# Virtuous client hash: 820fbdf787e344707ffa7558e8d608ccb3d1817d3ceb7f2749685da90e204f72
# Code generated by Virtuous runtime; DO NOT EDIT.

"""Runtime-generated Python client for Virtuous RPC routes."""

from dataclasses import dataclass, fields, is_dataclass
import http
import json
import types
from typing import Any, Union, get_args, get_origin, get_type_hints
from urllib import error, parse, request

# Type definitions
@dataclass
class Job:
    id: int
    job_key: str
    display_name: str
    description: str
    default_params_json: str
    nodes: list["JobNode"]
    edges: list["JobEdge"]
    schedules: list["JobSchedule"]

@dataclass
class JobByKeyRequest:
    job_key: str

@dataclass
class JobByKeyResponse:
    job: "Job"
    error: str | None = None

@dataclass
class JobEdge:
    from_step_key: str
    to_step_key: str

@dataclass
class JobNode:
    step_key: str
    display_name: str
    description: str
    kind: str
    depends_on: list[str]

@dataclass
class JobSchedule:
    schedule_key: str
    cron_expr: str
    timezone: str
    is_enabled: bool
    description: str

@dataclass
class JobsGetManyRequest:
    limit: int
    offset: int

@dataclass
class JobsGetManyResponse:
    data: list["Job"]
    total: int
    error: str | None = None

@dataclass
class Run:
    summary: "RunSummary"
    steps: list["RunStep"]

@dataclass
class RunByIDRequest:
    id: int

@dataclass
class RunByIDResponse:
    run: "Run"
    events: list["RunEvent"]
    error: str | None = None

@dataclass
class RunCreateRequest:
    job_key: str
    triggered_by: str
    note: str

@dataclass
class RunCreateResponse:
    run: "RunSummary"
    error: str | None = None

@dataclass
class RunEvent:
    id: int
    step_key: str
    event_type: str
    level: str
    message: str
    event_data_json: str
    created_at: str

@dataclass
class RunEventsGetManyRequest:
    run_id: int
    limit: int
    offset: int
    tail: bool

@dataclass
class RunEventsGetManyResponse:
    data: list["RunEvent"]
    total: int
    error: str | None = None

@dataclass
class RunRerunStepCreateRequest:
    source_run_id: int
    step_key: str
    triggered_by: str

@dataclass
class RunStep:
    step_key: str
    status: str
    attempt: int
    started_at: str
    completed_at: str
    duration_ms: int
    output_json: str
    error_message: str
    log_excerpt: str

@dataclass
class RunSummary:
    id: int
    run_key: str
    job_id: int
    job_key: str
    status: str
    triggered_by: str
    queued_at: str
    started_at: str
    completed_at: str
    parent_run_id: int
    rerun_step_key: str
    error_message: str
    pending_steps: int
    running_steps: int
    success_steps: int
    failed_steps: int
    skipped_steps: int

@dataclass
class RunTerminateRequest:
    id: int

@dataclass
class RunTerminateResponse:
    run: "RunSummary"
    error: str | None = None

@dataclass
class RunsGetManyRequest:
    job_key: str
    limit: int
    offset: int

@dataclass
class RunsGetManyResponse:
    data: list["RunSummary"]
    total: int
    error: str | None = None

@dataclass
class Schedule:
    id: int
    job_id: int
    job_key: str
    schedule_key: str
    cron_expr: str
    timezone: str
    is_enabled: bool
    description: str

@dataclass
class SchedulesGetManyRequest:
    limit: int
    offset: int

@dataclass
class SchedulesGetManyResponse:
    data: list["Schedule"]
    total: int
    error: str | None = None

class RPCError(RuntimeError):
    def __init__(self, status: int, body: Any, message: str):
        super().__init__(message)
        self.status = status
        self.body = body
class _jobsService:
    def __init__(self, basepath: str):
        self._basepath = basepath
    def JobByKey(self, body:"JobByKeyRequest") ->"JobByKeyResponse":
        headers = {
            "Accept": "application/json",
            "Content-Type": "application/json",
        }
        url = self._basepath + "/rpc/jobs/job-by-key"
        data = None
        data = json.dumps(_encode_value(body)).encode("utf-8")
        req = request.Request(url, data=data, method="POST", headers=headers)
        status = 0
        text = ""
        try:
            with request.urlopen(req) as resp:
                status = resp.getcode()
                text = resp.read().decode("utf-8")
        except error.HTTPError as err:
            status = err.code
            text = err.read().decode("utf-8")
        body = None
        if text:
            try:
                body = json.loads(text)
            except json.JSONDecodeError as err:
                raise RPCError(status, None, f"{status} {_status_text(status)}") from err
        if status >= 400:
            err_body = _decode_value("JobByKeyResponse", body)
            raise RPCError(status, err_body, f"{status} {_status_text(status)}")
        return _decode_value("JobByKeyResponse", body)
    def JobsGetMany(self, body:"JobsGetManyRequest") ->"JobsGetManyResponse":
        headers = {
            "Accept": "application/json",
            "Content-Type": "application/json",
        }
        url = self._basepath + "/rpc/jobs/jobs-get-many"
        data = None
        data = json.dumps(_encode_value(body)).encode("utf-8")
        req = request.Request(url, data=data, method="POST", headers=headers)
        status = 0
        text = ""
        try:
            with request.urlopen(req) as resp:
                status = resp.getcode()
                text = resp.read().decode("utf-8")
        except error.HTTPError as err:
            status = err.code
            text = err.read().decode("utf-8")
        body = None
        if text:
            try:
                body = json.loads(text)
            except json.JSONDecodeError as err:
                raise RPCError(status, None, f"{status} {_status_text(status)}") from err
        if status >= 400:
            err_body = _decode_value("JobsGetManyResponse", body)
            raise RPCError(status, err_body, f"{status} {_status_text(status)}")
        return _decode_value("JobsGetManyResponse", body)
class _runsService:
    def __init__(self, basepath: str):
        self._basepath = basepath
    def RunByID(self, body:"RunByIDRequest") ->"RunByIDResponse":
        headers = {
            "Accept": "application/json",
            "Content-Type": "application/json",
        }
        url = self._basepath + "/rpc/runs/run-by-id"
        data = None
        data = json.dumps(_encode_value(body)).encode("utf-8")
        req = request.Request(url, data=data, method="POST", headers=headers)
        status = 0
        text = ""
        try:
            with request.urlopen(req) as resp:
                status = resp.getcode()
                text = resp.read().decode("utf-8")
        except error.HTTPError as err:
            status = err.code
            text = err.read().decode("utf-8")
        body = None
        if text:
            try:
                body = json.loads(text)
            except json.JSONDecodeError as err:
                raise RPCError(status, None, f"{status} {_status_text(status)}") from err
        if status >= 400:
            err_body = _decode_value("RunByIDResponse", body)
            raise RPCError(status, err_body, f"{status} {_status_text(status)}")
        return _decode_value("RunByIDResponse", body)
    def RunCreate(self, body:"RunCreateRequest") ->"RunCreateResponse":
        headers = {
            "Accept": "application/json",
            "Content-Type": "application/json",
        }
        url = self._basepath + "/rpc/runs/run-create"
        data = None
        data = json.dumps(_encode_value(body)).encode("utf-8")
        req = request.Request(url, data=data, method="POST", headers=headers)
        status = 0
        text = ""
        try:
            with request.urlopen(req) as resp:
                status = resp.getcode()
                text = resp.read().decode("utf-8")
        except error.HTTPError as err:
            status = err.code
            text = err.read().decode("utf-8")
        body = None
        if text:
            try:
                body = json.loads(text)
            except json.JSONDecodeError as err:
                raise RPCError(status, None, f"{status} {_status_text(status)}") from err
        if status >= 400:
            err_body = _decode_value("RunCreateResponse", body)
            raise RPCError(status, err_body, f"{status} {_status_text(status)}")
        return _decode_value("RunCreateResponse", body)
    def RunEventsGetMany(self, body:"RunEventsGetManyRequest") ->"RunEventsGetManyResponse":
        headers = {
            "Accept": "application/json",
            "Content-Type": "application/json",
        }
        url = self._basepath + "/rpc/runs/run-events-get-many"
        data = None
        data = json.dumps(_encode_value(body)).encode("utf-8")
        req = request.Request(url, data=data, method="POST", headers=headers)
        status = 0
        text = ""
        try:
            with request.urlopen(req) as resp:
                status = resp.getcode()
                text = resp.read().decode("utf-8")
        except error.HTTPError as err:
            status = err.code
            text = err.read().decode("utf-8")
        body = None
        if text:
            try:
                body = json.loads(text)
            except json.JSONDecodeError as err:
                raise RPCError(status, None, f"{status} {_status_text(status)}") from err
        if status >= 400:
            err_body = _decode_value("RunEventsGetManyResponse", body)
            raise RPCError(status, err_body, f"{status} {_status_text(status)}")
        return _decode_value("RunEventsGetManyResponse", body)
    def RunRerunStepCreate(self, body:"RunRerunStepCreateRequest") ->"RunCreateResponse":
        headers = {
            "Accept": "application/json",
            "Content-Type": "application/json",
        }
        url = self._basepath + "/rpc/runs/run-rerun-step-create"
        data = None
        data = json.dumps(_encode_value(body)).encode("utf-8")
        req = request.Request(url, data=data, method="POST", headers=headers)
        status = 0
        text = ""
        try:
            with request.urlopen(req) as resp:
                status = resp.getcode()
                text = resp.read().decode("utf-8")
        except error.HTTPError as err:
            status = err.code
            text = err.read().decode("utf-8")
        body = None
        if text:
            try:
                body = json.loads(text)
            except json.JSONDecodeError as err:
                raise RPCError(status, None, f"{status} {_status_text(status)}") from err
        if status >= 400:
            err_body = _decode_value("RunCreateResponse", body)
            raise RPCError(status, err_body, f"{status} {_status_text(status)}")
        return _decode_value("RunCreateResponse", body)
    def RunTerminate(self, body:"RunTerminateRequest") ->"RunTerminateResponse":
        headers = {
            "Accept": "application/json",
            "Content-Type": "application/json",
        }
        url = self._basepath + "/rpc/runs/run-terminate"
        data = None
        data = json.dumps(_encode_value(body)).encode("utf-8")
        req = request.Request(url, data=data, method="POST", headers=headers)
        status = 0
        text = ""
        try:
            with request.urlopen(req) as resp:
                status = resp.getcode()
                text = resp.read().decode("utf-8")
        except error.HTTPError as err:
            status = err.code
            text = err.read().decode("utf-8")
        body = None
        if text:
            try:
                body = json.loads(text)
            except json.JSONDecodeError as err:
                raise RPCError(status, None, f"{status} {_status_text(status)}") from err
        if status >= 400:
            err_body = _decode_value("RunTerminateResponse", body)
            raise RPCError(status, err_body, f"{status} {_status_text(status)}")
        return _decode_value("RunTerminateResponse", body)
    def RunsGetMany(self, body:"RunsGetManyRequest") ->"RunsGetManyResponse":
        headers = {
            "Accept": "application/json",
            "Content-Type": "application/json",
        }
        url = self._basepath + "/rpc/runs/runs-get-many"
        data = None
        data = json.dumps(_encode_value(body)).encode("utf-8")
        req = request.Request(url, data=data, method="POST", headers=headers)
        status = 0
        text = ""
        try:
            with request.urlopen(req) as resp:
                status = resp.getcode()
                text = resp.read().decode("utf-8")
        except error.HTTPError as err:
            status = err.code
            text = err.read().decode("utf-8")
        body = None
        if text:
            try:
                body = json.loads(text)
            except json.JSONDecodeError as err:
                raise RPCError(status, None, f"{status} {_status_text(status)}") from err
        if status >= 400:
            err_body = _decode_value("RunsGetManyResponse", body)
            raise RPCError(status, err_body, f"{status} {_status_text(status)}")
        return _decode_value("RunsGetManyResponse", body)
class _schedulesService:
    def __init__(self, basepath: str):
        self._basepath = basepath
    def SchedulesGetMany(self, body:"SchedulesGetManyRequest") ->"SchedulesGetManyResponse":
        headers = {
            "Accept": "application/json",
            "Content-Type": "application/json",
        }
        url = self._basepath + "/rpc/schedules/schedules-get-many"
        data = None
        data = json.dumps(_encode_value(body)).encode("utf-8")
        req = request.Request(url, data=data, method="POST", headers=headers)
        status = 0
        text = ""
        try:
            with request.urlopen(req) as resp:
                status = resp.getcode()
                text = resp.read().decode("utf-8")
        except error.HTTPError as err:
            status = err.code
            text = err.read().decode("utf-8")
        body = None
        if text:
            try:
                body = json.loads(text)
            except json.JSONDecodeError as err:
                raise RPCError(status, None, f"{status} {_status_text(status)}") from err
        if status >= 400:
            err_body = _decode_value("SchedulesGetManyResponse", body)
            raise RPCError(status, err_body, f"{status} {_status_text(status)}")
        return _decode_value("SchedulesGetManyResponse", body)

class Client:
    def __init__(self, basepath: str = "/"):
        self._basepath = basepath
        self.jobs = _jobsService(basepath)
        self.runs = _runsService(basepath)
        self.schedules = _schedulesService(basepath)


def create_client(basepath: str = "/") -> Client:
    return Client(basepath)


def _status_text(code: int) -> str:
    try:
        return http.HTTPStatus(code).phrase
    except ValueError:
        return "HTTP error"


def _decode_value(tp: Any, value: Any) -> Any:
    if value is None:
        return None
    origin = get_origin(tp)
    if origin is None:
        if is_dataclass(tp):
            return _decode_dataclass(tp, value)
        return value
    if origin is list:
        args = get_args(tp)
        elem_type = args[0] if args else Any
        return [_decode_value(elem_type, item) for item in value]
    if origin is dict:
        args = get_args(tp)
        value_type = args[1] if len(args) > 1 else Any
        return {key: _decode_value(value_type, item) for key, item in value.items()}
    if origin in (Union, types.UnionType):
        args = [arg for arg in get_args(tp) if arg is not type(None)]
        if len(args) == 1:
            return _decode_value(args[0], value)
        return value
    return value


def _decode_dataclass(cls: type[Any], data: Any) -> Any:
    if data is None:
        return None
    if not isinstance(data, dict):
        return data
    type_hints = get_type_hints(cls)
    kwargs: dict[str, Any] = {}
    for field in fields(cls):
        if field.name in data:
            field_type = type_hints.get(field.name, Any)
            kwargs[field.name] = _decode_value(field_type, data[field.name])
    return cls(**kwargs)


def _encode_value(value: Any) -> Any:
    if value is None:
        return None
    if is_dataclass(value):
        return {field.name: _encode_value(getattr(value, field.name)) for field in fields(value)}
    if isinstance(value, list):
        return [_encode_value(item) for item in value]
    if isinstance(value, dict):
        return {key: _encode_value(item) for key, item in value.items()}
    return value


def _append_query(url: str, key: str, value: str) -> str:
    parts = parse.urlsplit(url)
    query = parse.parse_qsl(parts.query, keep_blank_values=True)
    query.append((key, value))
    new_query = parse.urlencode(query)
    return parse.urlunsplit((parts.scheme, parts.netloc, parts.path, new_query, parts.fragment))
