// Virtuous client hash: ce48c2cbc98ec24fa92858c84927d9f3665f95dc0703032f9343ca59fb2a0bfe
// Code generated by Virtuous runtime; DO NOT EDIT.

export type AuthOptions = {
	auth?: string
}

export class RPCError<E = unknown> extends Error {
	status: number
	body: E | null
	constructor(status: number, body: E | null, message: string) {
		super(message)
		this.status = status
		this.body = body
	}
}


export interface Job {
	id: number;
	job_key: string;
	display_name: string;
	description: string;
	default_params_json: string;
	nodes: JobNode[];
	edges: JobEdge[];
	schedules: JobSchedule[];
}

export interface JobByKeyRequest {
	job_key: string;
}

export interface JobByKeyResponse {
	job: Job;
	error?: string;
}

export interface JobEdge {
	from_step_key: string;
	to_step_key: string;
}

export interface JobNode {
	step_key: string;
	display_name: string;
	description: string;
	kind: string;
	depends_on: string[];
}

export interface JobSchedule {
	schedule_key: string;
	cron_expr: string;
	timezone: string;
	is_enabled: boolean;
	description: string;
}

export interface JobsGetManyRequest {
	limit: number;
	offset: number;
}

export interface JobsGetManyResponse {
	data: Job[];
	total: number;
	error?: string;
}

export interface Run {
	summary: RunSummary;
	steps: RunStep[];
}

export interface RunByIDRequest {
	id: number;
}

export interface RunByIDResponse {
	run: Run;
	events: RunEvent[];
	error?: string;
}

export interface RunCreateRequest {
	job_key: string;
	triggered_by: string;
	note: string;
}

export interface RunCreateResponse {
	run: RunSummary;
	error?: string;
}

export interface RunEvent {
	id: number;
	step_key: string;
	event_type: string;
	level: string;
	message: string;
	event_data_json: string;
	created_at: string;
}

export interface RunEventsGetManyRequest {
	run_id: number;
	limit: number;
	offset: number;
	tail: boolean;
}

export interface RunEventsGetManyResponse {
	data: RunEvent[];
	total: number;
	error?: string;
}

export interface RunRerunStepCreateRequest {
	source_run_id: number;
	step_key: string;
	triggered_by: string;
}

export interface RunStep {
	step_key: string;
	status: string;
	attempt: number;
	started_at: string;
	completed_at: string;
	duration_ms: number;
	output_json: string;
	error_message: string;
	log_excerpt: string;
}

export interface RunSummary {
	id: number;
	run_key: string;
	job_id: number;
	job_key: string;
	status: string;
	triggered_by: string;
	queued_at: string;
	started_at: string;
	completed_at: string;
	parent_run_id: number;
	rerun_step_key: string;
	error_message: string;
	pending_steps: number;
	running_steps: number;
	success_steps: number;
	failed_steps: number;
	skipped_steps: number;
}

export interface RunTerminateRequest {
	id: number;
}

export interface RunTerminateResponse {
	run: RunSummary;
	error?: string;
}

export interface RunsGetManyRequest {
	job_key: string;
	limit: number;
	offset: number;
}

export interface RunsGetManyResponse {
	data: RunSummary[];
	total: number;
	error?: string;
}

export interface Schedule {
	id: number;
	job_id: number;
	job_key: string;
	schedule_key: string;
	cron_expr: string;
	timezone: string;
	is_enabled: boolean;
	description: string;
}

export interface SchedulesGetManyRequest {
	limit: number;
	offset: number;
}

export interface SchedulesGetManyResponse {
	data: Schedule[];
	total: number;
	error?: string;
}

export function createClient(basepath: string = "/") {
	return {
		jobs: {
			async JobByKey(request: JobByKeyRequest, options?: AuthOptions): Promise<JobByKeyResponse> {
				const headers: Record<string, string> = {
					"Accept": "application/json",
					"Content-Type": "application/json",
				}
				let url = basepath + "/rpc/jobs/job-by-key"
				const response = await fetch(url, {
					method: "POST",
					headers,
					body: JSON.stringify(request),
				})
				const text = await response.text()
				let json: JobByKeyResponse | null = null
				if (text) {
					try {
						json = JSON.parse(text)
					} catch (e) {
						if (!response.ok) {
							throw new RPCError<JobByKeyResponse>(response.status, null, response.status + " " + response.statusText)
						}
						throw e
					}
				}
				if (!response.ok) {
					throw new RPCError<JobByKeyResponse>(response.status, json as JobByKeyResponse, response.status + " " + response.statusText)
				}
				return json as JobByKeyResponse
			},
			async JobsGetMany(request: JobsGetManyRequest, options?: AuthOptions): Promise<JobsGetManyResponse> {
				const headers: Record<string, string> = {
					"Accept": "application/json",
					"Content-Type": "application/json",
				}
				let url = basepath + "/rpc/jobs/jobs-get-many"
				const response = await fetch(url, {
					method: "POST",
					headers,
					body: JSON.stringify(request),
				})
				const text = await response.text()
				let json: JobsGetManyResponse | null = null
				if (text) {
					try {
						json = JSON.parse(text)
					} catch (e) {
						if (!response.ok) {
							throw new RPCError<JobsGetManyResponse>(response.status, null, response.status + " " + response.statusText)
						}
						throw e
					}
				}
				if (!response.ok) {
					throw new RPCError<JobsGetManyResponse>(response.status, json as JobsGetManyResponse, response.status + " " + response.statusText)
				}
				return json as JobsGetManyResponse
			},
		},
		runs: {
			async RunByID(request: RunByIDRequest, options?: AuthOptions): Promise<RunByIDResponse> {
				const headers: Record<string, string> = {
					"Accept": "application/json",
					"Content-Type": "application/json",
				}
				let url = basepath + "/rpc/runs/run-by-id"
				const response = await fetch(url, {
					method: "POST",
					headers,
					body: JSON.stringify(request),
				})
				const text = await response.text()
				let json: RunByIDResponse | null = null
				if (text) {
					try {
						json = JSON.parse(text)
					} catch (e) {
						if (!response.ok) {
							throw new RPCError<RunByIDResponse>(response.status, null, response.status + " " + response.statusText)
						}
						throw e
					}
				}
				if (!response.ok) {
					throw new RPCError<RunByIDResponse>(response.status, json as RunByIDResponse, response.status + " " + response.statusText)
				}
				return json as RunByIDResponse
			},
			async RunCreate(request: RunCreateRequest, options?: AuthOptions): Promise<RunCreateResponse> {
				const headers: Record<string, string> = {
					"Accept": "application/json",
					"Content-Type": "application/json",
				}
				let url = basepath + "/rpc/runs/run-create"
				const response = await fetch(url, {
					method: "POST",
					headers,
					body: JSON.stringify(request),
				})
				const text = await response.text()
				let json: RunCreateResponse | null = null
				if (text) {
					try {
						json = JSON.parse(text)
					} catch (e) {
						if (!response.ok) {
							throw new RPCError<RunCreateResponse>(response.status, null, response.status + " " + response.statusText)
						}
						throw e
					}
				}
				if (!response.ok) {
					throw new RPCError<RunCreateResponse>(response.status, json as RunCreateResponse, response.status + " " + response.statusText)
				}
				return json as RunCreateResponse
			},
			async RunEventsGetMany(request: RunEventsGetManyRequest, options?: AuthOptions): Promise<RunEventsGetManyResponse> {
				const headers: Record<string, string> = {
					"Accept": "application/json",
					"Content-Type": "application/json",
				}
				let url = basepath + "/rpc/runs/run-events-get-many"
				const response = await fetch(url, {
					method: "POST",
					headers,
					body: JSON.stringify(request),
				})
				const text = await response.text()
				let json: RunEventsGetManyResponse | null = null
				if (text) {
					try {
						json = JSON.parse(text)
					} catch (e) {
						if (!response.ok) {
							throw new RPCError<RunEventsGetManyResponse>(response.status, null, response.status + " " + response.statusText)
						}
						throw e
					}
				}
				if (!response.ok) {
					throw new RPCError<RunEventsGetManyResponse>(response.status, json as RunEventsGetManyResponse, response.status + " " + response.statusText)
				}
				return json as RunEventsGetManyResponse
			},
			async RunRerunStepCreate(request: RunRerunStepCreateRequest, options?: AuthOptions): Promise<RunCreateResponse> {
				const headers: Record<string, string> = {
					"Accept": "application/json",
					"Content-Type": "application/json",
				}
				let url = basepath + "/rpc/runs/run-rerun-step-create"
				const response = await fetch(url, {
					method: "POST",
					headers,
					body: JSON.stringify(request),
				})
				const text = await response.text()
				let json: RunCreateResponse | null = null
				if (text) {
					try {
						json = JSON.parse(text)
					} catch (e) {
						if (!response.ok) {
							throw new RPCError<RunCreateResponse>(response.status, null, response.status + " " + response.statusText)
						}
						throw e
					}
				}
				if (!response.ok) {
					throw new RPCError<RunCreateResponse>(response.status, json as RunCreateResponse, response.status + " " + response.statusText)
				}
				return json as RunCreateResponse
			},
			async RunTerminate(request: RunTerminateRequest, options?: AuthOptions): Promise<RunTerminateResponse> {
				const headers: Record<string, string> = {
					"Accept": "application/json",
					"Content-Type": "application/json",
				}
				let url = basepath + "/rpc/runs/run-terminate"
				const response = await fetch(url, {
					method: "POST",
					headers,
					body: JSON.stringify(request),
				})
				const text = await response.text()
				let json: RunTerminateResponse | null = null
				if (text) {
					try {
						json = JSON.parse(text)
					} catch (e) {
						if (!response.ok) {
							throw new RPCError<RunTerminateResponse>(response.status, null, response.status + " " + response.statusText)
						}
						throw e
					}
				}
				if (!response.ok) {
					throw new RPCError<RunTerminateResponse>(response.status, json as RunTerminateResponse, response.status + " " + response.statusText)
				}
				return json as RunTerminateResponse
			},
			async RunsGetMany(request: RunsGetManyRequest, options?: AuthOptions): Promise<RunsGetManyResponse> {
				const headers: Record<string, string> = {
					"Accept": "application/json",
					"Content-Type": "application/json",
				}
				let url = basepath + "/rpc/runs/runs-get-many"
				const response = await fetch(url, {
					method: "POST",
					headers,
					body: JSON.stringify(request),
				})
				const text = await response.text()
				let json: RunsGetManyResponse | null = null
				if (text) {
					try {
						json = JSON.parse(text)
					} catch (e) {
						if (!response.ok) {
							throw new RPCError<RunsGetManyResponse>(response.status, null, response.status + " " + response.statusText)
						}
						throw e
					}
				}
				if (!response.ok) {
					throw new RPCError<RunsGetManyResponse>(response.status, json as RunsGetManyResponse, response.status + " " + response.statusText)
				}
				return json as RunsGetManyResponse
			},
		},
		schedules: {
			async SchedulesGetMany(request: SchedulesGetManyRequest, options?: AuthOptions): Promise<SchedulesGetManyResponse> {
				const headers: Record<string, string> = {
					"Accept": "application/json",
					"Content-Type": "application/json",
				}
				let url = basepath + "/rpc/schedules/schedules-get-many"
				const response = await fetch(url, {
					method: "POST",
					headers,
					body: JSON.stringify(request),
				})
				const text = await response.text()
				let json: SchedulesGetManyResponse | null = null
				if (text) {
					try {
						json = JSON.parse(text)
					} catch (e) {
						if (!response.ok) {
							throw new RPCError<SchedulesGetManyResponse>(response.status, null, response.status + " " + response.statusText)
						}
						throw e
					}
				}
				if (!response.ok) {
					throw new RPCError<SchedulesGetManyResponse>(response.status, json as SchedulesGetManyResponse, response.status + " " + response.statusText)
				}
				return json as SchedulesGetManyResponse
			},
		},
	}
}
