// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: 001_jobs.sql

package postgresgen

import (
	"context"
	"encoding/json"
)

const jobCount = `-- name: JobCount :one
SELECT COUNT(1) AS total
FROM jobs
`

func (q *Queries) JobCount(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, jobCount)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const jobDeleteByID = `-- name: JobDeleteByID :exec
DELETE FROM jobs
WHERE id = $1
`

func (q *Queries) JobDeleteByID(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, jobDeleteByID, id)
	return err
}

const jobEdgeCreate = `-- name: JobEdgeCreate :one
INSERT INTO job_edges (job_id, from_step_key, to_step_key)
VALUES ($1, $2, $3)
RETURNING id, job_id, from_step_key, to_step_key, created_at
`

type JobEdgeCreateParams struct {
	JobID       int64  `json:"job_id"`
	FromStepKey string `json:"from_step_key"`
	ToStepKey   string `json:"to_step_key"`
}

func (q *Queries) JobEdgeCreate(ctx context.Context, arg JobEdgeCreateParams) (JobEdge, error) {
	row := q.db.QueryRowContext(ctx, jobEdgeCreate, arg.JobID, arg.FromStepKey, arg.ToStepKey)
	var i JobEdge
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.FromStepKey,
		&i.ToStepKey,
		&i.CreatedAt,
	)
	return i, err
}

const jobEdgeDeleteByJobID = `-- name: JobEdgeDeleteByJobID :exec
DELETE FROM job_edges
WHERE job_id = $1
`

func (q *Queries) JobEdgeDeleteByJobID(ctx context.Context, jobID int64) error {
	_, err := q.db.ExecContext(ctx, jobEdgeDeleteByJobID, jobID)
	return err
}

const jobEdgeGetManyByJobID = `-- name: JobEdgeGetManyByJobID :many
SELECT id, job_id, from_step_key, to_step_key, created_at
FROM job_edges
WHERE job_id = $1
ORDER BY id
`

func (q *Queries) JobEdgeGetManyByJobID(ctx context.Context, jobID int64) ([]JobEdge, error) {
	rows, err := q.db.QueryContext(ctx, jobEdgeGetManyByJobID, jobID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []JobEdge
	for rows.Next() {
		var i JobEdge
		if err := rows.Scan(
			&i.ID,
			&i.JobID,
			&i.FromStepKey,
			&i.ToStepKey,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const jobGetByID = `-- name: JobGetByID :one
SELECT id, job_key, display_name, description, default_params_json, created_at, updated_at
FROM jobs
WHERE id = $1
`

func (q *Queries) JobGetByID(ctx context.Context, id int64) (Job, error) {
	row := q.db.QueryRowContext(ctx, jobGetByID, id)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.JobKey,
		&i.DisplayName,
		&i.Description,
		&i.DefaultParamsJson,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const jobGetByKey = `-- name: JobGetByKey :one
SELECT id, job_key, display_name, description, default_params_json, created_at, updated_at
FROM jobs
WHERE job_key = $1
`

func (q *Queries) JobGetByKey(ctx context.Context, jobKey string) (Job, error) {
	row := q.db.QueryRowContext(ctx, jobGetByKey, jobKey)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.JobKey,
		&i.DisplayName,
		&i.Description,
		&i.DefaultParamsJson,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const jobGetMany = `-- name: JobGetMany :many
SELECT id, job_key, display_name, description, default_params_json, created_at, updated_at
FROM jobs
ORDER BY id
LIMIT $1 OFFSET $2
`

type JobGetManyParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) JobGetMany(ctx context.Context, arg JobGetManyParams) ([]Job, error) {
	rows, err := q.db.QueryContext(ctx, jobGetMany, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Job
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.JobKey,
			&i.DisplayName,
			&i.Description,
			&i.DefaultParamsJson,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const jobNodeCreate = `-- name: JobNodeCreate :one
INSERT INTO job_nodes (job_id, step_key, display_name, description, kind, metadata_json, sort_index)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, job_id, step_key, display_name, description, kind, metadata_json, sort_index, created_at
`

type JobNodeCreateParams struct {
	JobID        int64           `json:"job_id"`
	StepKey      string          `json:"step_key"`
	DisplayName  string          `json:"display_name"`
	Description  string          `json:"description"`
	Kind         string          `json:"kind"`
	MetadataJson json.RawMessage `json:"metadata_json"`
	SortIndex    int64           `json:"sort_index"`
}

func (q *Queries) JobNodeCreate(ctx context.Context, arg JobNodeCreateParams) (JobNode, error) {
	row := q.db.QueryRowContext(ctx, jobNodeCreate,
		arg.JobID,
		arg.StepKey,
		arg.DisplayName,
		arg.Description,
		arg.Kind,
		arg.MetadataJson,
		arg.SortIndex,
	)
	var i JobNode
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.StepKey,
		&i.DisplayName,
		&i.Description,
		&i.Kind,
		&i.MetadataJson,
		&i.SortIndex,
		&i.CreatedAt,
	)
	return i, err
}

const jobNodeDeleteByJobID = `-- name: JobNodeDeleteByJobID :exec
DELETE FROM job_nodes
WHERE job_id = $1
`

func (q *Queries) JobNodeDeleteByJobID(ctx context.Context, jobID int64) error {
	_, err := q.db.ExecContext(ctx, jobNodeDeleteByJobID, jobID)
	return err
}

const jobNodeGetManyByJobID = `-- name: JobNodeGetManyByJobID :many
SELECT id, job_id, step_key, display_name, description, kind, metadata_json, sort_index, created_at
FROM job_nodes
WHERE job_id = $1
ORDER BY sort_index, step_key
`

func (q *Queries) JobNodeGetManyByJobID(ctx context.Context, jobID int64) ([]JobNode, error) {
	rows, err := q.db.QueryContext(ctx, jobNodeGetManyByJobID, jobID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []JobNode
	for rows.Next() {
		var i JobNode
		if err := rows.Scan(
			&i.ID,
			&i.JobID,
			&i.StepKey,
			&i.DisplayName,
			&i.Description,
			&i.Kind,
			&i.MetadataJson,
			&i.SortIndex,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const jobUpsert = `-- name: JobUpsert :one
INSERT INTO jobs (job_key, display_name, description, default_params_json)
VALUES ($1, $2, $3, $4)
ON CONFLICT(job_key)
DO UPDATE SET
    display_name = excluded.display_name,
    description = excluded.description,
    default_params_json = excluded.default_params_json,
    updated_at = now()
RETURNING id, job_key, display_name, description, default_params_json, created_at, updated_at
`

type JobUpsertParams struct {
	JobKey            string          `json:"job_key"`
	DisplayName       string          `json:"display_name"`
	Description       string          `json:"description"`
	DefaultParamsJson json.RawMessage `json:"default_params_json"`
}

func (q *Queries) JobUpsert(ctx context.Context, arg JobUpsertParams) (Job, error) {
	row := q.db.QueryRowContext(ctx, jobUpsert,
		arg.JobKey,
		arg.DisplayName,
		arg.Description,
		arg.DefaultParamsJson,
	)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.JobKey,
		&i.DisplayName,
		&i.Description,
		&i.DefaultParamsJson,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
