// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: 002_runs.sql

package postgresgen

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"
)

const runCount = `-- name: RunCount :one
SELECT COUNT(1) AS total
FROM runs
`

func (q *Queries) RunCount(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, runCount)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const runCountByJobID = `-- name: RunCountByJobID :one
SELECT COUNT(1) AS total
FROM runs
WHERE job_id = $1
`

func (q *Queries) RunCountByJobID(ctx context.Context, jobID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, runCountByJobID, jobID)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const runCreate = `-- name: RunCreate :one
INSERT INTO runs (run_key, job_id, status, triggered_by, params_json, queued_at, started_at, completed_at, parent_run_id, rerun_step_key, error_message)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id, run_key, job_id, status, triggered_by, params_json, queued_at, started_at, completed_at, parent_run_id, rerun_step_key, error_message, created_at, updated_at
`

type RunCreateParams struct {
	RunKey       string          `json:"run_key"`
	JobID        int64           `json:"job_id"`
	Status       string          `json:"status"`
	TriggeredBy  string          `json:"triggered_by"`
	ParamsJson   json.RawMessage `json:"params_json"`
	QueuedAt     time.Time       `json:"queued_at"`
	StartedAt    sql.NullTime    `json:"started_at"`
	CompletedAt  sql.NullTime    `json:"completed_at"`
	ParentRunID  int64           `json:"parent_run_id"`
	RerunStepKey string          `json:"rerun_step_key"`
	ErrorMessage string          `json:"error_message"`
}

func (q *Queries) RunCreate(ctx context.Context, arg RunCreateParams) (Run, error) {
	row := q.db.QueryRowContext(ctx, runCreate,
		arg.RunKey,
		arg.JobID,
		arg.Status,
		arg.TriggeredBy,
		arg.ParamsJson,
		arg.QueuedAt,
		arg.StartedAt,
		arg.CompletedAt,
		arg.ParentRunID,
		arg.RerunStepKey,
		arg.ErrorMessage,
	)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.RunKey,
		&i.JobID,
		&i.Status,
		&i.TriggeredBy,
		&i.ParamsJson,
		&i.QueuedAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.ParentRunID,
		&i.RerunStepKey,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const runEventCountByRunID = `-- name: RunEventCountByRunID :one
SELECT COUNT(*)
FROM run_events
WHERE run_id = $1
`

func (q *Queries) RunEventCountByRunID(ctx context.Context, runID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, runEventCountByRunID, runID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const runEventCreate = `-- name: RunEventCreate :one
INSERT INTO run_events (run_id, step_key, event_type, level, message, event_data_json)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, run_id, step_key, event_type, level, message, event_data_json, created_at
`

type RunEventCreateParams struct {
	RunID         int64           `json:"run_id"`
	StepKey       string          `json:"step_key"`
	EventType     string          `json:"event_type"`
	Level         string          `json:"level"`
	Message       string          `json:"message"`
	EventDataJson json.RawMessage `json:"event_data_json"`
}

func (q *Queries) RunEventCreate(ctx context.Context, arg RunEventCreateParams) (RunEvent, error) {
	row := q.db.QueryRowContext(ctx, runEventCreate,
		arg.RunID,
		arg.StepKey,
		arg.EventType,
		arg.Level,
		arg.Message,
		arg.EventDataJson,
	)
	var i RunEvent
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.StepKey,
		&i.EventType,
		&i.Level,
		&i.Message,
		&i.EventDataJson,
		&i.CreatedAt,
	)
	return i, err
}

const runEventGetManyByRunID = `-- name: RunEventGetManyByRunID :many
SELECT id, run_id, step_key, event_type, level, message, event_data_json, created_at
FROM run_events
WHERE run_id = $1
ORDER BY id
LIMIT $2 OFFSET $3
`

type RunEventGetManyByRunIDParams struct {
	RunID  int64 `json:"run_id"`
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) RunEventGetManyByRunID(ctx context.Context, arg RunEventGetManyByRunIDParams) ([]RunEvent, error) {
	rows, err := q.db.QueryContext(ctx, runEventGetManyByRunID, arg.RunID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RunEvent
	for rows.Next() {
		var i RunEvent
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.StepKey,
			&i.EventType,
			&i.Level,
			&i.Message,
			&i.EventDataJson,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const runGetByID = `-- name: RunGetByID :one
SELECT id, run_key, job_id, status, triggered_by, params_json, queued_at, started_at, completed_at, parent_run_id, rerun_step_key, error_message, created_at, updated_at
FROM runs
WHERE id = $1
`

func (q *Queries) RunGetByID(ctx context.Context, id int64) (Run, error) {
	row := q.db.QueryRowContext(ctx, runGetByID, id)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.RunKey,
		&i.JobID,
		&i.Status,
		&i.TriggeredBy,
		&i.ParamsJson,
		&i.QueuedAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.ParentRunID,
		&i.RerunStepKey,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const runGetByIDJoinedJobs = `-- name: RunGetByIDJoinedJobs :one
SELECT r.id,
       r.run_key,
       r.job_id,
       j.job_key,
       r.status,
       r.triggered_by,
       r.params_json,
       r.queued_at,
       r.started_at,
       r.completed_at,
       r.parent_run_id,
       r.rerun_step_key,
       r.error_message,
       r.created_at,
       r.updated_at
FROM runs r
JOIN jobs j ON j.id = r.job_id
WHERE r.id = $1
`

type RunGetByIDJoinedJobsRow struct {
	ID           int64           `json:"id"`
	RunKey       string          `json:"run_key"`
	JobID        int64           `json:"job_id"`
	JobKey       string          `json:"job_key"`
	Status       string          `json:"status"`
	TriggeredBy  string          `json:"triggered_by"`
	ParamsJson   json.RawMessage `json:"params_json"`
	QueuedAt     time.Time       `json:"queued_at"`
	StartedAt    sql.NullTime    `json:"started_at"`
	CompletedAt  sql.NullTime    `json:"completed_at"`
	ParentRunID  int64           `json:"parent_run_id"`
	RerunStepKey string          `json:"rerun_step_key"`
	ErrorMessage string          `json:"error_message"`
	CreatedAt    time.Time       `json:"created_at"`
	UpdatedAt    time.Time       `json:"updated_at"`
}

func (q *Queries) RunGetByIDJoinedJobs(ctx context.Context, id int64) (RunGetByIDJoinedJobsRow, error) {
	row := q.db.QueryRowContext(ctx, runGetByIDJoinedJobs, id)
	var i RunGetByIDJoinedJobsRow
	err := row.Scan(
		&i.ID,
		&i.RunKey,
		&i.JobID,
		&i.JobKey,
		&i.Status,
		&i.TriggeredBy,
		&i.ParamsJson,
		&i.QueuedAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.ParentRunID,
		&i.RerunStepKey,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const runGetMany = `-- name: RunGetMany :many
SELECT id, run_key, job_id, status, triggered_by, params_json, queued_at, started_at, completed_at, parent_run_id, rerun_step_key, error_message, created_at, updated_at
FROM runs
ORDER BY id DESC
LIMIT $1 OFFSET $2
`

type RunGetManyParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) RunGetMany(ctx context.Context, arg RunGetManyParams) ([]Run, error) {
	rows, err := q.db.QueryContext(ctx, runGetMany, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Run
	for rows.Next() {
		var i Run
		if err := rows.Scan(
			&i.ID,
			&i.RunKey,
			&i.JobID,
			&i.Status,
			&i.TriggeredBy,
			&i.ParamsJson,
			&i.QueuedAt,
			&i.StartedAt,
			&i.CompletedAt,
			&i.ParentRunID,
			&i.RerunStepKey,
			&i.ErrorMessage,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const runGetManyByJobID = `-- name: RunGetManyByJobID :many
SELECT id, run_key, job_id, status, triggered_by, params_json, queued_at, started_at, completed_at, parent_run_id, rerun_step_key, error_message, created_at, updated_at
FROM runs
WHERE job_id = $1
ORDER BY id DESC
LIMIT $2 OFFSET $3
`

type RunGetManyByJobIDParams struct {
	JobID  int64 `json:"job_id"`
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) RunGetManyByJobID(ctx context.Context, arg RunGetManyByJobIDParams) ([]Run, error) {
	rows, err := q.db.QueryContext(ctx, runGetManyByJobID, arg.JobID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Run
	for rows.Next() {
		var i Run
		if err := rows.Scan(
			&i.ID,
			&i.RunKey,
			&i.JobID,
			&i.Status,
			&i.TriggeredBy,
			&i.ParamsJson,
			&i.QueuedAt,
			&i.StartedAt,
			&i.CompletedAt,
			&i.ParentRunID,
			&i.RerunStepKey,
			&i.ErrorMessage,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const runGetManyByJobIDJoinedJobs = `-- name: RunGetManyByJobIDJoinedJobs :many
SELECT r.id,
       r.run_key,
       r.job_id,
       j.job_key,
       r.status,
       r.triggered_by,
       r.params_json,
       r.queued_at,
       r.started_at,
       r.completed_at,
       r.parent_run_id,
       r.rerun_step_key,
       r.error_message,
       r.created_at,
       r.updated_at
FROM runs r
JOIN jobs j ON j.id = r.job_id
WHERE r.job_id = $1
ORDER BY r.id DESC
LIMIT $2 OFFSET $3
`

type RunGetManyByJobIDJoinedJobsParams struct {
	JobID  int64 `json:"job_id"`
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type RunGetManyByJobIDJoinedJobsRow struct {
	ID           int64           `json:"id"`
	RunKey       string          `json:"run_key"`
	JobID        int64           `json:"job_id"`
	JobKey       string          `json:"job_key"`
	Status       string          `json:"status"`
	TriggeredBy  string          `json:"triggered_by"`
	ParamsJson   json.RawMessage `json:"params_json"`
	QueuedAt     time.Time       `json:"queued_at"`
	StartedAt    sql.NullTime    `json:"started_at"`
	CompletedAt  sql.NullTime    `json:"completed_at"`
	ParentRunID  int64           `json:"parent_run_id"`
	RerunStepKey string          `json:"rerun_step_key"`
	ErrorMessage string          `json:"error_message"`
	CreatedAt    time.Time       `json:"created_at"`
	UpdatedAt    time.Time       `json:"updated_at"`
}

func (q *Queries) RunGetManyByJobIDJoinedJobs(ctx context.Context, arg RunGetManyByJobIDJoinedJobsParams) ([]RunGetManyByJobIDJoinedJobsRow, error) {
	rows, err := q.db.QueryContext(ctx, runGetManyByJobIDJoinedJobs, arg.JobID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RunGetManyByJobIDJoinedJobsRow
	for rows.Next() {
		var i RunGetManyByJobIDJoinedJobsRow
		if err := rows.Scan(
			&i.ID,
			&i.RunKey,
			&i.JobID,
			&i.JobKey,
			&i.Status,
			&i.TriggeredBy,
			&i.ParamsJson,
			&i.QueuedAt,
			&i.StartedAt,
			&i.CompletedAt,
			&i.ParentRunID,
			&i.RerunStepKey,
			&i.ErrorMessage,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const runGetManyJoinedJobs = `-- name: RunGetManyJoinedJobs :many
SELECT r.id,
       r.run_key,
       r.job_id,
       j.job_key,
       r.status,
       r.triggered_by,
       r.params_json,
       r.queued_at,
       r.started_at,
       r.completed_at,
       r.parent_run_id,
       r.rerun_step_key,
       r.error_message,
       r.created_at,
       r.updated_at
FROM runs r
JOIN jobs j ON j.id = r.job_id
ORDER BY r.id DESC
LIMIT $1 OFFSET $2
`

type RunGetManyJoinedJobsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type RunGetManyJoinedJobsRow struct {
	ID           int64           `json:"id"`
	RunKey       string          `json:"run_key"`
	JobID        int64           `json:"job_id"`
	JobKey       string          `json:"job_key"`
	Status       string          `json:"status"`
	TriggeredBy  string          `json:"triggered_by"`
	ParamsJson   json.RawMessage `json:"params_json"`
	QueuedAt     time.Time       `json:"queued_at"`
	StartedAt    sql.NullTime    `json:"started_at"`
	CompletedAt  sql.NullTime    `json:"completed_at"`
	ParentRunID  int64           `json:"parent_run_id"`
	RerunStepKey string          `json:"rerun_step_key"`
	ErrorMessage string          `json:"error_message"`
	CreatedAt    time.Time       `json:"created_at"`
	UpdatedAt    time.Time       `json:"updated_at"`
}

func (q *Queries) RunGetManyJoinedJobs(ctx context.Context, arg RunGetManyJoinedJobsParams) ([]RunGetManyJoinedJobsRow, error) {
	rows, err := q.db.QueryContext(ctx, runGetManyJoinedJobs, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RunGetManyJoinedJobsRow
	for rows.Next() {
		var i RunGetManyJoinedJobsRow
		if err := rows.Scan(
			&i.ID,
			&i.RunKey,
			&i.JobID,
			&i.JobKey,
			&i.Status,
			&i.TriggeredBy,
			&i.ParamsJson,
			&i.QueuedAt,
			&i.StartedAt,
			&i.CompletedAt,
			&i.ParentRunID,
			&i.RerunStepKey,
			&i.ErrorMessage,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const runStepCreate = `-- name: RunStepCreate :one
INSERT INTO run_steps (run_id, job_node_id, step_key, status, attempt, started_at, completed_at, duration_ms, output_json, error_message, log_excerpt)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id, run_id, job_node_id, step_key, status, attempt, started_at, completed_at, duration_ms, output_json, error_message, log_excerpt, created_at, updated_at
`

type RunStepCreateParams struct {
	RunID        int64           `json:"run_id"`
	JobNodeID    int64           `json:"job_node_id"`
	StepKey      string          `json:"step_key"`
	Status       string          `json:"status"`
	Attempt      int64           `json:"attempt"`
	StartedAt    sql.NullTime    `json:"started_at"`
	CompletedAt  sql.NullTime    `json:"completed_at"`
	DurationMs   int64           `json:"duration_ms"`
	OutputJson   json.RawMessage `json:"output_json"`
	ErrorMessage string          `json:"error_message"`
	LogExcerpt   string          `json:"log_excerpt"`
}

func (q *Queries) RunStepCreate(ctx context.Context, arg RunStepCreateParams) (RunStep, error) {
	row := q.db.QueryRowContext(ctx, runStepCreate,
		arg.RunID,
		arg.JobNodeID,
		arg.StepKey,
		arg.Status,
		arg.Attempt,
		arg.StartedAt,
		arg.CompletedAt,
		arg.DurationMs,
		arg.OutputJson,
		arg.ErrorMessage,
		arg.LogExcerpt,
	)
	var i RunStep
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.JobNodeID,
		&i.StepKey,
		&i.Status,
		&i.Attempt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.DurationMs,
		&i.OutputJson,
		&i.ErrorMessage,
		&i.LogExcerpt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const runStepGetByRunIDAndStepKey = `-- name: RunStepGetByRunIDAndStepKey :one
SELECT id, run_id, job_node_id, step_key, status, attempt, started_at, completed_at, duration_ms, output_json, error_message, log_excerpt, created_at, updated_at
FROM run_steps
WHERE run_id = $1 AND step_key = $2
`

type RunStepGetByRunIDAndStepKeyParams struct {
	RunID   int64  `json:"run_id"`
	StepKey string `json:"step_key"`
}

func (q *Queries) RunStepGetByRunIDAndStepKey(ctx context.Context, arg RunStepGetByRunIDAndStepKeyParams) (RunStep, error) {
	row := q.db.QueryRowContext(ctx, runStepGetByRunIDAndStepKey, arg.RunID, arg.StepKey)
	var i RunStep
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.JobNodeID,
		&i.StepKey,
		&i.Status,
		&i.Attempt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.DurationMs,
		&i.OutputJson,
		&i.ErrorMessage,
		&i.LogExcerpt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const runStepGetManyByRunID = `-- name: RunStepGetManyByRunID :many
SELECT id, run_id, job_node_id, step_key, status, attempt, started_at, completed_at, duration_ms, output_json, error_message, log_excerpt, created_at, updated_at
FROM run_steps
WHERE run_id = $1
ORDER BY id
`

func (q *Queries) RunStepGetManyByRunID(ctx context.Context, runID int64) ([]RunStep, error) {
	rows, err := q.db.QueryContext(ctx, runStepGetManyByRunID, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RunStep
	for rows.Next() {
		var i RunStep
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.JobNodeID,
			&i.StepKey,
			&i.Status,
			&i.Attempt,
			&i.StartedAt,
			&i.CompletedAt,
			&i.DurationMs,
			&i.OutputJson,
			&i.ErrorMessage,
			&i.LogExcerpt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const runStepUpdateForComplete = `-- name: RunStepUpdateForComplete :one
UPDATE run_steps
SET status = $1,
    completed_at = $2,
    duration_ms = $3,
    output_json = $4,
    error_message = $5,
    log_excerpt = $6,
    updated_at = now()
WHERE run_id = $7 AND step_key = $8
RETURNING id, run_id, job_node_id, step_key, status, attempt, started_at, completed_at, duration_ms, output_json, error_message, log_excerpt, created_at, updated_at
`

type RunStepUpdateForCompleteParams struct {
	Status       string          `json:"status"`
	CompletedAt  sql.NullTime    `json:"completed_at"`
	DurationMs   int64           `json:"duration_ms"`
	OutputJson   json.RawMessage `json:"output_json"`
	ErrorMessage string          `json:"error_message"`
	LogExcerpt   string          `json:"log_excerpt"`
	RunID        int64           `json:"run_id"`
	StepKey      string          `json:"step_key"`
}

func (q *Queries) RunStepUpdateForComplete(ctx context.Context, arg RunStepUpdateForCompleteParams) (RunStep, error) {
	row := q.db.QueryRowContext(ctx, runStepUpdateForComplete,
		arg.Status,
		arg.CompletedAt,
		arg.DurationMs,
		arg.OutputJson,
		arg.ErrorMessage,
		arg.LogExcerpt,
		arg.RunID,
		arg.StepKey,
	)
	var i RunStep
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.JobNodeID,
		&i.StepKey,
		&i.Status,
		&i.Attempt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.DurationMs,
		&i.OutputJson,
		&i.ErrorMessage,
		&i.LogExcerpt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const runStepUpdateForStart = `-- name: RunStepUpdateForStart :one
UPDATE run_steps
SET status = $1,
    started_at = $2,
    updated_at = now()
WHERE run_id = $3 AND step_key = $4
RETURNING id, run_id, job_node_id, step_key, status, attempt, started_at, completed_at, duration_ms, output_json, error_message, log_excerpt, created_at, updated_at
`

type RunStepUpdateForStartParams struct {
	Status    string       `json:"status"`
	StartedAt sql.NullTime `json:"started_at"`
	RunID     int64        `json:"run_id"`
	StepKey   string       `json:"step_key"`
}

func (q *Queries) RunStepUpdateForStart(ctx context.Context, arg RunStepUpdateForStartParams) (RunStep, error) {
	row := q.db.QueryRowContext(ctx, runStepUpdateForStart,
		arg.Status,
		arg.StartedAt,
		arg.RunID,
		arg.StepKey,
	)
	var i RunStep
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.JobNodeID,
		&i.StepKey,
		&i.Status,
		&i.Attempt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.DurationMs,
		&i.OutputJson,
		&i.ErrorMessage,
		&i.LogExcerpt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const runUpdateForComplete = `-- name: RunUpdateForComplete :one
UPDATE runs
SET status = $1,
    completed_at = $2,
    error_message = $3,
    updated_at = now()
WHERE id = $4
RETURNING id, run_key, job_id, status, triggered_by, params_json, queued_at, started_at, completed_at, parent_run_id, rerun_step_key, error_message, created_at, updated_at
`

type RunUpdateForCompleteParams struct {
	Status       string       `json:"status"`
	CompletedAt  sql.NullTime `json:"completed_at"`
	ErrorMessage string       `json:"error_message"`
	ID           int64        `json:"id"`
}

func (q *Queries) RunUpdateForComplete(ctx context.Context, arg RunUpdateForCompleteParams) (Run, error) {
	row := q.db.QueryRowContext(ctx, runUpdateForComplete,
		arg.Status,
		arg.CompletedAt,
		arg.ErrorMessage,
		arg.ID,
	)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.RunKey,
		&i.JobID,
		&i.Status,
		&i.TriggeredBy,
		&i.ParamsJson,
		&i.QueuedAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.ParentRunID,
		&i.RerunStepKey,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const runUpdateForStart = `-- name: RunUpdateForStart :one
UPDATE runs
SET status = $1,
    started_at = $2,
    updated_at = now()
WHERE id = $3
RETURNING id, run_key, job_id, status, triggered_by, params_json, queued_at, started_at, completed_at, parent_run_id, rerun_step_key, error_message, created_at, updated_at
`

type RunUpdateForStartParams struct {
	Status    string       `json:"status"`
	StartedAt sql.NullTime `json:"started_at"`
	ID        int64        `json:"id"`
}

func (q *Queries) RunUpdateForStart(ctx context.Context, arg RunUpdateForStartParams) (Run, error) {
	row := q.db.QueryRowContext(ctx, runUpdateForStart, arg.Status, arg.StartedAt, arg.ID)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.RunKey,
		&i.JobID,
		&i.Status,
		&i.TriggeredBy,
		&i.ParamsJson,
		&i.QueuedAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.ParentRunID,
		&i.RerunStepKey,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
