// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: 003_scheduler.sql

package postgresgen

import (
	"context"
	"database/sql"
	"time"
)

const schedulerHeartbeatUpsert = `-- name: SchedulerHeartbeatUpsert :one
INSERT INTO scheduler_heartbeats (
    scheduler_key,
    last_heartbeat_at,
    last_tick_started_at,
    last_tick_completed_at,
    last_error
)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT(scheduler_key)
DO UPDATE SET
    last_heartbeat_at = excluded.last_heartbeat_at,
    last_tick_started_at = excluded.last_tick_started_at,
    last_tick_completed_at = excluded.last_tick_completed_at,
    last_error = excluded.last_error,
    updated_at = now()
RETURNING scheduler_key, last_heartbeat_at, last_tick_started_at, last_tick_completed_at, last_error, updated_at
`

type SchedulerHeartbeatUpsertParams struct {
	SchedulerKey        string       `json:"scheduler_key"`
	LastHeartbeatAt     time.Time    `json:"last_heartbeat_at"`
	LastTickStartedAt   sql.NullTime `json:"last_tick_started_at"`
	LastTickCompletedAt sql.NullTime `json:"last_tick_completed_at"`
	LastError           string       `json:"last_error"`
}

func (q *Queries) SchedulerHeartbeatUpsert(ctx context.Context, arg SchedulerHeartbeatUpsertParams) (SchedulerHeartbeat, error) {
	row := q.db.QueryRowContext(ctx, schedulerHeartbeatUpsert,
		arg.SchedulerKey,
		arg.LastHeartbeatAt,
		arg.LastTickStartedAt,
		arg.LastTickCompletedAt,
		arg.LastError,
	)
	var i SchedulerHeartbeat
	err := row.Scan(
		&i.SchedulerKey,
		&i.LastHeartbeatAt,
		&i.LastTickStartedAt,
		&i.LastTickCompletedAt,
		&i.LastError,
		&i.UpdatedAt,
	)
	return i, err
}

const schedulerScheduleGetEnabledMany = `-- name: SchedulerScheduleGetEnabledMany :many
SELECT js.id,
       js.job_id,
       j.job_key,
       js.schedule_key,
       js.cron_expr,
       js.timezone,
       js.description
FROM job_schedules js
JOIN jobs j ON j.id = js.job_id
WHERE js.is_enabled = true
ORDER BY j.job_key, js.schedule_key, js.id
`

type SchedulerScheduleGetEnabledManyRow struct {
	ID          int64  `json:"id"`
	JobID       int64  `json:"job_id"`
	JobKey      string `json:"job_key"`
	ScheduleKey string `json:"schedule_key"`
	CronExpr    string `json:"cron_expr"`
	Timezone    string `json:"timezone"`
	Description string `json:"description"`
}

func (q *Queries) SchedulerScheduleGetEnabledMany(ctx context.Context) ([]SchedulerScheduleGetEnabledManyRow, error) {
	rows, err := q.db.QueryContext(ctx, schedulerScheduleGetEnabledMany)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SchedulerScheduleGetEnabledManyRow
	for rows.Next() {
		var i SchedulerScheduleGetEnabledManyRow
		if err := rows.Scan(
			&i.ID,
			&i.JobID,
			&i.JobKey,
			&i.ScheduleKey,
			&i.CronExpr,
			&i.Timezone,
			&i.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const schedulerScheduleRunDeleteByID = `-- name: SchedulerScheduleRunDeleteByID :exec
DELETE FROM scheduler_schedule_runs
WHERE id = $1
`

func (q *Queries) SchedulerScheduleRunDeleteByID(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, schedulerScheduleRunDeleteByID, id)
	return err
}

const schedulerScheduleRunUpdateByID = `-- name: SchedulerScheduleRunUpdateByID :one
UPDATE scheduler_schedule_runs
SET run_key = $1,
    triggered_by = $2,
    updated_at = now()
WHERE id = $3
RETURNING id, job_schedule_id, scheduled_for, run_key, triggered_by, created_at, updated_at
`

type SchedulerScheduleRunUpdateByIDParams struct {
	RunKey      string `json:"run_key"`
	TriggeredBy string `json:"triggered_by"`
	ID          int64  `json:"id"`
}

func (q *Queries) SchedulerScheduleRunUpdateByID(ctx context.Context, arg SchedulerScheduleRunUpdateByIDParams) (SchedulerScheduleRun, error) {
	row := q.db.QueryRowContext(ctx, schedulerScheduleRunUpdateByID, arg.RunKey, arg.TriggeredBy, arg.ID)
	var i SchedulerScheduleRun
	err := row.Scan(
		&i.ID,
		&i.JobScheduleID,
		&i.ScheduledFor,
		&i.RunKey,
		&i.TriggeredBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const schedulerScheduleRunsCreateIfAbsent = `-- name: SchedulerScheduleRunsCreateIfAbsent :many
INSERT INTO scheduler_schedule_runs (
    job_schedule_id,
    scheduled_for,
    run_key,
    triggered_by
)
VALUES ($1, $2, $3, $4)
ON CONFLICT(job_schedule_id, scheduled_for)
DO NOTHING
RETURNING id, job_schedule_id, scheduled_for, run_key, triggered_by, created_at, updated_at
`

type SchedulerScheduleRunsCreateIfAbsentParams struct {
	JobScheduleID int64     `json:"job_schedule_id"`
	ScheduledFor  time.Time `json:"scheduled_for"`
	RunKey        string    `json:"run_key"`
	TriggeredBy   string    `json:"triggered_by"`
}

func (q *Queries) SchedulerScheduleRunsCreateIfAbsent(ctx context.Context, arg SchedulerScheduleRunsCreateIfAbsentParams) ([]SchedulerScheduleRun, error) {
	rows, err := q.db.QueryContext(ctx, schedulerScheduleRunsCreateIfAbsent,
		arg.JobScheduleID,
		arg.ScheduledFor,
		arg.RunKey,
		arg.TriggeredBy,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SchedulerScheduleRun
	for rows.Next() {
		var i SchedulerScheduleRun
		if err := rows.Scan(
			&i.ID,
			&i.JobScheduleID,
			&i.ScheduledFor,
			&i.RunKey,
			&i.TriggeredBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const schedulerScheduleStateGetByJobScheduleID = `-- name: SchedulerScheduleStateGetByJobScheduleID :one
SELECT job_schedule_id, last_checked_at, last_enqueued_at, next_run_at, updated_at
FROM scheduler_schedule_state
WHERE job_schedule_id = $1
`

func (q *Queries) SchedulerScheduleStateGetByJobScheduleID(ctx context.Context, jobScheduleID int64) (SchedulerScheduleState, error) {
	row := q.db.QueryRowContext(ctx, schedulerScheduleStateGetByJobScheduleID, jobScheduleID)
	var i SchedulerScheduleState
	err := row.Scan(
		&i.JobScheduleID,
		&i.LastCheckedAt,
		&i.LastEnqueuedAt,
		&i.NextRunAt,
		&i.UpdatedAt,
	)
	return i, err
}

const schedulerScheduleStateUpsert = `-- name: SchedulerScheduleStateUpsert :one
INSERT INTO scheduler_schedule_state (
    job_schedule_id,
    last_checked_at,
    last_enqueued_at,
    next_run_at
)
VALUES ($1, $2, $3, $4)
ON CONFLICT(job_schedule_id)
DO UPDATE SET
    last_checked_at = excluded.last_checked_at,
    last_enqueued_at = excluded.last_enqueued_at,
    next_run_at = excluded.next_run_at,
    updated_at = now()
RETURNING job_schedule_id, last_checked_at, last_enqueued_at, next_run_at, updated_at
`

type SchedulerScheduleStateUpsertParams struct {
	JobScheduleID  int64        `json:"job_schedule_id"`
	LastCheckedAt  sql.NullTime `json:"last_checked_at"`
	LastEnqueuedAt sql.NullTime `json:"last_enqueued_at"`
	NextRunAt      sql.NullTime `json:"next_run_at"`
}

func (q *Queries) SchedulerScheduleStateUpsert(ctx context.Context, arg SchedulerScheduleStateUpsertParams) (SchedulerScheduleState, error) {
	row := q.db.QueryRowContext(ctx, schedulerScheduleStateUpsert,
		arg.JobScheduleID,
		arg.LastCheckedAt,
		arg.LastEnqueuedAt,
		arg.NextRunAt,
	)
	var i SchedulerScheduleState
	err := row.Scan(
		&i.JobScheduleID,
		&i.LastCheckedAt,
		&i.LastEnqueuedAt,
		&i.NextRunAt,
		&i.UpdatedAt,
	)
	return i, err
}
