// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: 003_scheduler.sql

package postgresgen

import (
	"context"
	"database/sql"
	"time"
)

const schedulerHeartbeatUpsert = `-- name: SchedulerHeartbeatUpsert :one
INSERT INTO scheduler_heartbeats (
    scheduler_key,
    last_heartbeat_at,
    last_tick_started_at,
    last_tick_completed_at,
    last_error
)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT(scheduler_key)
DO UPDATE SET
    last_heartbeat_at = excluded.last_heartbeat_at,
    last_tick_started_at = excluded.last_tick_started_at,
    last_tick_completed_at = excluded.last_tick_completed_at,
    last_error = excluded.last_error,
    updated_at = now()
RETURNING scheduler_key, last_heartbeat_at, last_tick_started_at, last_tick_completed_at, last_error, updated_at
`

type SchedulerHeartbeatUpsertParams struct {
	SchedulerKey        string       `json:"scheduler_key"`
	LastHeartbeatAt     time.Time    `json:"last_heartbeat_at"`
	LastTickStartedAt   sql.NullTime `json:"last_tick_started_at"`
	LastTickCompletedAt sql.NullTime `json:"last_tick_completed_at"`
	LastError           string       `json:"last_error"`
}

func (q *Queries) SchedulerHeartbeatUpsert(ctx context.Context, arg SchedulerHeartbeatUpsertParams) (SchedulerHeartbeat, error) {
	row := q.db.QueryRowContext(ctx, schedulerHeartbeatUpsert,
		arg.SchedulerKey,
		arg.LastHeartbeatAt,
		arg.LastTickStartedAt,
		arg.LastTickCompletedAt,
		arg.LastError,
	)
	var i SchedulerHeartbeat
	err := row.Scan(
		&i.SchedulerKey,
		&i.LastHeartbeatAt,
		&i.LastTickStartedAt,
		&i.LastTickCompletedAt,
		&i.LastError,
		&i.UpdatedAt,
	)
	return i, err
}

const schedulerScheduleRunDeleteByID = `-- name: SchedulerScheduleRunDeleteByID :exec
DELETE FROM scheduler_schedule_runs
WHERE id = $1
`

func (q *Queries) SchedulerScheduleRunDeleteByID(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, schedulerScheduleRunDeleteByID, id)
	return err
}

const schedulerScheduleRunGetDistinctMany = `-- name: SchedulerScheduleRunGetDistinctMany :many
SELECT DISTINCT job_key, schedule_key
FROM scheduler_schedule_runs
ORDER BY job_key, schedule_key
`

type SchedulerScheduleRunGetDistinctManyRow struct {
	JobKey      string `json:"job_key"`
	ScheduleKey string `json:"schedule_key"`
}

func (q *Queries) SchedulerScheduleRunGetDistinctMany(ctx context.Context) ([]SchedulerScheduleRunGetDistinctManyRow, error) {
	rows, err := q.db.QueryContext(ctx, schedulerScheduleRunGetDistinctMany)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SchedulerScheduleRunGetDistinctManyRow
	for rows.Next() {
		var i SchedulerScheduleRunGetDistinctManyRow
		if err := rows.Scan(&i.JobKey, &i.ScheduleKey); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const schedulerScheduleRunUpdateByID = `-- name: SchedulerScheduleRunUpdateByID :one
UPDATE scheduler_schedule_runs
SET run_key = $1,
    triggered_by = $2,
    updated_at = now()
WHERE id = $3
RETURNING id, job_key, schedule_key, scheduled_for, run_key, triggered_by, created_at, updated_at
`

type SchedulerScheduleRunUpdateByIDParams struct {
	RunKey      string `json:"run_key"`
	TriggeredBy string `json:"triggered_by"`
	ID          int64  `json:"id"`
}

func (q *Queries) SchedulerScheduleRunUpdateByID(ctx context.Context, arg SchedulerScheduleRunUpdateByIDParams) (SchedulerScheduleRun, error) {
	row := q.db.QueryRowContext(ctx, schedulerScheduleRunUpdateByID, arg.RunKey, arg.TriggeredBy, arg.ID)
	var i SchedulerScheduleRun
	err := row.Scan(
		&i.ID,
		&i.JobKey,
		&i.ScheduleKey,
		&i.ScheduledFor,
		&i.RunKey,
		&i.TriggeredBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const schedulerScheduleRunsCreateIfAbsent = `-- name: SchedulerScheduleRunsCreateIfAbsent :many
INSERT INTO scheduler_schedule_runs (
    job_key,
    schedule_key,
    scheduled_for,
    run_key,
    triggered_by
)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT(job_key, schedule_key, scheduled_for)
DO NOTHING
RETURNING id, job_key, schedule_key, scheduled_for, run_key, triggered_by, created_at, updated_at
`

type SchedulerScheduleRunsCreateIfAbsentParams struct {
	JobKey       string    `json:"job_key"`
	ScheduleKey  string    `json:"schedule_key"`
	ScheduledFor time.Time `json:"scheduled_for"`
	RunKey       string    `json:"run_key"`
	TriggeredBy  string    `json:"triggered_by"`
}

func (q *Queries) SchedulerScheduleRunsCreateIfAbsent(ctx context.Context, arg SchedulerScheduleRunsCreateIfAbsentParams) ([]SchedulerScheduleRun, error) {
	rows, err := q.db.QueryContext(ctx, schedulerScheduleRunsCreateIfAbsent,
		arg.JobKey,
		arg.ScheduleKey,
		arg.ScheduledFor,
		arg.RunKey,
		arg.TriggeredBy,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SchedulerScheduleRun
	for rows.Next() {
		var i SchedulerScheduleRun
		if err := rows.Scan(
			&i.ID,
			&i.JobKey,
			&i.ScheduleKey,
			&i.ScheduledFor,
			&i.RunKey,
			&i.TriggeredBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const schedulerScheduleRunsDeleteByJobKeyScheduleKey = `-- name: SchedulerScheduleRunsDeleteByJobKeyScheduleKey :exec
DELETE FROM scheduler_schedule_runs
WHERE job_key = $1
  AND schedule_key = $2
`

type SchedulerScheduleRunsDeleteByJobKeyScheduleKeyParams struct {
	JobKey      string `json:"job_key"`
	ScheduleKey string `json:"schedule_key"`
}

func (q *Queries) SchedulerScheduleRunsDeleteByJobKeyScheduleKey(ctx context.Context, arg SchedulerScheduleRunsDeleteByJobKeyScheduleKeyParams) error {
	_, err := q.db.ExecContext(ctx, schedulerScheduleRunsDeleteByJobKeyScheduleKey, arg.JobKey, arg.ScheduleKey)
	return err
}

const schedulerScheduleStateDeleteByJobKeyScheduleKey = `-- name: SchedulerScheduleStateDeleteByJobKeyScheduleKey :exec
DELETE FROM scheduler_schedule_state
WHERE job_key = $1
  AND schedule_key = $2
`

type SchedulerScheduleStateDeleteByJobKeyScheduleKeyParams struct {
	JobKey      string `json:"job_key"`
	ScheduleKey string `json:"schedule_key"`
}

func (q *Queries) SchedulerScheduleStateDeleteByJobKeyScheduleKey(ctx context.Context, arg SchedulerScheduleStateDeleteByJobKeyScheduleKeyParams) error {
	_, err := q.db.ExecContext(ctx, schedulerScheduleStateDeleteByJobKeyScheduleKey, arg.JobKey, arg.ScheduleKey)
	return err
}

const schedulerScheduleStateGetByJobKeyScheduleKey = `-- name: SchedulerScheduleStateGetByJobKeyScheduleKey :one
SELECT job_key, schedule_key, last_checked_at, last_enqueued_at, next_run_at, updated_at
FROM scheduler_schedule_state
WHERE job_key = $1
  AND schedule_key = $2
`

type SchedulerScheduleStateGetByJobKeyScheduleKeyParams struct {
	JobKey      string `json:"job_key"`
	ScheduleKey string `json:"schedule_key"`
}

func (q *Queries) SchedulerScheduleStateGetByJobKeyScheduleKey(ctx context.Context, arg SchedulerScheduleStateGetByJobKeyScheduleKeyParams) (SchedulerScheduleState, error) {
	row := q.db.QueryRowContext(ctx, schedulerScheduleStateGetByJobKeyScheduleKey, arg.JobKey, arg.ScheduleKey)
	var i SchedulerScheduleState
	err := row.Scan(
		&i.JobKey,
		&i.ScheduleKey,
		&i.LastCheckedAt,
		&i.LastEnqueuedAt,
		&i.NextRunAt,
		&i.UpdatedAt,
	)
	return i, err
}

const schedulerScheduleStateGetMany = `-- name: SchedulerScheduleStateGetMany :many
SELECT job_key, schedule_key, last_checked_at, last_enqueued_at, next_run_at, updated_at
FROM scheduler_schedule_state
ORDER BY job_key, schedule_key
`

func (q *Queries) SchedulerScheduleStateGetMany(ctx context.Context) ([]SchedulerScheduleState, error) {
	rows, err := q.db.QueryContext(ctx, schedulerScheduleStateGetMany)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SchedulerScheduleState
	for rows.Next() {
		var i SchedulerScheduleState
		if err := rows.Scan(
			&i.JobKey,
			&i.ScheduleKey,
			&i.LastCheckedAt,
			&i.LastEnqueuedAt,
			&i.NextRunAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const schedulerScheduleStateUpsert = `-- name: SchedulerScheduleStateUpsert :one
INSERT INTO scheduler_schedule_state (
    job_key,
    schedule_key,
    last_checked_at,
    last_enqueued_at,
    next_run_at
)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT(job_key, schedule_key)
DO UPDATE SET
    last_checked_at = excluded.last_checked_at,
    last_enqueued_at = excluded.last_enqueued_at,
    next_run_at = excluded.next_run_at,
    updated_at = now()
RETURNING job_key, schedule_key, last_checked_at, last_enqueued_at, next_run_at, updated_at
`

type SchedulerScheduleStateUpsertParams struct {
	JobKey         string       `json:"job_key"`
	ScheduleKey    string       `json:"schedule_key"`
	LastCheckedAt  sql.NullTime `json:"last_checked_at"`
	LastEnqueuedAt sql.NullTime `json:"last_enqueued_at"`
	NextRunAt      sql.NullTime `json:"next_run_at"`
}

func (q *Queries) SchedulerScheduleStateUpsert(ctx context.Context, arg SchedulerScheduleStateUpsertParams) (SchedulerScheduleState, error) {
	row := q.db.QueryRowContext(ctx, schedulerScheduleStateUpsert,
		arg.JobKey,
		arg.ScheduleKey,
		arg.LastCheckedAt,
		arg.LastEnqueuedAt,
		arg.NextRunAt,
	)
	var i SchedulerScheduleState
	err := row.Scan(
		&i.JobKey,
		&i.ScheduleKey,
		&i.LastCheckedAt,
		&i.LastEnqueuedAt,
		&i.NextRunAt,
		&i.UpdatedAt,
	)
	return i, err
}
