// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: 004_queues.sql

package postgresgen

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"
)

const queueCount = `-- name: QueueCount :one
SELECT COUNT(*) FROM queues
`

func (q *Queries) QueueCount(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, queueCount)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const queueGetByKey = `-- name: QueueGetByKey :one
SELECT id, queue_key, display_name, description, route_path, load_mode, load_poll_every_seconds, created_at, updated_at
FROM queues
WHERE queue_key = $1
`

func (q *Queries) QueueGetByKey(ctx context.Context, queueKey string) (Queue, error) {
	row := q.db.QueryRowContext(ctx, queueGetByKey, queueKey)
	var i Queue
	err := row.Scan(
		&i.ID,
		&i.QueueKey,
		&i.DisplayName,
		&i.Description,
		&i.RoutePath,
		&i.LoadMode,
		&i.LoadPollEverySeconds,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const queueGetMany = `-- name: QueueGetMany :many
SELECT id, queue_key, display_name, description, route_path, load_mode, load_poll_every_seconds, created_at, updated_at
FROM queues
ORDER BY queue_key
LIMIT $1 OFFSET $2
`

type QueueGetManyParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) QueueGetMany(ctx context.Context, arg QueueGetManyParams) ([]Queue, error) {
	rows, err := q.db.QueryContext(ctx, queueGetMany, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Queue
	for rows.Next() {
		var i Queue
		if err := rows.Scan(
			&i.ID,
			&i.QueueKey,
			&i.DisplayName,
			&i.Description,
			&i.RoutePath,
			&i.LoadMode,
			&i.LoadPollEverySeconds,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const queueItemCountByQueueID = `-- name: QueueItemCountByQueueID :one
SELECT COUNT(*)
FROM queue_items
WHERE queue_id = $1
`

func (q *Queries) QueueItemCountByQueueID(ctx context.Context, queueID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, queueItemCountByQueueID, queueID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const queueItemCreate = `-- name: QueueItemCreate :one
INSERT INTO queue_items (queue_id, queue_item_key, partition_key, status, external_key, payload_json, error_message, queued_at, started_at, completed_at)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10
)
RETURNING id, queue_id, queue_item_key, partition_key, status, external_key, payload_json, error_message, queued_at, started_at, completed_at, created_at, updated_at
`

type QueueItemCreateParams struct {
	QueueID      int64           `json:"queue_id"`
	QueueItemKey string          `json:"queue_item_key"`
	PartitionKey string          `json:"partition_key"`
	Status       string          `json:"status"`
	ExternalKey  string          `json:"external_key"`
	PayloadJson  json.RawMessage `json:"payload_json"`
	ErrorMessage string          `json:"error_message"`
	QueuedAt     time.Time       `json:"queued_at"`
	StartedAt    sql.NullTime    `json:"started_at"`
	CompletedAt  sql.NullTime    `json:"completed_at"`
}

func (q *Queries) QueueItemCreate(ctx context.Context, arg QueueItemCreateParams) (QueueItem, error) {
	row := q.db.QueryRowContext(ctx, queueItemCreate,
		arg.QueueID,
		arg.QueueItemKey,
		arg.PartitionKey,
		arg.Status,
		arg.ExternalKey,
		arg.PayloadJson,
		arg.ErrorMessage,
		arg.QueuedAt,
		arg.StartedAt,
		arg.CompletedAt,
	)
	var i QueueItem
	err := row.Scan(
		&i.ID,
		&i.QueueID,
		&i.QueueItemKey,
		&i.PartitionKey,
		&i.Status,
		&i.ExternalKey,
		&i.PayloadJson,
		&i.ErrorMessage,
		&i.QueuedAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const queueItemDeleteByID = `-- name: QueueItemDeleteByID :exec
DELETE FROM queue_items
WHERE id = $1
`

func (q *Queries) QueueItemDeleteByID(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, queueItemDeleteByID, id)
	return err
}

const queueItemGetByIDJoinedQueues = `-- name: QueueItemGetByIDJoinedQueues :one
SELECT qi.id,
       qi.queue_id,
       qi.queue_item_key,
       qi.partition_key,
       qi.status,
       qi.external_key,
       qi.payload_json,
       qi.error_message,
       qi.queued_at,
       qi.started_at,
       qi.completed_at,
       qi.created_at,
       qi.updated_at,
       q.queue_key,
       q.display_name AS queue_display_name
FROM queue_items qi
JOIN queues q ON q.id = qi.queue_id
WHERE qi.id = $1
`

type QueueItemGetByIDJoinedQueuesRow struct {
	ID               int64           `json:"id"`
	QueueID          int64           `json:"queue_id"`
	QueueItemKey     string          `json:"queue_item_key"`
	PartitionKey     string          `json:"partition_key"`
	Status           string          `json:"status"`
	ExternalKey      string          `json:"external_key"`
	PayloadJson      json.RawMessage `json:"payload_json"`
	ErrorMessage     string          `json:"error_message"`
	QueuedAt         time.Time       `json:"queued_at"`
	StartedAt        sql.NullTime    `json:"started_at"`
	CompletedAt      sql.NullTime    `json:"completed_at"`
	CreatedAt        time.Time       `json:"created_at"`
	UpdatedAt        time.Time       `json:"updated_at"`
	QueueKey         string          `json:"queue_key"`
	QueueDisplayName string          `json:"queue_display_name"`
}

func (q *Queries) QueueItemGetByIDJoinedQueues(ctx context.Context, id int64) (QueueItemGetByIDJoinedQueuesRow, error) {
	row := q.db.QueryRowContext(ctx, queueItemGetByIDJoinedQueues, id)
	var i QueueItemGetByIDJoinedQueuesRow
	err := row.Scan(
		&i.ID,
		&i.QueueID,
		&i.QueueItemKey,
		&i.PartitionKey,
		&i.Status,
		&i.ExternalKey,
		&i.PayloadJson,
		&i.ErrorMessage,
		&i.QueuedAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.QueueKey,
		&i.QueueDisplayName,
	)
	return i, err
}

const queueItemGetManyByQueueID = `-- name: QueueItemGetManyByQueueID :many
SELECT id, queue_id, queue_item_key, partition_key, status, external_key, payload_json, error_message, queued_at, started_at, completed_at, created_at, updated_at
FROM queue_items
WHERE queue_id = $1
ORDER BY created_at DESC, id DESC
LIMIT $2 OFFSET $3
`

type QueueItemGetManyByQueueIDParams struct {
	QueueID int64 `json:"queue_id"`
	Limit   int32 `json:"limit"`
	Offset  int32 `json:"offset"`
}

func (q *Queries) QueueItemGetManyByQueueID(ctx context.Context, arg QueueItemGetManyByQueueIDParams) ([]QueueItem, error) {
	rows, err := q.db.QueryContext(ctx, queueItemGetManyByQueueID, arg.QueueID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []QueueItem
	for rows.Next() {
		var i QueueItem
		if err := rows.Scan(
			&i.ID,
			&i.QueueID,
			&i.QueueItemKey,
			&i.PartitionKey,
			&i.Status,
			&i.ExternalKey,
			&i.PayloadJson,
			&i.ErrorMessage,
			&i.QueuedAt,
			&i.StartedAt,
			&i.CompletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const queueItemGetManyForRetentionPurge = `-- name: QueueItemGetManyForRetentionPurge :many
SELECT qi.id
FROM queue_items qi
WHERE qi.completed_at IS NOT NULL
  AND qi.completed_at < $1
  AND NOT EXISTS (
    SELECT 1
    FROM queue_item_runs qir
    WHERE qir.queue_item_id = qi.id
  )
ORDER BY qi.completed_at, qi.id
LIMIT $2
`

type QueueItemGetManyForRetentionPurgeParams struct {
	CompletedAt sql.NullTime `json:"completed_at"`
	Limit       int32        `json:"limit"`
}

func (q *Queries) QueueItemGetManyForRetentionPurge(ctx context.Context, arg QueueItemGetManyForRetentionPurgeParams) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, queueItemGetManyForRetentionPurge, arg.CompletedAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const queueItemRunCreate = `-- name: QueueItemRunCreate :one
INSERT INTO queue_item_runs (queue_item_id, job_id, run_id)
VALUES ($1, $2, $3)
RETURNING id, queue_item_id, job_id, run_id, created_at
`

type QueueItemRunCreateParams struct {
	QueueItemID int64 `json:"queue_item_id"`
	JobID       int64 `json:"job_id"`
	RunID       int64 `json:"run_id"`
}

func (q *Queries) QueueItemRunCreate(ctx context.Context, arg QueueItemRunCreateParams) (QueueItemRun, error) {
	row := q.db.QueryRowContext(ctx, queueItemRunCreate, arg.QueueItemID, arg.JobID, arg.RunID)
	var i QueueItemRun
	err := row.Scan(
		&i.ID,
		&i.QueueItemID,
		&i.JobID,
		&i.RunID,
		&i.CreatedAt,
	)
	return i, err
}

const queueItemRunGetByRunID = `-- name: QueueItemRunGetByRunID :one
SELECT id, queue_item_id, job_id, run_id, created_at
FROM queue_item_runs
WHERE run_id = $1
`

func (q *Queries) QueueItemRunGetByRunID(ctx context.Context, runID int64) (QueueItemRun, error) {
	row := q.db.QueryRowContext(ctx, queueItemRunGetByRunID, runID)
	var i QueueItemRun
	err := row.Scan(
		&i.ID,
		&i.QueueItemID,
		&i.JobID,
		&i.RunID,
		&i.CreatedAt,
	)
	return i, err
}

const queueItemRunGetManyByQueueItemIDJoinedRuns = `-- name: QueueItemRunGetManyByQueueItemIDJoinedRuns :many
SELECT qir.id,
       qir.queue_item_id,
       qir.job_id,
       qir.run_id,
       qir.created_at,
       r.run_key,
       r.status AS run_status,
       r.triggered_by,
       r.queued_at,
       r.started_at,
       r.completed_at,
       r.parent_run_id,
       r.rerun_step_key,
       r.error_message AS run_error_message,
       j.job_key,
       j.display_name AS job_display_name
FROM queue_item_runs qir
JOIN runs r ON r.id = qir.run_id
JOIN jobs j ON j.id = qir.job_id
WHERE qir.queue_item_id = $1
ORDER BY qir.created_at, qir.id
`

type QueueItemRunGetManyByQueueItemIDJoinedRunsRow struct {
	ID              int64        `json:"id"`
	QueueItemID     int64        `json:"queue_item_id"`
	JobID           int64        `json:"job_id"`
	RunID           int64        `json:"run_id"`
	CreatedAt       time.Time    `json:"created_at"`
	RunKey          string       `json:"run_key"`
	RunStatus       string       `json:"run_status"`
	TriggeredBy     string       `json:"triggered_by"`
	QueuedAt        time.Time    `json:"queued_at"`
	StartedAt       sql.NullTime `json:"started_at"`
	CompletedAt     sql.NullTime `json:"completed_at"`
	ParentRunID     int64        `json:"parent_run_id"`
	RerunStepKey    string       `json:"rerun_step_key"`
	RunErrorMessage string       `json:"run_error_message"`
	JobKey          string       `json:"job_key"`
	JobDisplayName  string       `json:"job_display_name"`
}

func (q *Queries) QueueItemRunGetManyByQueueItemIDJoinedRuns(ctx context.Context, queueItemID int64) ([]QueueItemRunGetManyByQueueItemIDJoinedRunsRow, error) {
	rows, err := q.db.QueryContext(ctx, queueItemRunGetManyByQueueItemIDJoinedRuns, queueItemID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []QueueItemRunGetManyByQueueItemIDJoinedRunsRow
	for rows.Next() {
		var i QueueItemRunGetManyByQueueItemIDJoinedRunsRow
		if err := rows.Scan(
			&i.ID,
			&i.QueueItemID,
			&i.JobID,
			&i.RunID,
			&i.CreatedAt,
			&i.RunKey,
			&i.RunStatus,
			&i.TriggeredBy,
			&i.QueuedAt,
			&i.StartedAt,
			&i.CompletedAt,
			&i.ParentRunID,
			&i.RerunStepKey,
			&i.RunErrorMessage,
			&i.JobKey,
			&i.JobDisplayName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const queueItemStatusCountGetManyByQueueID = `-- name: QueueItemStatusCountGetManyByQueueID :many
SELECT status, COUNT(*) AS total
FROM queue_items
WHERE queue_id = $1
GROUP BY status
ORDER BY status
`

type QueueItemStatusCountGetManyByQueueIDRow struct {
	Status string `json:"status"`
	Total  int64  `json:"total"`
}

func (q *Queries) QueueItemStatusCountGetManyByQueueID(ctx context.Context, queueID int64) ([]QueueItemStatusCountGetManyByQueueIDRow, error) {
	rows, err := q.db.QueryContext(ctx, queueItemStatusCountGetManyByQueueID, queueID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []QueueItemStatusCountGetManyByQueueIDRow
	for rows.Next() {
		var i QueueItemStatusCountGetManyByQueueIDRow
		if err := rows.Scan(&i.Status, &i.Total); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const queueItemStepMetadataGetManyByQueueItemID = `-- name: QueueItemStepMetadataGetManyByQueueItemID :many
SELECT id, queue_item_id, job_id, run_id, step_key, metadata_json, created_at, updated_at
FROM queue_item_step_metadata
WHERE queue_item_id = $1
ORDER BY job_id, step_key, id
`

func (q *Queries) QueueItemStepMetadataGetManyByQueueItemID(ctx context.Context, queueItemID int64) ([]QueueItemStepMetadatum, error) {
	rows, err := q.db.QueryContext(ctx, queueItemStepMetadataGetManyByQueueItemID, queueItemID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []QueueItemStepMetadatum
	for rows.Next() {
		var i QueueItemStepMetadatum
		if err := rows.Scan(
			&i.ID,
			&i.QueueItemID,
			&i.JobID,
			&i.RunID,
			&i.StepKey,
			&i.MetadataJson,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const queueItemStepMetadataUpsert = `-- name: QueueItemStepMetadataUpsert :one
INSERT INTO queue_item_step_metadata (queue_item_id, job_id, run_id, step_key, metadata_json)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (queue_item_id, job_id, step_key) DO UPDATE SET
    run_id = excluded.run_id,
    metadata_json = excluded.metadata_json,
    updated_at = now()
RETURNING id, queue_item_id, job_id, run_id, step_key, metadata_json, created_at, updated_at
`

type QueueItemStepMetadataUpsertParams struct {
	QueueItemID  int64           `json:"queue_item_id"`
	JobID        int64           `json:"job_id"`
	RunID        int64           `json:"run_id"`
	StepKey      string          `json:"step_key"`
	MetadataJson json.RawMessage `json:"metadata_json"`
}

func (q *Queries) QueueItemStepMetadataUpsert(ctx context.Context, arg QueueItemStepMetadataUpsertParams) (QueueItemStepMetadatum, error) {
	row := q.db.QueryRowContext(ctx, queueItemStepMetadataUpsert,
		arg.QueueItemID,
		arg.JobID,
		arg.RunID,
		arg.StepKey,
		arg.MetadataJson,
	)
	var i QueueItemStepMetadatum
	err := row.Scan(
		&i.ID,
		&i.QueueItemID,
		&i.JobID,
		&i.RunID,
		&i.StepKey,
		&i.MetadataJson,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const queueItemUpdateLifecycleByID = `-- name: QueueItemUpdateLifecycleByID :one
UPDATE queue_items
SET status = $1,
    started_at = $2,
    completed_at = $3,
    error_message = $4,
    updated_at = now()
WHERE id = $5
RETURNING id, queue_id, queue_item_key, partition_key, status, external_key, payload_json, error_message, queued_at, started_at, completed_at, created_at, updated_at
`

type QueueItemUpdateLifecycleByIDParams struct {
	Status       string       `json:"status"`
	StartedAt    sql.NullTime `json:"started_at"`
	CompletedAt  sql.NullTime `json:"completed_at"`
	ErrorMessage string       `json:"error_message"`
	ID           int64        `json:"id"`
}

func (q *Queries) QueueItemUpdateLifecycleByID(ctx context.Context, arg QueueItemUpdateLifecycleByIDParams) (QueueItem, error) {
	row := q.db.QueryRowContext(ctx, queueItemUpdateLifecycleByID,
		arg.Status,
		arg.StartedAt,
		arg.CompletedAt,
		arg.ErrorMessage,
		arg.ID,
	)
	var i QueueItem
	err := row.Scan(
		&i.ID,
		&i.QueueID,
		&i.QueueItemKey,
		&i.PartitionKey,
		&i.Status,
		&i.ExternalKey,
		&i.PayloadJson,
		&i.ErrorMessage,
		&i.QueuedAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const queueJobCreate = `-- name: QueueJobCreate :one
INSERT INTO queue_jobs (queue_id, job_id, sort_index)
VALUES ($1, $2, $3)
RETURNING id, queue_id, job_id, sort_index, created_at
`

type QueueJobCreateParams struct {
	QueueID   int64 `json:"queue_id"`
	JobID     int64 `json:"job_id"`
	SortIndex int64 `json:"sort_index"`
}

func (q *Queries) QueueJobCreate(ctx context.Context, arg QueueJobCreateParams) (QueueJob, error) {
	row := q.db.QueryRowContext(ctx, queueJobCreate, arg.QueueID, arg.JobID, arg.SortIndex)
	var i QueueJob
	err := row.Scan(
		&i.ID,
		&i.QueueID,
		&i.JobID,
		&i.SortIndex,
		&i.CreatedAt,
	)
	return i, err
}

const queueJobDeleteByQueueID = `-- name: QueueJobDeleteByQueueID :exec
DELETE FROM queue_jobs
WHERE queue_id = $1
`

func (q *Queries) QueueJobDeleteByQueueID(ctx context.Context, queueID int64) error {
	_, err := q.db.ExecContext(ctx, queueJobDeleteByQueueID, queueID)
	return err
}

const queuePartitionCountByQueueID = `-- name: QueuePartitionCountByQueueID :one
SELECT COUNT(*)
FROM (
    SELECT DISTINCT partition_key
    FROM queue_items
    WHERE queue_id = $1
) AS queue_partitions
`

func (q *Queries) QueuePartitionCountByQueueID(ctx context.Context, queueID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, queuePartitionCountByQueueID, queueID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const queuePartitionGetManyByQueueID = `-- name: QueuePartitionGetManyByQueueID :many
WITH ranked AS (
    SELECT id,
           queue_id,
           queue_item_key,
           partition_key,
           status,
           external_key,
           payload_json,
           error_message,
           queued_at,
           started_at,
           completed_at,
           created_at,
           updated_at,
           ROW_NUMBER() OVER (
               PARTITION BY partition_key
               ORDER BY created_at DESC, id DESC
           ) AS rn
    FROM queue_items
    WHERE queue_id = $1
)
SELECT id, queue_id, queue_item_key, partition_key, status, external_key, payload_json, error_message, queued_at, started_at, completed_at, created_at, updated_at
FROM ranked
WHERE rn = 1
ORDER BY created_at DESC, id DESC
LIMIT $2 OFFSET $3
`

type QueuePartitionGetManyByQueueIDParams struct {
	QueueID int64 `json:"queue_id"`
	Limit   int32 `json:"limit"`
	Offset  int32 `json:"offset"`
}

type QueuePartitionGetManyByQueueIDRow struct {
	ID           int64           `json:"id"`
	QueueID      int64           `json:"queue_id"`
	QueueItemKey string          `json:"queue_item_key"`
	PartitionKey string          `json:"partition_key"`
	Status       string          `json:"status"`
	ExternalKey  string          `json:"external_key"`
	PayloadJson  json.RawMessage `json:"payload_json"`
	ErrorMessage string          `json:"error_message"`
	QueuedAt     time.Time       `json:"queued_at"`
	StartedAt    sql.NullTime    `json:"started_at"`
	CompletedAt  sql.NullTime    `json:"completed_at"`
	CreatedAt    time.Time       `json:"created_at"`
	UpdatedAt    time.Time       `json:"updated_at"`
}

func (q *Queries) QueuePartitionGetManyByQueueID(ctx context.Context, arg QueuePartitionGetManyByQueueIDParams) ([]QueuePartitionGetManyByQueueIDRow, error) {
	rows, err := q.db.QueryContext(ctx, queuePartitionGetManyByQueueID, arg.QueueID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []QueuePartitionGetManyByQueueIDRow
	for rows.Next() {
		var i QueuePartitionGetManyByQueueIDRow
		if err := rows.Scan(
			&i.ID,
			&i.QueueID,
			&i.QueueItemKey,
			&i.PartitionKey,
			&i.Status,
			&i.ExternalKey,
			&i.PayloadJson,
			&i.ErrorMessage,
			&i.QueuedAt,
			&i.StartedAt,
			&i.CompletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const queueUpsert = `-- name: QueueUpsert :one
INSERT INTO queues (queue_key, display_name, description, route_path, load_mode, load_poll_every_seconds)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (queue_key) DO UPDATE SET
    display_name = excluded.display_name,
    description = excluded.description,
    route_path = excluded.route_path,
    load_mode = excluded.load_mode,
    load_poll_every_seconds = excluded.load_poll_every_seconds,
    updated_at = now()
RETURNING id, queue_key, display_name, description, route_path, load_mode, load_poll_every_seconds, created_at, updated_at
`

type QueueUpsertParams struct {
	QueueKey             string `json:"queue_key"`
	DisplayName          string `json:"display_name"`
	Description          string `json:"description"`
	RoutePath            string `json:"route_path"`
	LoadMode             string `json:"load_mode"`
	LoadPollEverySeconds int64  `json:"load_poll_every_seconds"`
}

func (q *Queries) QueueUpsert(ctx context.Context, arg QueueUpsertParams) (Queue, error) {
	row := q.db.QueryRowContext(ctx, queueUpsert,
		arg.QueueKey,
		arg.DisplayName,
		arg.Description,
		arg.RoutePath,
		arg.LoadMode,
		arg.LoadPollEverySeconds,
	)
	var i Queue
	err := row.Scan(
		&i.ID,
		&i.QueueKey,
		&i.DisplayName,
		&i.Description,
		&i.RoutePath,
		&i.LoadMode,
		&i.LoadPollEverySeconds,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
