// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: 004_partitions_backfills.sql

package postgresgen

import (
	"context"
	"database/sql"
	"encoding/json"
	"strings"
)

const backfillCount = `-- name: BackfillCount :one
SELECT COUNT(1) AS total
FROM backfills
`

func (q *Queries) BackfillCount(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, backfillCount)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const backfillCountByJobID = `-- name: BackfillCountByJobID :one
SELECT COUNT(1) AS total
FROM backfills
WHERE job_id = $1
`

func (q *Queries) BackfillCountByJobID(ctx context.Context, jobID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, backfillCountByJobID, jobID)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const backfillCreate = `-- name: BackfillCreate :one
INSERT INTO backfills (
    backfill_key,
    job_id,
    partition_definition_id,
    status,
    selection_mode,
    selection_json,
    triggered_by,
    policy_mode,
    max_partitions_per_run,
    requested_partition_count,
    requested_run_count,
    completed_partition_count,
    failed_partition_count,
    error_message,
    started_at,
    completed_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16)
RETURNING id, backfill_key, job_id, partition_definition_id, status, selection_mode, selection_json, triggered_by, policy_mode, max_partitions_per_run, requested_partition_count, requested_run_count, completed_partition_count, failed_partition_count, error_message, started_at, completed_at, created_at, updated_at
`

type BackfillCreateParams struct {
	BackfillKey             string          `json:"backfill_key"`
	JobID                   int64           `json:"job_id"`
	PartitionDefinitionID   int64           `json:"partition_definition_id"`
	Status                  string          `json:"status"`
	SelectionMode           string          `json:"selection_mode"`
	SelectionJson           json.RawMessage `json:"selection_json"`
	TriggeredBy             string          `json:"triggered_by"`
	PolicyMode              string          `json:"policy_mode"`
	MaxPartitionsPerRun     int64           `json:"max_partitions_per_run"`
	RequestedPartitionCount int64           `json:"requested_partition_count"`
	RequestedRunCount       int64           `json:"requested_run_count"`
	CompletedPartitionCount int64           `json:"completed_partition_count"`
	FailedPartitionCount    int64           `json:"failed_partition_count"`
	ErrorMessage            string          `json:"error_message"`
	StartedAt               sql.NullTime    `json:"started_at"`
	CompletedAt             sql.NullTime    `json:"completed_at"`
}

func (q *Queries) BackfillCreate(ctx context.Context, arg BackfillCreateParams) (Backfill, error) {
	row := q.db.QueryRowContext(ctx, backfillCreate,
		arg.BackfillKey,
		arg.JobID,
		arg.PartitionDefinitionID,
		arg.Status,
		arg.SelectionMode,
		arg.SelectionJson,
		arg.TriggeredBy,
		arg.PolicyMode,
		arg.MaxPartitionsPerRun,
		arg.RequestedPartitionCount,
		arg.RequestedRunCount,
		arg.CompletedPartitionCount,
		arg.FailedPartitionCount,
		arg.ErrorMessage,
		arg.StartedAt,
		arg.CompletedAt,
	)
	var i Backfill
	err := row.Scan(
		&i.ID,
		&i.BackfillKey,
		&i.JobID,
		&i.PartitionDefinitionID,
		&i.Status,
		&i.SelectionMode,
		&i.SelectionJson,
		&i.TriggeredBy,
		&i.PolicyMode,
		&i.MaxPartitionsPerRun,
		&i.RequestedPartitionCount,
		&i.RequestedRunCount,
		&i.CompletedPartitionCount,
		&i.FailedPartitionCount,
		&i.ErrorMessage,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const backfillDeleteByID = `-- name: BackfillDeleteByID :exec
DELETE FROM backfills
WHERE id = $1
`

func (q *Queries) BackfillDeleteByID(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, backfillDeleteByID, id)
	return err
}

const backfillGetByID = `-- name: BackfillGetByID :one
SELECT id, backfill_key, job_id, partition_definition_id, status, selection_mode, selection_json, triggered_by, policy_mode, max_partitions_per_run, requested_partition_count, requested_run_count, completed_partition_count, failed_partition_count, error_message, started_at, completed_at, created_at, updated_at
FROM backfills
WHERE id = $1
`

func (q *Queries) BackfillGetByID(ctx context.Context, id int64) (Backfill, error) {
	row := q.db.QueryRowContext(ctx, backfillGetByID, id)
	var i Backfill
	err := row.Scan(
		&i.ID,
		&i.BackfillKey,
		&i.JobID,
		&i.PartitionDefinitionID,
		&i.Status,
		&i.SelectionMode,
		&i.SelectionJson,
		&i.TriggeredBy,
		&i.PolicyMode,
		&i.MaxPartitionsPerRun,
		&i.RequestedPartitionCount,
		&i.RequestedRunCount,
		&i.CompletedPartitionCount,
		&i.FailedPartitionCount,
		&i.ErrorMessage,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const backfillGetByKey = `-- name: BackfillGetByKey :one
SELECT id, backfill_key, job_id, partition_definition_id, status, selection_mode, selection_json, triggered_by, policy_mode, max_partitions_per_run, requested_partition_count, requested_run_count, completed_partition_count, failed_partition_count, error_message, started_at, completed_at, created_at, updated_at
FROM backfills
WHERE backfill_key = $1
`

func (q *Queries) BackfillGetByKey(ctx context.Context, backfillKey string) (Backfill, error) {
	row := q.db.QueryRowContext(ctx, backfillGetByKey, backfillKey)
	var i Backfill
	err := row.Scan(
		&i.ID,
		&i.BackfillKey,
		&i.JobID,
		&i.PartitionDefinitionID,
		&i.Status,
		&i.SelectionMode,
		&i.SelectionJson,
		&i.TriggeredBy,
		&i.PolicyMode,
		&i.MaxPartitionsPerRun,
		&i.RequestedPartitionCount,
		&i.RequestedRunCount,
		&i.CompletedPartitionCount,
		&i.FailedPartitionCount,
		&i.ErrorMessage,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const backfillGetMany = `-- name: BackfillGetMany :many
SELECT id, backfill_key, job_id, partition_definition_id, status, selection_mode, selection_json, triggered_by, policy_mode, max_partitions_per_run, requested_partition_count, requested_run_count, completed_partition_count, failed_partition_count, error_message, started_at, completed_at, created_at, updated_at
FROM backfills
ORDER BY id DESC
LIMIT $1 OFFSET $2
`

type BackfillGetManyParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) BackfillGetMany(ctx context.Context, arg BackfillGetManyParams) ([]Backfill, error) {
	rows, err := q.db.QueryContext(ctx, backfillGetMany, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Backfill
	for rows.Next() {
		var i Backfill
		if err := rows.Scan(
			&i.ID,
			&i.BackfillKey,
			&i.JobID,
			&i.PartitionDefinitionID,
			&i.Status,
			&i.SelectionMode,
			&i.SelectionJson,
			&i.TriggeredBy,
			&i.PolicyMode,
			&i.MaxPartitionsPerRun,
			&i.RequestedPartitionCount,
			&i.RequestedRunCount,
			&i.CompletedPartitionCount,
			&i.FailedPartitionCount,
			&i.ErrorMessage,
			&i.StartedAt,
			&i.CompletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const backfillGetManyByJobID = `-- name: BackfillGetManyByJobID :many
SELECT id, backfill_key, job_id, partition_definition_id, status, selection_mode, selection_json, triggered_by, policy_mode, max_partitions_per_run, requested_partition_count, requested_run_count, completed_partition_count, failed_partition_count, error_message, started_at, completed_at, created_at, updated_at
FROM backfills
WHERE job_id = $1
ORDER BY id DESC
LIMIT $2 OFFSET $3
`

type BackfillGetManyByJobIDParams struct {
	JobID  int64 `json:"job_id"`
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) BackfillGetManyByJobID(ctx context.Context, arg BackfillGetManyByJobIDParams) ([]Backfill, error) {
	rows, err := q.db.QueryContext(ctx, backfillGetManyByJobID, arg.JobID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Backfill
	for rows.Next() {
		var i Backfill
		if err := rows.Scan(
			&i.ID,
			&i.BackfillKey,
			&i.JobID,
			&i.PartitionDefinitionID,
			&i.Status,
			&i.SelectionMode,
			&i.SelectionJson,
			&i.TriggeredBy,
			&i.PolicyMode,
			&i.MaxPartitionsPerRun,
			&i.RequestedPartitionCount,
			&i.RequestedRunCount,
			&i.CompletedPartitionCount,
			&i.FailedPartitionCount,
			&i.ErrorMessage,
			&i.StartedAt,
			&i.CompletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const backfillPartitionCountByBackfillID = `-- name: BackfillPartitionCountByBackfillID :one
SELECT COUNT(1) AS total
FROM backfill_partitions
WHERE backfill_id = $1
`

func (q *Queries) BackfillPartitionCountByBackfillID(ctx context.Context, backfillID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, backfillPartitionCountByBackfillID, backfillID)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const backfillPartitionCountByBackfillIDAndStatus = `-- name: BackfillPartitionCountByBackfillIDAndStatus :one
SELECT COUNT(1) AS total
FROM backfill_partitions
WHERE backfill_id = $1
  AND status = $2
`

type BackfillPartitionCountByBackfillIDAndStatusParams struct {
	BackfillID int64  `json:"backfill_id"`
	Status     string `json:"status"`
}

func (q *Queries) BackfillPartitionCountByBackfillIDAndStatus(ctx context.Context, arg BackfillPartitionCountByBackfillIDAndStatusParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, backfillPartitionCountByBackfillIDAndStatus, arg.BackfillID, arg.Status)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const backfillPartitionDeleteByBackfillID = `-- name: BackfillPartitionDeleteByBackfillID :exec
DELETE FROM backfill_partitions
WHERE backfill_id = $1
`

func (q *Queries) BackfillPartitionDeleteByBackfillID(ctx context.Context, backfillID int64) error {
	_, err := q.db.ExecContext(ctx, backfillPartitionDeleteByBackfillID, backfillID)
	return err
}

const backfillPartitionGetManyByBackfillID = `-- name: BackfillPartitionGetManyByBackfillID :many
SELECT id, backfill_id, partition_key, status, run_id, error_message, created_at, updated_at
FROM backfill_partitions
WHERE backfill_id = $1
ORDER BY id
LIMIT $2 OFFSET $3
`

type BackfillPartitionGetManyByBackfillIDParams struct {
	BackfillID int64 `json:"backfill_id"`
	Limit      int32 `json:"limit"`
	Offset     int32 `json:"offset"`
}

func (q *Queries) BackfillPartitionGetManyByBackfillID(ctx context.Context, arg BackfillPartitionGetManyByBackfillIDParams) ([]BackfillPartition, error) {
	rows, err := q.db.QueryContext(ctx, backfillPartitionGetManyByBackfillID, arg.BackfillID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BackfillPartition
	for rows.Next() {
		var i BackfillPartition
		if err := rows.Scan(
			&i.ID,
			&i.BackfillID,
			&i.PartitionKey,
			&i.Status,
			&i.RunID,
			&i.ErrorMessage,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const backfillPartitionGetManyByBackfillIDAndStatus = `-- name: BackfillPartitionGetManyByBackfillIDAndStatus :many
SELECT id, backfill_id, partition_key, status, run_id, error_message, created_at, updated_at
FROM backfill_partitions
WHERE backfill_id = $1
  AND status = $2
ORDER BY id
LIMIT $3 OFFSET $4
`

type BackfillPartitionGetManyByBackfillIDAndStatusParams struct {
	BackfillID int64  `json:"backfill_id"`
	Status     string `json:"status"`
	Limit      int32  `json:"limit"`
	Offset     int32  `json:"offset"`
}

func (q *Queries) BackfillPartitionGetManyByBackfillIDAndStatus(ctx context.Context, arg BackfillPartitionGetManyByBackfillIDAndStatusParams) ([]BackfillPartition, error) {
	rows, err := q.db.QueryContext(ctx, backfillPartitionGetManyByBackfillIDAndStatus,
		arg.BackfillID,
		arg.Status,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BackfillPartition
	for rows.Next() {
		var i BackfillPartition
		if err := rows.Scan(
			&i.ID,
			&i.BackfillID,
			&i.PartitionKey,
			&i.Status,
			&i.RunID,
			&i.ErrorMessage,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const backfillPartitionGetManyByRunID = `-- name: BackfillPartitionGetManyByRunID :many
SELECT id, backfill_id, partition_key, status, run_id, error_message, created_at, updated_at
FROM backfill_partitions
WHERE run_id = $1
ORDER BY id
`

func (q *Queries) BackfillPartitionGetManyByRunID(ctx context.Context, runID int64) ([]BackfillPartition, error) {
	rows, err := q.db.QueryContext(ctx, backfillPartitionGetManyByRunID, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BackfillPartition
	for rows.Next() {
		var i BackfillPartition
		if err := rows.Scan(
			&i.ID,
			&i.BackfillID,
			&i.PartitionKey,
			&i.Status,
			&i.RunID,
			&i.ErrorMessage,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const backfillPartitionUpdateStatusByBackfillIDAndPartitionKey = `-- name: BackfillPartitionUpdateStatusByBackfillIDAndPartitionKey :one
UPDATE backfill_partitions
SET status = $1,
    run_id = $2,
    error_message = $3,
    updated_at = now()
WHERE backfill_id = $4
  AND partition_key = $5
RETURNING id, backfill_id, partition_key, status, run_id, error_message, created_at, updated_at
`

type BackfillPartitionUpdateStatusByBackfillIDAndPartitionKeyParams struct {
	Status       string `json:"status"`
	RunID        int64  `json:"run_id"`
	ErrorMessage string `json:"error_message"`
	BackfillID   int64  `json:"backfill_id"`
	PartitionKey string `json:"partition_key"`
}

func (q *Queries) BackfillPartitionUpdateStatusByBackfillIDAndPartitionKey(ctx context.Context, arg BackfillPartitionUpdateStatusByBackfillIDAndPartitionKeyParams) (BackfillPartition, error) {
	row := q.db.QueryRowContext(ctx, backfillPartitionUpdateStatusByBackfillIDAndPartitionKey,
		arg.Status,
		arg.RunID,
		arg.ErrorMessage,
		arg.BackfillID,
		arg.PartitionKey,
	)
	var i BackfillPartition
	err := row.Scan(
		&i.ID,
		&i.BackfillID,
		&i.PartitionKey,
		&i.Status,
		&i.RunID,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const backfillPartitionUpsert = `-- name: BackfillPartitionUpsert :one
INSERT INTO backfill_partitions (
    backfill_id,
    partition_key,
    status,
    run_id,
    error_message
)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT(backfill_id, partition_key)
DO UPDATE SET
    status = excluded.status,
    run_id = excluded.run_id,
    error_message = excluded.error_message,
    updated_at = now()
RETURNING id, backfill_id, partition_key, status, run_id, error_message, created_at, updated_at
`

type BackfillPartitionUpsertParams struct {
	BackfillID   int64  `json:"backfill_id"`
	PartitionKey string `json:"partition_key"`
	Status       string `json:"status"`
	RunID        int64  `json:"run_id"`
	ErrorMessage string `json:"error_message"`
}

func (q *Queries) BackfillPartitionUpsert(ctx context.Context, arg BackfillPartitionUpsertParams) (BackfillPartition, error) {
	row := q.db.QueryRowContext(ctx, backfillPartitionUpsert,
		arg.BackfillID,
		arg.PartitionKey,
		arg.Status,
		arg.RunID,
		arg.ErrorMessage,
	)
	var i BackfillPartition
	err := row.Scan(
		&i.ID,
		&i.BackfillID,
		&i.PartitionKey,
		&i.Status,
		&i.RunID,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const backfillUpdateStatus = `-- name: BackfillUpdateStatus :one
UPDATE backfills
SET status = $1,
    requested_partition_count = $2,
    requested_run_count = $3,
    completed_partition_count = $4,
    failed_partition_count = $5,
    error_message = $6,
    started_at = $7,
    completed_at = $8,
    updated_at = now()
WHERE id = $9
RETURNING id, backfill_key, job_id, partition_definition_id, status, selection_mode, selection_json, triggered_by, policy_mode, max_partitions_per_run, requested_partition_count, requested_run_count, completed_partition_count, failed_partition_count, error_message, started_at, completed_at, created_at, updated_at
`

type BackfillUpdateStatusParams struct {
	Status                  string       `json:"status"`
	RequestedPartitionCount int64        `json:"requested_partition_count"`
	RequestedRunCount       int64        `json:"requested_run_count"`
	CompletedPartitionCount int64        `json:"completed_partition_count"`
	FailedPartitionCount    int64        `json:"failed_partition_count"`
	ErrorMessage            string       `json:"error_message"`
	StartedAt               sql.NullTime `json:"started_at"`
	CompletedAt             sql.NullTime `json:"completed_at"`
	ID                      int64        `json:"id"`
}

func (q *Queries) BackfillUpdateStatus(ctx context.Context, arg BackfillUpdateStatusParams) (Backfill, error) {
	row := q.db.QueryRowContext(ctx, backfillUpdateStatus,
		arg.Status,
		arg.RequestedPartitionCount,
		arg.RequestedRunCount,
		arg.CompletedPartitionCount,
		arg.FailedPartitionCount,
		arg.ErrorMessage,
		arg.StartedAt,
		arg.CompletedAt,
		arg.ID,
	)
	var i Backfill
	err := row.Scan(
		&i.ID,
		&i.BackfillKey,
		&i.JobID,
		&i.PartitionDefinitionID,
		&i.Status,
		&i.SelectionMode,
		&i.SelectionJson,
		&i.TriggeredBy,
		&i.PolicyMode,
		&i.MaxPartitionsPerRun,
		&i.RequestedPartitionCount,
		&i.RequestedRunCount,
		&i.CompletedPartitionCount,
		&i.FailedPartitionCount,
		&i.ErrorMessage,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const partitionDefinitionDeleteByID = `-- name: PartitionDefinitionDeleteByID :exec
DELETE FROM partition_definitions
WHERE id = $1
`

func (q *Queries) PartitionDefinitionDeleteByID(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, partitionDefinitionDeleteByID, id)
	return err
}

const partitionDefinitionGetByID = `-- name: PartitionDefinitionGetByID :one
SELECT id, job_id, target_kind, target_key, definition_kind, definition_json, enabled, created_at, updated_at
FROM partition_definitions
WHERE id = $1
`

func (q *Queries) PartitionDefinitionGetByID(ctx context.Context, id int64) (PartitionDefinition, error) {
	row := q.db.QueryRowContext(ctx, partitionDefinitionGetByID, id)
	var i PartitionDefinition
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.TargetKind,
		&i.TargetKey,
		&i.DefinitionKind,
		&i.DefinitionJson,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const partitionDefinitionGetByJobIDAndTarget = `-- name: PartitionDefinitionGetByJobIDAndTarget :one
SELECT id, job_id, target_kind, target_key, definition_kind, definition_json, enabled, created_at, updated_at
FROM partition_definitions
WHERE job_id = $1
  AND target_kind = $2
  AND target_key = $3
`

type PartitionDefinitionGetByJobIDAndTargetParams struct {
	JobID      int64  `json:"job_id"`
	TargetKind string `json:"target_kind"`
	TargetKey  string `json:"target_key"`
}

func (q *Queries) PartitionDefinitionGetByJobIDAndTarget(ctx context.Context, arg PartitionDefinitionGetByJobIDAndTargetParams) (PartitionDefinition, error) {
	row := q.db.QueryRowContext(ctx, partitionDefinitionGetByJobIDAndTarget, arg.JobID, arg.TargetKind, arg.TargetKey)
	var i PartitionDefinition
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.TargetKind,
		&i.TargetKey,
		&i.DefinitionKind,
		&i.DefinitionJson,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const partitionDefinitionGetManyByJobID = `-- name: PartitionDefinitionGetManyByJobID :many
SELECT id, job_id, target_kind, target_key, definition_kind, definition_json, enabled, created_at, updated_at
FROM partition_definitions
WHERE job_id = $1
ORDER BY target_kind, target_key, id
`

func (q *Queries) PartitionDefinitionGetManyByJobID(ctx context.Context, jobID int64) ([]PartitionDefinition, error) {
	rows, err := q.db.QueryContext(ctx, partitionDefinitionGetManyByJobID, jobID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PartitionDefinition
	for rows.Next() {
		var i PartitionDefinition
		if err := rows.Scan(
			&i.ID,
			&i.JobID,
			&i.TargetKind,
			&i.TargetKey,
			&i.DefinitionKind,
			&i.DefinitionJson,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const partitionDefinitionUpsert = `-- name: PartitionDefinitionUpsert :one
INSERT INTO partition_definitions (
    job_id,
    target_kind,
    target_key,
    definition_kind,
    definition_json,
    enabled
)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT(job_id, target_kind, target_key)
DO UPDATE SET
    definition_kind = excluded.definition_kind,
    definition_json = excluded.definition_json,
    enabled = excluded.enabled,
    updated_at = now()
RETURNING id, job_id, target_kind, target_key, definition_kind, definition_json, enabled, created_at, updated_at
`

type PartitionDefinitionUpsertParams struct {
	JobID          int64           `json:"job_id"`
	TargetKind     string          `json:"target_kind"`
	TargetKey      string          `json:"target_key"`
	DefinitionKind string          `json:"definition_kind"`
	DefinitionJson json.RawMessage `json:"definition_json"`
	Enabled        bool            `json:"enabled"`
}

func (q *Queries) PartitionDefinitionUpsert(ctx context.Context, arg PartitionDefinitionUpsertParams) (PartitionDefinition, error) {
	row := q.db.QueryRowContext(ctx, partitionDefinitionUpsert,
		arg.JobID,
		arg.TargetKind,
		arg.TargetKey,
		arg.DefinitionKind,
		arg.DefinitionJson,
		arg.Enabled,
	)
	var i PartitionDefinition
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.TargetKind,
		&i.TargetKey,
		&i.DefinitionKind,
		&i.DefinitionJson,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const partitionKeyCountByDefinitionID = `-- name: PartitionKeyCountByDefinitionID :one
SELECT COUNT(1) AS total
FROM partition_keys
WHERE partition_definition_id = $1
`

func (q *Queries) PartitionKeyCountByDefinitionID(ctx context.Context, partitionDefinitionID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, partitionKeyCountByDefinitionID, partitionDefinitionID)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const partitionKeyDeleteByDefinitionID = `-- name: PartitionKeyDeleteByDefinitionID :exec
DELETE FROM partition_keys
WHERE partition_definition_id = $1
`

func (q *Queries) PartitionKeyDeleteByDefinitionID(ctx context.Context, partitionDefinitionID int64) error {
	_, err := q.db.ExecContext(ctx, partitionKeyDeleteByDefinitionID, partitionDefinitionID)
	return err
}

const partitionKeyDeleteByDefinitionIDAndKey = `-- name: PartitionKeyDeleteByDefinitionIDAndKey :exec
DELETE FROM partition_keys
WHERE partition_definition_id = $1
  AND partition_key = $2
`

type PartitionKeyDeleteByDefinitionIDAndKeyParams struct {
	PartitionDefinitionID int64  `json:"partition_definition_id"`
	PartitionKey          string `json:"partition_key"`
}

func (q *Queries) PartitionKeyDeleteByDefinitionIDAndKey(ctx context.Context, arg PartitionKeyDeleteByDefinitionIDAndKeyParams) error {
	_, err := q.db.ExecContext(ctx, partitionKeyDeleteByDefinitionIDAndKey, arg.PartitionDefinitionID, arg.PartitionKey)
	return err
}

const partitionKeyGetByDefinitionIDAndKey = `-- name: PartitionKeyGetByDefinitionIDAndKey :one
SELECT id, partition_definition_id, partition_key, sort_index, is_active, created_at, updated_at
FROM partition_keys
WHERE partition_definition_id = $1
  AND partition_key = $2
`

type PartitionKeyGetByDefinitionIDAndKeyParams struct {
	PartitionDefinitionID int64  `json:"partition_definition_id"`
	PartitionKey          string `json:"partition_key"`
}

func (q *Queries) PartitionKeyGetByDefinitionIDAndKey(ctx context.Context, arg PartitionKeyGetByDefinitionIDAndKeyParams) (PartitionKey, error) {
	row := q.db.QueryRowContext(ctx, partitionKeyGetByDefinitionIDAndKey, arg.PartitionDefinitionID, arg.PartitionKey)
	var i PartitionKey
	err := row.Scan(
		&i.ID,
		&i.PartitionDefinitionID,
		&i.PartitionKey,
		&i.SortIndex,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const partitionKeyGetManyByDefinitionID = `-- name: PartitionKeyGetManyByDefinitionID :many
SELECT id, partition_definition_id, partition_key, sort_index, is_active, created_at, updated_at
FROM partition_keys
WHERE partition_definition_id = $1
ORDER BY sort_index, partition_key, id
LIMIT $2 OFFSET $3
`

type PartitionKeyGetManyByDefinitionIDParams struct {
	PartitionDefinitionID int64 `json:"partition_definition_id"`
	Limit                 int32 `json:"limit"`
	Offset                int32 `json:"offset"`
}

func (q *Queries) PartitionKeyGetManyByDefinitionID(ctx context.Context, arg PartitionKeyGetManyByDefinitionIDParams) ([]PartitionKey, error) {
	rows, err := q.db.QueryContext(ctx, partitionKeyGetManyByDefinitionID, arg.PartitionDefinitionID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PartitionKey
	for rows.Next() {
		var i PartitionKey
		if err := rows.Scan(
			&i.ID,
			&i.PartitionDefinitionID,
			&i.PartitionKey,
			&i.SortIndex,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const partitionKeyGetManyByDefinitionIDAndKeys = `-- name: PartitionKeyGetManyByDefinitionIDAndKeys :many
SELECT id, partition_definition_id, partition_key, sort_index, is_active, created_at, updated_at
FROM partition_keys
WHERE partition_definition_id = $1
  AND partition_key IN ($2)
ORDER BY sort_index, partition_key, id
`

type PartitionKeyGetManyByDefinitionIDAndKeysParams struct {
	PartitionDefinitionID int64    `json:"partition_definition_id"`
	PartitionKeys         []string `json:"partition_keys"`
}

func (q *Queries) PartitionKeyGetManyByDefinitionIDAndKeys(ctx context.Context, arg PartitionKeyGetManyByDefinitionIDAndKeysParams) ([]PartitionKey, error) {
	query := partitionKeyGetManyByDefinitionIDAndKeys
	var queryParams []interface{}
	queryParams = append(queryParams, arg.PartitionDefinitionID)
	if len(arg.PartitionKeys) > 0 {
		for _, v := range arg.PartitionKeys {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:partition_keys*/?", strings.Repeat(",?", len(arg.PartitionKeys))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:partition_keys*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PartitionKey
	for rows.Next() {
		var i PartitionKey
		if err := rows.Scan(
			&i.ID,
			&i.PartitionDefinitionID,
			&i.PartitionKey,
			&i.SortIndex,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const partitionKeyGetManyByDefinitionIDRange = `-- name: PartitionKeyGetManyByDefinitionIDRange :many
SELECT keys.id,
       keys.partition_definition_id,
       keys.partition_key,
       keys.sort_index,
       keys.is_active,
       keys.created_at,
       keys.updated_at
FROM partition_keys keys
JOIN partition_keys start_key
  ON start_key.partition_definition_id = keys.partition_definition_id
 AND start_key.partition_key = $1
JOIN partition_keys end_key
  ON end_key.partition_definition_id = keys.partition_definition_id
 AND end_key.partition_key = $2
WHERE keys.partition_definition_id = $3
  AND keys.sort_index BETWEEN
    CASE
        WHEN start_key.sort_index <= end_key.sort_index THEN start_key.sort_index
        ELSE end_key.sort_index
    END
    AND
    CASE
        WHEN start_key.sort_index <= end_key.sort_index THEN end_key.sort_index
        ELSE start_key.sort_index
    END
ORDER BY keys.sort_index, keys.partition_key, keys.id
`

type PartitionKeyGetManyByDefinitionIDRangeParams struct {
	PartitionKey          string `json:"partition_key"`
	PartitionKey_2        string `json:"partition_key_2"`
	PartitionDefinitionID int64  `json:"partition_definition_id"`
}

func (q *Queries) PartitionKeyGetManyByDefinitionIDRange(ctx context.Context, arg PartitionKeyGetManyByDefinitionIDRangeParams) ([]PartitionKey, error) {
	rows, err := q.db.QueryContext(ctx, partitionKeyGetManyByDefinitionIDRange, arg.PartitionKey, arg.PartitionKey_2, arg.PartitionDefinitionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PartitionKey
	for rows.Next() {
		var i PartitionKey
		if err := rows.Scan(
			&i.ID,
			&i.PartitionDefinitionID,
			&i.PartitionKey,
			&i.SortIndex,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const partitionKeyUpsert = `-- name: PartitionKeyUpsert :one
INSERT INTO partition_keys (
    partition_definition_id,
    partition_key,
    sort_index,
    is_active
)
VALUES ($1, $2, $3, $4)
ON CONFLICT(partition_definition_id, partition_key)
DO UPDATE SET
    sort_index = excluded.sort_index,
    is_active = excluded.is_active,
    updated_at = now()
RETURNING id, partition_definition_id, partition_key, sort_index, is_active, created_at, updated_at
`

type PartitionKeyUpsertParams struct {
	PartitionDefinitionID int64  `json:"partition_definition_id"`
	PartitionKey          string `json:"partition_key"`
	SortIndex             int64  `json:"sort_index"`
	IsActive              bool   `json:"is_active"`
}

func (q *Queries) PartitionKeyUpsert(ctx context.Context, arg PartitionKeyUpsertParams) (PartitionKey, error) {
	row := q.db.QueryRowContext(ctx, partitionKeyUpsert,
		arg.PartitionDefinitionID,
		arg.PartitionKey,
		arg.SortIndex,
		arg.IsActive,
	)
	var i PartitionKey
	err := row.Scan(
		&i.ID,
		&i.PartitionDefinitionID,
		&i.PartitionKey,
		&i.SortIndex,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const runPartitionTargetCountByBackfillKey = `-- name: RunPartitionTargetCountByBackfillKey :one
SELECT COUNT(1) AS total
FROM run_partition_targets
WHERE backfill_key = $1
`

func (q *Queries) RunPartitionTargetCountByBackfillKey(ctx context.Context, backfillKey string) (int64, error) {
	row := q.db.QueryRowContext(ctx, runPartitionTargetCountByBackfillKey, backfillKey)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const runPartitionTargetDeleteByRunID = `-- name: RunPartitionTargetDeleteByRunID :exec
DELETE FROM run_partition_targets
WHERE run_id = $1
`

func (q *Queries) RunPartitionTargetDeleteByRunID(ctx context.Context, runID int64) error {
	_, err := q.db.ExecContext(ctx, runPartitionTargetDeleteByRunID, runID)
	return err
}

const runPartitionTargetGetByRunID = `-- name: RunPartitionTargetGetByRunID :one
SELECT run_id, partition_definition_id, selection_mode, partition_key, range_start_key, range_end_key, partition_subset_json, tags_json, backfill_key, created_at, updated_at
FROM run_partition_targets
WHERE run_id = $1
`

func (q *Queries) RunPartitionTargetGetByRunID(ctx context.Context, runID int64) (RunPartitionTarget, error) {
	row := q.db.QueryRowContext(ctx, runPartitionTargetGetByRunID, runID)
	var i RunPartitionTarget
	err := row.Scan(
		&i.RunID,
		&i.PartitionDefinitionID,
		&i.SelectionMode,
		&i.PartitionKey,
		&i.RangeStartKey,
		&i.RangeEndKey,
		&i.PartitionSubsetJson,
		&i.TagsJson,
		&i.BackfillKey,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const runPartitionTargetGetManyByBackfillKey = `-- name: RunPartitionTargetGetManyByBackfillKey :many
SELECT run_id, partition_definition_id, selection_mode, partition_key, range_start_key, range_end_key, partition_subset_json, tags_json, backfill_key, created_at, updated_at
FROM run_partition_targets
WHERE backfill_key = $1
ORDER BY run_id DESC
LIMIT $2 OFFSET $3
`

type RunPartitionTargetGetManyByBackfillKeyParams struct {
	BackfillKey string `json:"backfill_key"`
	Limit       int32  `json:"limit"`
	Offset      int32  `json:"offset"`
}

func (q *Queries) RunPartitionTargetGetManyByBackfillKey(ctx context.Context, arg RunPartitionTargetGetManyByBackfillKeyParams) ([]RunPartitionTarget, error) {
	rows, err := q.db.QueryContext(ctx, runPartitionTargetGetManyByBackfillKey, arg.BackfillKey, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RunPartitionTarget
	for rows.Next() {
		var i RunPartitionTarget
		if err := rows.Scan(
			&i.RunID,
			&i.PartitionDefinitionID,
			&i.SelectionMode,
			&i.PartitionKey,
			&i.RangeStartKey,
			&i.RangeEndKey,
			&i.PartitionSubsetJson,
			&i.TagsJson,
			&i.BackfillKey,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const runPartitionTargetUpsert = `-- name: RunPartitionTargetUpsert :one
INSERT INTO run_partition_targets (
    run_id,
    partition_definition_id,
    selection_mode,
    partition_key,
    range_start_key,
    range_end_key,
    partition_subset_json,
    tags_json,
    backfill_key
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
ON CONFLICT(run_id)
DO UPDATE SET
    partition_definition_id = excluded.partition_definition_id,
    selection_mode = excluded.selection_mode,
    partition_key = excluded.partition_key,
    range_start_key = excluded.range_start_key,
    range_end_key = excluded.range_end_key,
    partition_subset_json = excluded.partition_subset_json,
    tags_json = excluded.tags_json,
    backfill_key = excluded.backfill_key,
    updated_at = now()
RETURNING run_id, partition_definition_id, selection_mode, partition_key, range_start_key, range_end_key, partition_subset_json, tags_json, backfill_key, created_at, updated_at
`

type RunPartitionTargetUpsertParams struct {
	RunID                 int64           `json:"run_id"`
	PartitionDefinitionID int64           `json:"partition_definition_id"`
	SelectionMode         string          `json:"selection_mode"`
	PartitionKey          string          `json:"partition_key"`
	RangeStartKey         string          `json:"range_start_key"`
	RangeEndKey           string          `json:"range_end_key"`
	PartitionSubsetJson   json.RawMessage `json:"partition_subset_json"`
	TagsJson              json.RawMessage `json:"tags_json"`
	BackfillKey           string          `json:"backfill_key"`
}

func (q *Queries) RunPartitionTargetUpsert(ctx context.Context, arg RunPartitionTargetUpsertParams) (RunPartitionTarget, error) {
	row := q.db.QueryRowContext(ctx, runPartitionTargetUpsert,
		arg.RunID,
		arg.PartitionDefinitionID,
		arg.SelectionMode,
		arg.PartitionKey,
		arg.RangeStartKey,
		arg.RangeEndKey,
		arg.PartitionSubsetJson,
		arg.TagsJson,
		arg.BackfillKey,
	)
	var i RunPartitionTarget
	err := row.Scan(
		&i.RunID,
		&i.PartitionDefinitionID,
		&i.SelectionMode,
		&i.PartitionKey,
		&i.RangeStartKey,
		&i.RangeEndKey,
		&i.PartitionSubsetJson,
		&i.TagsJson,
		&i.BackfillKey,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const runSystemTagCountByTagKeyAndValue = `-- name: RunSystemTagCountByTagKeyAndValue :one
SELECT COUNT(1) AS total
FROM run_system_tags
WHERE tag_key = $1
  AND tag_value = $2
`

type RunSystemTagCountByTagKeyAndValueParams struct {
	TagKey   string `json:"tag_key"`
	TagValue string `json:"tag_value"`
}

func (q *Queries) RunSystemTagCountByTagKeyAndValue(ctx context.Context, arg RunSystemTagCountByTagKeyAndValueParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, runSystemTagCountByTagKeyAndValue, arg.TagKey, arg.TagValue)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const runSystemTagDeleteByRunID = `-- name: RunSystemTagDeleteByRunID :exec
DELETE FROM run_system_tags
WHERE run_id = $1
`

func (q *Queries) RunSystemTagDeleteByRunID(ctx context.Context, runID int64) error {
	_, err := q.db.ExecContext(ctx, runSystemTagDeleteByRunID, runID)
	return err
}

const runSystemTagGetManyByRunID = `-- name: RunSystemTagGetManyByRunID :many
SELECT id, run_id, tag_key, tag_value, created_at
FROM run_system_tags
WHERE run_id = $1
ORDER BY tag_key
`

func (q *Queries) RunSystemTagGetManyByRunID(ctx context.Context, runID int64) ([]RunSystemTag, error) {
	rows, err := q.db.QueryContext(ctx, runSystemTagGetManyByRunID, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RunSystemTag
	for rows.Next() {
		var i RunSystemTag
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.TagKey,
			&i.TagValue,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const runSystemTagGetManyByTagKeyAndValue = `-- name: RunSystemTagGetManyByTagKeyAndValue :many
SELECT id, run_id, tag_key, tag_value, created_at
FROM run_system_tags
WHERE tag_key = $1
  AND tag_value = $2
ORDER BY run_id DESC
LIMIT $3 OFFSET $4
`

type RunSystemTagGetManyByTagKeyAndValueParams struct {
	TagKey   string `json:"tag_key"`
	TagValue string `json:"tag_value"`
	Limit    int32  `json:"limit"`
	Offset   int32  `json:"offset"`
}

func (q *Queries) RunSystemTagGetManyByTagKeyAndValue(ctx context.Context, arg RunSystemTagGetManyByTagKeyAndValueParams) ([]RunSystemTag, error) {
	rows, err := q.db.QueryContext(ctx, runSystemTagGetManyByTagKeyAndValue,
		arg.TagKey,
		arg.TagValue,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RunSystemTag
	for rows.Next() {
		var i RunSystemTag
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.TagKey,
			&i.TagValue,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const runSystemTagUpsert = `-- name: RunSystemTagUpsert :one
INSERT INTO run_system_tags (run_id, tag_key, tag_value)
VALUES ($1, $2, $3)
ON CONFLICT(run_id, tag_key)
DO UPDATE SET
    tag_value = excluded.tag_value
RETURNING id, run_id, tag_key, tag_value, created_at
`

type RunSystemTagUpsertParams struct {
	RunID    int64  `json:"run_id"`
	TagKey   string `json:"tag_key"`
	TagValue string `json:"tag_value"`
}

func (q *Queries) RunSystemTagUpsert(ctx context.Context, arg RunSystemTagUpsertParams) (RunSystemTag, error) {
	row := q.db.QueryRowContext(ctx, runSystemTagUpsert, arg.RunID, arg.TagKey, arg.TagValue)
	var i RunSystemTag
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.TagKey,
		&i.TagValue,
		&i.CreatedAt,
	)
	return i, err
}
