// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package postgresgen

import (
	"database/sql"
	"encoding/json"
	"time"
)

type Job struct {
	ID                int64           `json:"id"`
	JobKey            string          `json:"job_key"`
	DisplayName       string          `json:"display_name"`
	Description       string          `json:"description"`
	DefaultParamsJson json.RawMessage `json:"default_params_json"`
	CreatedAt         time.Time       `json:"created_at"`
	UpdatedAt         time.Time       `json:"updated_at"`
}

type JobEdge struct {
	ID          int64     `json:"id"`
	JobID       int64     `json:"job_id"`
	FromStepKey string    `json:"from_step_key"`
	ToStepKey   string    `json:"to_step_key"`
	CreatedAt   time.Time `json:"created_at"`
}

type JobNode struct {
	ID           int64           `json:"id"`
	JobID        int64           `json:"job_id"`
	StepKey      string          `json:"step_key"`
	DisplayName  string          `json:"display_name"`
	Description  string          `json:"description"`
	Kind         string          `json:"kind"`
	MetadataJson json.RawMessage `json:"metadata_json"`
	SortIndex    int64           `json:"sort_index"`
	CreatedAt    time.Time       `json:"created_at"`
}

type Queue struct {
	ID                   int64     `json:"id"`
	QueueKey             string    `json:"queue_key"`
	DisplayName          string    `json:"display_name"`
	Description          string    `json:"description"`
	RoutePath            string    `json:"route_path"`
	LoadMode             string    `json:"load_mode"`
	LoadPollEverySeconds int64     `json:"load_poll_every_seconds"`
	CreatedAt            time.Time `json:"created_at"`
	UpdatedAt            time.Time `json:"updated_at"`
}

type QueueItem struct {
	ID           int64           `json:"id"`
	QueueID      int64           `json:"queue_id"`
	QueueItemKey string          `json:"queue_item_key"`
	PartitionKey string          `json:"partition_key"`
	Status       string          `json:"status"`
	ExternalKey  string          `json:"external_key"`
	PayloadJson  json.RawMessage `json:"payload_json"`
	ErrorMessage string          `json:"error_message"`
	QueuedAt     time.Time       `json:"queued_at"`
	StartedAt    sql.NullTime    `json:"started_at"`
	CompletedAt  sql.NullTime    `json:"completed_at"`
	CreatedAt    time.Time       `json:"created_at"`
	UpdatedAt    time.Time       `json:"updated_at"`
}

type QueueItemRun struct {
	ID          int64     `json:"id"`
	QueueItemID int64     `json:"queue_item_id"`
	JobID       int64     `json:"job_id"`
	RunID       int64     `json:"run_id"`
	CreatedAt   time.Time `json:"created_at"`
}

type QueueItemStepMetadatum struct {
	ID           int64           `json:"id"`
	QueueItemID  int64           `json:"queue_item_id"`
	JobID        int64           `json:"job_id"`
	RunID        int64           `json:"run_id"`
	StepKey      string          `json:"step_key"`
	MetadataJson json.RawMessage `json:"metadata_json"`
	CreatedAt    time.Time       `json:"created_at"`
	UpdatedAt    time.Time       `json:"updated_at"`
}

type QueueJob struct {
	ID        int64     `json:"id"`
	QueueID   int64     `json:"queue_id"`
	JobID     int64     `json:"job_id"`
	SortIndex int64     `json:"sort_index"`
	CreatedAt time.Time `json:"created_at"`
}

type Run struct {
	ID           int64           `json:"id"`
	RunKey       string          `json:"run_key"`
	JobID        int64           `json:"job_id"`
	Status       string          `json:"status"`
	TriggeredBy  string          `json:"triggered_by"`
	ParamsJson   json.RawMessage `json:"params_json"`
	QueuedAt     time.Time       `json:"queued_at"`
	StartedAt    sql.NullTime    `json:"started_at"`
	CompletedAt  sql.NullTime    `json:"completed_at"`
	ParentRunID  int64           `json:"parent_run_id"`
	RerunStepKey string          `json:"rerun_step_key"`
	ErrorMessage string          `json:"error_message"`
	CreatedAt    time.Time       `json:"created_at"`
	UpdatedAt    time.Time       `json:"updated_at"`
}

type RunEvent struct {
	ID            int64           `json:"id"`
	RunID         int64           `json:"run_id"`
	StepKey       string          `json:"step_key"`
	EventType     string          `json:"event_type"`
	Level         string          `json:"level"`
	Message       string          `json:"message"`
	EventDataJson json.RawMessage `json:"event_data_json"`
	CreatedAt     time.Time       `json:"created_at"`
}

type RunStep struct {
	ID           int64           `json:"id"`
	RunID        int64           `json:"run_id"`
	JobNodeID    int64           `json:"job_node_id"`
	StepKey      string          `json:"step_key"`
	Status       string          `json:"status"`
	Attempt      int64           `json:"attempt"`
	StartedAt    sql.NullTime    `json:"started_at"`
	CompletedAt  sql.NullTime    `json:"completed_at"`
	DurationMs   int64           `json:"duration_ms"`
	OutputJson   json.RawMessage `json:"output_json"`
	ErrorMessage string          `json:"error_message"`
	LogExcerpt   string          `json:"log_excerpt"`
	CreatedAt    time.Time       `json:"created_at"`
	UpdatedAt    time.Time       `json:"updated_at"`
}

type SchedulerHeartbeat struct {
	SchedulerKey        string       `json:"scheduler_key"`
	LastHeartbeatAt     time.Time    `json:"last_heartbeat_at"`
	LastTickStartedAt   sql.NullTime `json:"last_tick_started_at"`
	LastTickCompletedAt sql.NullTime `json:"last_tick_completed_at"`
	LastError           string       `json:"last_error"`
	UpdatedAt           time.Time    `json:"updated_at"`
}

type SchedulerScheduleRun struct {
	ID           int64     `json:"id"`
	JobKey       string    `json:"job_key"`
	ScheduleKey  string    `json:"schedule_key"`
	ScheduledFor time.Time `json:"scheduled_for"`
	RunKey       string    `json:"run_key"`
	TriggeredBy  string    `json:"triggered_by"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
}

type SchedulerScheduleState struct {
	JobKey         string       `json:"job_key"`
	ScheduleKey    string       `json:"schedule_key"`
	LastCheckedAt  sql.NullTime `json:"last_checked_at"`
	LastEnqueuedAt sql.NullTime `json:"last_enqueued_at"`
	NextRunAt      sql.NullTime `json:"next_run_at"`
	UpdatedAt      time.Time    `json:"updated_at"`
}
