// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package postgresgen

import (
	"database/sql"
	"encoding/json"
	"time"
)

type Backfill struct {
	ID                      int64           `json:"id"`
	BackfillKey             string          `json:"backfill_key"`
	JobID                   int64           `json:"job_id"`
	PartitionDefinitionID   int64           `json:"partition_definition_id"`
	Status                  string          `json:"status"`
	SelectionMode           string          `json:"selection_mode"`
	SelectionJson           json.RawMessage `json:"selection_json"`
	TriggeredBy             string          `json:"triggered_by"`
	PolicyMode              string          `json:"policy_mode"`
	MaxPartitionsPerRun     int64           `json:"max_partitions_per_run"`
	RequestedPartitionCount int64           `json:"requested_partition_count"`
	RequestedRunCount       int64           `json:"requested_run_count"`
	CompletedPartitionCount int64           `json:"completed_partition_count"`
	FailedPartitionCount    int64           `json:"failed_partition_count"`
	ErrorMessage            string          `json:"error_message"`
	StartedAt               sql.NullTime    `json:"started_at"`
	CompletedAt             sql.NullTime    `json:"completed_at"`
	CreatedAt               time.Time       `json:"created_at"`
	UpdatedAt               time.Time       `json:"updated_at"`
}

type BackfillPartition struct {
	ID           int64     `json:"id"`
	BackfillID   int64     `json:"backfill_id"`
	PartitionKey string    `json:"partition_key"`
	Status       string    `json:"status"`
	RunID        int64     `json:"run_id"`
	ErrorMessage string    `json:"error_message"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
}

type Job struct {
	ID                int64           `json:"id"`
	JobKey            string          `json:"job_key"`
	DisplayName       string          `json:"display_name"`
	Description       string          `json:"description"`
	DefaultParamsJson json.RawMessage `json:"default_params_json"`
	CreatedAt         time.Time       `json:"created_at"`
	UpdatedAt         time.Time       `json:"updated_at"`
}

type JobEdge struct {
	ID          int64     `json:"id"`
	JobID       int64     `json:"job_id"`
	FromStepKey string    `json:"from_step_key"`
	ToStepKey   string    `json:"to_step_key"`
	CreatedAt   time.Time `json:"created_at"`
}

type JobNode struct {
	ID           int64           `json:"id"`
	JobID        int64           `json:"job_id"`
	StepKey      string          `json:"step_key"`
	DisplayName  string          `json:"display_name"`
	Description  string          `json:"description"`
	Kind         string          `json:"kind"`
	MetadataJson json.RawMessage `json:"metadata_json"`
	SortIndex    int64           `json:"sort_index"`
	CreatedAt    time.Time       `json:"created_at"`
}

type PartitionDefinition struct {
	ID             int64           `json:"id"`
	JobID          int64           `json:"job_id"`
	TargetKind     string          `json:"target_kind"`
	TargetKey      string          `json:"target_key"`
	DefinitionKind string          `json:"definition_kind"`
	DefinitionJson json.RawMessage `json:"definition_json"`
	Enabled        bool            `json:"enabled"`
	CreatedAt      time.Time       `json:"created_at"`
	UpdatedAt      time.Time       `json:"updated_at"`
}

type PartitionKey struct {
	ID                    int64     `json:"id"`
	PartitionDefinitionID int64     `json:"partition_definition_id"`
	PartitionKey          string    `json:"partition_key"`
	SortIndex             int64     `json:"sort_index"`
	IsActive              bool      `json:"is_active"`
	CreatedAt             time.Time `json:"created_at"`
	UpdatedAt             time.Time `json:"updated_at"`
}

type Run struct {
	ID           int64           `json:"id"`
	RunKey       string          `json:"run_key"`
	JobID        int64           `json:"job_id"`
	Status       string          `json:"status"`
	TriggeredBy  string          `json:"triggered_by"`
	ParamsJson   json.RawMessage `json:"params_json"`
	QueuedAt     time.Time       `json:"queued_at"`
	StartedAt    sql.NullTime    `json:"started_at"`
	CompletedAt  sql.NullTime    `json:"completed_at"`
	ParentRunID  int64           `json:"parent_run_id"`
	RerunStepKey string          `json:"rerun_step_key"`
	ErrorMessage string          `json:"error_message"`
	CreatedAt    time.Time       `json:"created_at"`
	UpdatedAt    time.Time       `json:"updated_at"`
}

type RunEvent struct {
	ID            int64           `json:"id"`
	RunID         int64           `json:"run_id"`
	StepKey       string          `json:"step_key"`
	EventType     string          `json:"event_type"`
	Level         string          `json:"level"`
	Message       string          `json:"message"`
	EventDataJson json.RawMessage `json:"event_data_json"`
	CreatedAt     time.Time       `json:"created_at"`
}

type RunPartitionTarget struct {
	RunID                 int64           `json:"run_id"`
	PartitionDefinitionID int64           `json:"partition_definition_id"`
	SelectionMode         string          `json:"selection_mode"`
	PartitionKey          string          `json:"partition_key"`
	RangeStartKey         string          `json:"range_start_key"`
	RangeEndKey           string          `json:"range_end_key"`
	PartitionSubsetJson   json.RawMessage `json:"partition_subset_json"`
	TagsJson              json.RawMessage `json:"tags_json"`
	BackfillKey           string          `json:"backfill_key"`
	CreatedAt             time.Time       `json:"created_at"`
	UpdatedAt             time.Time       `json:"updated_at"`
}

type RunStep struct {
	ID           int64           `json:"id"`
	RunID        int64           `json:"run_id"`
	JobNodeID    int64           `json:"job_node_id"`
	StepKey      string          `json:"step_key"`
	Status       string          `json:"status"`
	Attempt      int64           `json:"attempt"`
	StartedAt    sql.NullTime    `json:"started_at"`
	CompletedAt  sql.NullTime    `json:"completed_at"`
	DurationMs   int64           `json:"duration_ms"`
	OutputJson   json.RawMessage `json:"output_json"`
	ErrorMessage string          `json:"error_message"`
	LogExcerpt   string          `json:"log_excerpt"`
	CreatedAt    time.Time       `json:"created_at"`
	UpdatedAt    time.Time       `json:"updated_at"`
}

type RunSystemTag struct {
	ID        int64     `json:"id"`
	RunID     int64     `json:"run_id"`
	TagKey    string    `json:"tag_key"`
	TagValue  string    `json:"tag_value"`
	CreatedAt time.Time `json:"created_at"`
}

type SchedulerHeartbeat struct {
	SchedulerKey        string       `json:"scheduler_key"`
	LastHeartbeatAt     time.Time    `json:"last_heartbeat_at"`
	LastTickStartedAt   sql.NullTime `json:"last_tick_started_at"`
	LastTickCompletedAt sql.NullTime `json:"last_tick_completed_at"`
	LastError           string       `json:"last_error"`
	UpdatedAt           time.Time    `json:"updated_at"`
}

type SchedulerScheduleRun struct {
	ID           int64     `json:"id"`
	JobKey       string    `json:"job_key"`
	ScheduleKey  string    `json:"schedule_key"`
	ScheduledFor time.Time `json:"scheduled_for"`
	RunKey       string    `json:"run_key"`
	TriggeredBy  string    `json:"triggered_by"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
}

type SchedulerScheduleState struct {
	JobKey         string       `json:"job_key"`
	ScheduleKey    string       `json:"schedule_key"`
	LastCheckedAt  sql.NullTime `json:"last_checked_at"`
	LastEnqueuedAt sql.NullTime `json:"last_enqueued_at"`
	NextRunAt      sql.NullTime `json:"next_run_at"`
	UpdatedAt      time.Time    `json:"updated_at"`
}
