// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: 002_runs.sql

package db

import (
	"context"
)

const runCount = `-- name: RunCount :one
SELECT COUNT(1) AS total
FROM runs
`

func (q *Queries) RunCount(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, runCount)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const runCountByJobID = `-- name: RunCountByJobID :one
SELECT COUNT(1) AS total
FROM runs
WHERE job_id = ?
`

func (q *Queries) RunCountByJobID(ctx context.Context, jobID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, runCountByJobID, jobID)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const runCountFiltered = `-- name: RunCountFiltered :one
SELECT COUNT(1) AS total
FROM runs r
JOIN jobs j ON j.id = r.job_id
WHERE (?1 = 0 OR r.job_id = ?1)
  AND (?2 = '' OR r.status = ?2)
  AND (
    ?3 = ''
    OR LOWER(r.run_key) LIKE '%' || ?3 || '%'
    OR LOWER(j.job_key) LIKE '%' || ?3 || '%'
    OR LOWER(r.triggered_by) LIKE '%' || ?3 || '%'
  )
  AND (
    ?4 = ''
    OR (
      (?4 = 'backfills' AND LOWER(r.triggered_by) LIKE '%backfill%')
      OR (?4 = 'queued' AND r.status IN ('queued', 'pending'))
      OR (?4 = 'in_progress' AND r.status = 'running')
      OR (?4 = 'failed' AND r.status = 'failed')
      OR (?4 = 'scheduled' AND LOWER(r.triggered_by) LIKE '%schedule%')
    )
  )
  AND (
    ?5 = 0
    OR julianday(r.queued_at) >= julianday('now', '-' || ?5 || ' hours')
  )
`

type RunCountFilteredParams struct {
	JobID       interface{} `json:"job_id"`
	Status      interface{} `json:"status"`
	Search      interface{} `json:"search"`
	QuickFilter interface{} `json:"quick_filter"`
	WindowHours interface{} `json:"window_hours"`
}

func (q *Queries) RunCountFiltered(ctx context.Context, arg RunCountFilteredParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, runCountFiltered,
		arg.JobID,
		arg.Status,
		arg.Search,
		arg.QuickFilter,
		arg.WindowHours,
	)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const runCreate = `-- name: RunCreate :one
INSERT INTO runs (run_key, job_id, status, triggered_by, params_json, queued_at, started_at, completed_at, parent_run_id, rerun_step_key, error_message)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, run_key, job_id, status, triggered_by, params_json, queued_at, started_at, completed_at, parent_run_id, rerun_step_key, error_message, created_at, updated_at
`

type RunCreateParams struct {
	RunKey       string `json:"run_key"`
	JobID        int64  `json:"job_id"`
	Status       string `json:"status"`
	TriggeredBy  string `json:"triggered_by"`
	ParamsJson   string `json:"params_json"`
	QueuedAt     string `json:"queued_at"`
	StartedAt    string `json:"started_at"`
	CompletedAt  string `json:"completed_at"`
	ParentRunID  int64  `json:"parent_run_id"`
	RerunStepKey string `json:"rerun_step_key"`
	ErrorMessage string `json:"error_message"`
}

func (q *Queries) RunCreate(ctx context.Context, arg RunCreateParams) (Run, error) {
	row := q.db.QueryRowContext(ctx, runCreate,
		arg.RunKey,
		arg.JobID,
		arg.Status,
		arg.TriggeredBy,
		arg.ParamsJson,
		arg.QueuedAt,
		arg.StartedAt,
		arg.CompletedAt,
		arg.ParentRunID,
		arg.RerunStepKey,
		arg.ErrorMessage,
	)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.RunKey,
		&i.JobID,
		&i.Status,
		&i.TriggeredBy,
		&i.ParamsJson,
		&i.QueuedAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.ParentRunID,
		&i.RerunStepKey,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const runDeleteByID = `-- name: RunDeleteByID :exec
DELETE FROM runs
WHERE id = ?
`

func (q *Queries) RunDeleteByID(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, runDeleteByID, id)
	return err
}

const runEventCountByRunID = `-- name: RunEventCountByRunID :one
SELECT COUNT(*)
FROM run_events
WHERE run_id = ?
`

func (q *Queries) RunEventCountByRunID(ctx context.Context, runID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, runEventCountByRunID, runID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const runEventCreate = `-- name: RunEventCreate :one
INSERT INTO run_events (run_id, step_key, event_type, level, message, event_data_json)
VALUES (?, ?, ?, ?, ?, ?)
RETURNING id, run_id, step_key, event_type, level, message, event_data_json, created_at
`

type RunEventCreateParams struct {
	RunID         int64  `json:"run_id"`
	StepKey       string `json:"step_key"`
	EventType     string `json:"event_type"`
	Level         string `json:"level"`
	Message       string `json:"message"`
	EventDataJson string `json:"event_data_json"`
}

func (q *Queries) RunEventCreate(ctx context.Context, arg RunEventCreateParams) (RunEvent, error) {
	row := q.db.QueryRowContext(ctx, runEventCreate,
		arg.RunID,
		arg.StepKey,
		arg.EventType,
		arg.Level,
		arg.Message,
		arg.EventDataJson,
	)
	var i RunEvent
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.StepKey,
		&i.EventType,
		&i.Level,
		&i.Message,
		&i.EventDataJson,
		&i.CreatedAt,
	)
	return i, err
}

const runEventGetManyByRunID = `-- name: RunEventGetManyByRunID :many
SELECT id, run_id, step_key, event_type, level, message, event_data_json, created_at
FROM run_events
WHERE run_id = ?
ORDER BY id
LIMIT ? OFFSET ?
`

type RunEventGetManyByRunIDParams struct {
	RunID  int64 `json:"run_id"`
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

func (q *Queries) RunEventGetManyByRunID(ctx context.Context, arg RunEventGetManyByRunIDParams) ([]RunEvent, error) {
	rows, err := q.db.QueryContext(ctx, runEventGetManyByRunID, arg.RunID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RunEvent
	for rows.Next() {
		var i RunEvent
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.StepKey,
			&i.EventType,
			&i.Level,
			&i.Message,
			&i.EventDataJson,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const runGetByID = `-- name: RunGetByID :one
SELECT id, run_key, job_id, status, triggered_by, params_json, queued_at, started_at, completed_at, parent_run_id, rerun_step_key, error_message, created_at, updated_at
FROM runs
WHERE id = ?
`

func (q *Queries) RunGetByID(ctx context.Context, id int64) (Run, error) {
	row := q.db.QueryRowContext(ctx, runGetByID, id)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.RunKey,
		&i.JobID,
		&i.Status,
		&i.TriggeredBy,
		&i.ParamsJson,
		&i.QueuedAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.ParentRunID,
		&i.RerunStepKey,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const runGetByIDJoinedJobs = `-- name: RunGetByIDJoinedJobs :one
SELECT r.id,
       r.run_key,
       r.job_id,
       j.job_key,
       r.status,
       r.triggered_by,
       r.params_json,
       r.queued_at,
       r.started_at,
       r.completed_at,
       r.parent_run_id,
       r.rerun_step_key,
       r.error_message,
       r.created_at,
       r.updated_at
FROM runs r
JOIN jobs j ON j.id = r.job_id
WHERE r.id = ?
`

type RunGetByIDJoinedJobsRow struct {
	ID           int64  `json:"id"`
	RunKey       string `json:"run_key"`
	JobID        int64  `json:"job_id"`
	JobKey       string `json:"job_key"`
	Status       string `json:"status"`
	TriggeredBy  string `json:"triggered_by"`
	ParamsJson   string `json:"params_json"`
	QueuedAt     string `json:"queued_at"`
	StartedAt    string `json:"started_at"`
	CompletedAt  string `json:"completed_at"`
	ParentRunID  int64  `json:"parent_run_id"`
	RerunStepKey string `json:"rerun_step_key"`
	ErrorMessage string `json:"error_message"`
	CreatedAt    string `json:"created_at"`
	UpdatedAt    string `json:"updated_at"`
}

func (q *Queries) RunGetByIDJoinedJobs(ctx context.Context, id int64) (RunGetByIDJoinedJobsRow, error) {
	row := q.db.QueryRowContext(ctx, runGetByIDJoinedJobs, id)
	var i RunGetByIDJoinedJobsRow
	err := row.Scan(
		&i.ID,
		&i.RunKey,
		&i.JobID,
		&i.JobKey,
		&i.Status,
		&i.TriggeredBy,
		&i.ParamsJson,
		&i.QueuedAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.ParentRunID,
		&i.RerunStepKey,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const runGetMany = `-- name: RunGetMany :many
SELECT id, run_key, job_id, status, triggered_by, params_json, queued_at, started_at, completed_at, parent_run_id, rerun_step_key, error_message, created_at, updated_at
FROM runs
ORDER BY id DESC
LIMIT ? OFFSET ?
`

type RunGetManyParams struct {
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

func (q *Queries) RunGetMany(ctx context.Context, arg RunGetManyParams) ([]Run, error) {
	rows, err := q.db.QueryContext(ctx, runGetMany, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Run
	for rows.Next() {
		var i Run
		if err := rows.Scan(
			&i.ID,
			&i.RunKey,
			&i.JobID,
			&i.Status,
			&i.TriggeredBy,
			&i.ParamsJson,
			&i.QueuedAt,
			&i.StartedAt,
			&i.CompletedAt,
			&i.ParentRunID,
			&i.RerunStepKey,
			&i.ErrorMessage,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const runGetManyByJobID = `-- name: RunGetManyByJobID :many
SELECT id, run_key, job_id, status, triggered_by, params_json, queued_at, started_at, completed_at, parent_run_id, rerun_step_key, error_message, created_at, updated_at
FROM runs
WHERE job_id = ?
ORDER BY id DESC
LIMIT ? OFFSET ?
`

type RunGetManyByJobIDParams struct {
	JobID  int64 `json:"job_id"`
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

func (q *Queries) RunGetManyByJobID(ctx context.Context, arg RunGetManyByJobIDParams) ([]Run, error) {
	rows, err := q.db.QueryContext(ctx, runGetManyByJobID, arg.JobID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Run
	for rows.Next() {
		var i Run
		if err := rows.Scan(
			&i.ID,
			&i.RunKey,
			&i.JobID,
			&i.Status,
			&i.TriggeredBy,
			&i.ParamsJson,
			&i.QueuedAt,
			&i.StartedAt,
			&i.CompletedAt,
			&i.ParentRunID,
			&i.RerunStepKey,
			&i.ErrorMessage,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const runGetManyByJobIDJoinedJobs = `-- name: RunGetManyByJobIDJoinedJobs :many
SELECT r.id,
       r.run_key,
       r.job_id,
       j.job_key,
       r.status,
       r.triggered_by,
       r.params_json,
       r.queued_at,
       r.started_at,
       r.completed_at,
       r.parent_run_id,
       r.rerun_step_key,
       r.error_message,
       r.created_at,
       r.updated_at
FROM runs r
JOIN jobs j ON j.id = r.job_id
WHERE r.job_id = ?
ORDER BY r.id DESC
LIMIT ? OFFSET ?
`

type RunGetManyByJobIDJoinedJobsParams struct {
	JobID  int64 `json:"job_id"`
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

type RunGetManyByJobIDJoinedJobsRow struct {
	ID           int64  `json:"id"`
	RunKey       string `json:"run_key"`
	JobID        int64  `json:"job_id"`
	JobKey       string `json:"job_key"`
	Status       string `json:"status"`
	TriggeredBy  string `json:"triggered_by"`
	ParamsJson   string `json:"params_json"`
	QueuedAt     string `json:"queued_at"`
	StartedAt    string `json:"started_at"`
	CompletedAt  string `json:"completed_at"`
	ParentRunID  int64  `json:"parent_run_id"`
	RerunStepKey string `json:"rerun_step_key"`
	ErrorMessage string `json:"error_message"`
	CreatedAt    string `json:"created_at"`
	UpdatedAt    string `json:"updated_at"`
}

func (q *Queries) RunGetManyByJobIDJoinedJobs(ctx context.Context, arg RunGetManyByJobIDJoinedJobsParams) ([]RunGetManyByJobIDJoinedJobsRow, error) {
	rows, err := q.db.QueryContext(ctx, runGetManyByJobIDJoinedJobs, arg.JobID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RunGetManyByJobIDJoinedJobsRow
	for rows.Next() {
		var i RunGetManyByJobIDJoinedJobsRow
		if err := rows.Scan(
			&i.ID,
			&i.RunKey,
			&i.JobID,
			&i.JobKey,
			&i.Status,
			&i.TriggeredBy,
			&i.ParamsJson,
			&i.QueuedAt,
			&i.StartedAt,
			&i.CompletedAt,
			&i.ParentRunID,
			&i.RerunStepKey,
			&i.ErrorMessage,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const runGetManyByJobIDWithinWindowJoinedJobs = `-- name: RunGetManyByJobIDWithinWindowJoinedJobs :many
SELECT r.id,
       r.run_key,
       r.job_id,
       j.job_key,
       r.status,
       r.triggered_by,
       r.params_json,
       r.queued_at,
       r.started_at,
       r.completed_at,
       r.parent_run_id,
       r.rerun_step_key,
       r.error_message,
       r.created_at,
       r.updated_at
FROM runs r
JOIN jobs j ON j.id = r.job_id
WHERE r.job_id = ?1
  AND CASE WHEN r.started_at != '' THEN r.started_at ELSE r.queued_at END >= ?2
  AND CASE WHEN r.started_at != '' THEN r.started_at ELSE r.queued_at END <= ?3
ORDER BY CASE WHEN r.started_at != '' THEN r.started_at ELSE r.queued_at END DESC, r.id DESC
LIMIT ?5 OFFSET ?4
`

type RunGetManyByJobIDWithinWindowJoinedJobsParams struct {
	JobID       int64  `json:"job_id"`
	WindowStart string `json:"window_start"`
	WindowEnd   string `json:"window_end"`
	Offset      int64  `json:"offset"`
	Limit       int64  `json:"limit"`
}

type RunGetManyByJobIDWithinWindowJoinedJobsRow struct {
	ID           int64  `json:"id"`
	RunKey       string `json:"run_key"`
	JobID        int64  `json:"job_id"`
	JobKey       string `json:"job_key"`
	Status       string `json:"status"`
	TriggeredBy  string `json:"triggered_by"`
	ParamsJson   string `json:"params_json"`
	QueuedAt     string `json:"queued_at"`
	StartedAt    string `json:"started_at"`
	CompletedAt  string `json:"completed_at"`
	ParentRunID  int64  `json:"parent_run_id"`
	RerunStepKey string `json:"rerun_step_key"`
	ErrorMessage string `json:"error_message"`
	CreatedAt    string `json:"created_at"`
	UpdatedAt    string `json:"updated_at"`
}

func (q *Queries) RunGetManyByJobIDWithinWindowJoinedJobs(ctx context.Context, arg RunGetManyByJobIDWithinWindowJoinedJobsParams) ([]RunGetManyByJobIDWithinWindowJoinedJobsRow, error) {
	rows, err := q.db.QueryContext(ctx, runGetManyByJobIDWithinWindowJoinedJobs,
		arg.JobID,
		arg.WindowStart,
		arg.WindowEnd,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RunGetManyByJobIDWithinWindowJoinedJobsRow
	for rows.Next() {
		var i RunGetManyByJobIDWithinWindowJoinedJobsRow
		if err := rows.Scan(
			&i.ID,
			&i.RunKey,
			&i.JobID,
			&i.JobKey,
			&i.Status,
			&i.TriggeredBy,
			&i.ParamsJson,
			&i.QueuedAt,
			&i.StartedAt,
			&i.CompletedAt,
			&i.ParentRunID,
			&i.RerunStepKey,
			&i.ErrorMessage,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const runGetManyFilteredJoinedJobs = `-- name: RunGetManyFilteredJoinedJobs :many
SELECT r.id,
       r.run_key,
       r.job_id,
       j.job_key,
       r.status,
       r.triggered_by,
       r.params_json,
       r.queued_at,
       r.started_at,
       r.completed_at,
       r.parent_run_id,
       r.rerun_step_key,
       r.error_message,
       r.created_at,
       r.updated_at
FROM runs r
JOIN jobs j ON j.id = r.job_id
WHERE (?1 = 0 OR r.job_id = ?1)
  AND (?2 = '' OR r.status = ?2)
  AND (
    ?3 = ''
    OR LOWER(r.run_key) LIKE '%' || ?3 || '%'
    OR LOWER(j.job_key) LIKE '%' || ?3 || '%'
    OR LOWER(r.triggered_by) LIKE '%' || ?3 || '%'
  )
  AND (
    ?4 = ''
    OR (
      (?4 = 'backfills' AND LOWER(r.triggered_by) LIKE '%backfill%')
      OR (?4 = 'queued' AND r.status IN ('queued', 'pending'))
      OR (?4 = 'in_progress' AND r.status = 'running')
      OR (?4 = 'failed' AND r.status = 'failed')
      OR (?4 = 'scheduled' AND LOWER(r.triggered_by) LIKE '%schedule%')
    )
  )
  AND (
    ?5 = 0
    OR julianday(r.queued_at) >= julianday('now', '-' || ?5 || ' hours')
  )
ORDER BY CASE WHEN r.started_at != '' THEN r.started_at ELSE r.queued_at END DESC, r.id DESC
LIMIT ?7 OFFSET ?6
`

type RunGetManyFilteredJoinedJobsParams struct {
	JobID       interface{} `json:"job_id"`
	Status      interface{} `json:"status"`
	Search      interface{} `json:"search"`
	QuickFilter interface{} `json:"quick_filter"`
	WindowHours interface{} `json:"window_hours"`
	Offset      int64       `json:"offset"`
	Limit       int64       `json:"limit"`
}

type RunGetManyFilteredJoinedJobsRow struct {
	ID           int64  `json:"id"`
	RunKey       string `json:"run_key"`
	JobID        int64  `json:"job_id"`
	JobKey       string `json:"job_key"`
	Status       string `json:"status"`
	TriggeredBy  string `json:"triggered_by"`
	ParamsJson   string `json:"params_json"`
	QueuedAt     string `json:"queued_at"`
	StartedAt    string `json:"started_at"`
	CompletedAt  string `json:"completed_at"`
	ParentRunID  int64  `json:"parent_run_id"`
	RerunStepKey string `json:"rerun_step_key"`
	ErrorMessage string `json:"error_message"`
	CreatedAt    string `json:"created_at"`
	UpdatedAt    string `json:"updated_at"`
}

func (q *Queries) RunGetManyFilteredJoinedJobs(ctx context.Context, arg RunGetManyFilteredJoinedJobsParams) ([]RunGetManyFilteredJoinedJobsRow, error) {
	rows, err := q.db.QueryContext(ctx, runGetManyFilteredJoinedJobs,
		arg.JobID,
		arg.Status,
		arg.Search,
		arg.QuickFilter,
		arg.WindowHours,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RunGetManyFilteredJoinedJobsRow
	for rows.Next() {
		var i RunGetManyFilteredJoinedJobsRow
		if err := rows.Scan(
			&i.ID,
			&i.RunKey,
			&i.JobID,
			&i.JobKey,
			&i.Status,
			&i.TriggeredBy,
			&i.ParamsJson,
			&i.QueuedAt,
			&i.StartedAt,
			&i.CompletedAt,
			&i.ParentRunID,
			&i.RerunStepKey,
			&i.ErrorMessage,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const runGetManyFilteredJoinedJobsCursorNewest = `-- name: RunGetManyFilteredJoinedJobsCursorNewest :many
SELECT r.id,
       r.run_key,
       r.job_id,
       j.job_key,
       r.status,
       r.triggered_by,
       r.params_json,
       r.queued_at,
       r.started_at,
       r.completed_at,
       r.parent_run_id,
       r.rerun_step_key,
       r.error_message,
       r.created_at,
       r.updated_at
FROM runs r
JOIN jobs j ON j.id = r.job_id
WHERE (?1 = 0 OR r.job_id = ?1)
  AND (?2 = '' OR r.status = ?2)
  AND (
    ?3 = ''
    OR LOWER(r.run_key) LIKE '%' || ?3 || '%'
    OR LOWER(j.job_key) LIKE '%' || ?3 || '%'
    OR LOWER(r.triggered_by) LIKE '%' || ?3 || '%'
  )
  AND (
    ?4 = ''
    OR (
      (?4 = 'backfills' AND LOWER(r.triggered_by) LIKE '%backfill%')
      OR (?4 = 'queued' AND r.status IN ('queued', 'pending'))
      OR (?4 = 'in_progress' AND r.status = 'running')
      OR (?4 = 'failed' AND r.status = 'failed')
      OR (?4 = 'scheduled' AND LOWER(r.triggered_by) LIKE '%schedule%')
    )
  )
  AND (
    ?5 = 0
    OR julianday(r.queued_at) >= julianday('now', '-' || ?5 || ' hours')
  )
  AND (
    ?6 = ''
    OR CASE WHEN r.started_at != '' THEN r.started_at ELSE r.queued_at END < ?6
    OR (CASE WHEN r.started_at != '' THEN r.started_at ELSE r.queued_at END = ?6 AND r.id < ?7)
  )
ORDER BY CASE WHEN r.started_at != '' THEN r.started_at ELSE r.queued_at END DESC, r.id DESC
LIMIT ?8
`

type RunGetManyFilteredJoinedJobsCursorNewestParams struct {
	JobID       interface{} `json:"job_id"`
	Status      interface{} `json:"status"`
	Search      interface{} `json:"search"`
	QuickFilter interface{} `json:"quick_filter"`
	WindowHours interface{} `json:"window_hours"`
	CursorAt    interface{} `json:"cursor_at"`
	CursorID    int64       `json:"cursor_id"`
	Limit       int64       `json:"limit"`
}

type RunGetManyFilteredJoinedJobsCursorNewestRow struct {
	ID           int64  `json:"id"`
	RunKey       string `json:"run_key"`
	JobID        int64  `json:"job_id"`
	JobKey       string `json:"job_key"`
	Status       string `json:"status"`
	TriggeredBy  string `json:"triggered_by"`
	ParamsJson   string `json:"params_json"`
	QueuedAt     string `json:"queued_at"`
	StartedAt    string `json:"started_at"`
	CompletedAt  string `json:"completed_at"`
	ParentRunID  int64  `json:"parent_run_id"`
	RerunStepKey string `json:"rerun_step_key"`
	ErrorMessage string `json:"error_message"`
	CreatedAt    string `json:"created_at"`
	UpdatedAt    string `json:"updated_at"`
}

func (q *Queries) RunGetManyFilteredJoinedJobsCursorNewest(ctx context.Context, arg RunGetManyFilteredJoinedJobsCursorNewestParams) ([]RunGetManyFilteredJoinedJobsCursorNewestRow, error) {
	rows, err := q.db.QueryContext(ctx, runGetManyFilteredJoinedJobsCursorNewest,
		arg.JobID,
		arg.Status,
		arg.Search,
		arg.QuickFilter,
		arg.WindowHours,
		arg.CursorAt,
		arg.CursorID,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RunGetManyFilteredJoinedJobsCursorNewestRow
	for rows.Next() {
		var i RunGetManyFilteredJoinedJobsCursorNewestRow
		if err := rows.Scan(
			&i.ID,
			&i.RunKey,
			&i.JobID,
			&i.JobKey,
			&i.Status,
			&i.TriggeredBy,
			&i.ParamsJson,
			&i.QueuedAt,
			&i.StartedAt,
			&i.CompletedAt,
			&i.ParentRunID,
			&i.RerunStepKey,
			&i.ErrorMessage,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const runGetManyFilteredJoinedJobsCursorOldest = `-- name: RunGetManyFilteredJoinedJobsCursorOldest :many
SELECT r.id,
       r.run_key,
       r.job_id,
       j.job_key,
       r.status,
       r.triggered_by,
       r.params_json,
       r.queued_at,
       r.started_at,
       r.completed_at,
       r.parent_run_id,
       r.rerun_step_key,
       r.error_message,
       r.created_at,
       r.updated_at
FROM runs r
JOIN jobs j ON j.id = r.job_id
WHERE (?1 = 0 OR r.job_id = ?1)
  AND (?2 = '' OR r.status = ?2)
  AND (
    ?3 = ''
    OR LOWER(r.run_key) LIKE '%' || ?3 || '%'
    OR LOWER(j.job_key) LIKE '%' || ?3 || '%'
    OR LOWER(r.triggered_by) LIKE '%' || ?3 || '%'
  )
  AND (
    ?4 = ''
    OR (
      (?4 = 'backfills' AND LOWER(r.triggered_by) LIKE '%backfill%')
      OR (?4 = 'queued' AND r.status IN ('queued', 'pending'))
      OR (?4 = 'in_progress' AND r.status = 'running')
      OR (?4 = 'failed' AND r.status = 'failed')
      OR (?4 = 'scheduled' AND LOWER(r.triggered_by) LIKE '%schedule%')
    )
  )
  AND (
    ?5 = 0
    OR julianday(r.queued_at) >= julianday('now', '-' || ?5 || ' hours')
  )
  AND (
    ?6 = ''
    OR CASE WHEN r.started_at != '' THEN r.started_at ELSE r.queued_at END > ?6
    OR (CASE WHEN r.started_at != '' THEN r.started_at ELSE r.queued_at END = ?6 AND r.id > ?7)
  )
ORDER BY CASE WHEN r.started_at != '' THEN r.started_at ELSE r.queued_at END ASC, r.id ASC
LIMIT ?8
`

type RunGetManyFilteredJoinedJobsCursorOldestParams struct {
	JobID       interface{} `json:"job_id"`
	Status      interface{} `json:"status"`
	Search      interface{} `json:"search"`
	QuickFilter interface{} `json:"quick_filter"`
	WindowHours interface{} `json:"window_hours"`
	CursorAt    interface{} `json:"cursor_at"`
	CursorID    int64       `json:"cursor_id"`
	Limit       int64       `json:"limit"`
}

type RunGetManyFilteredJoinedJobsCursorOldestRow struct {
	ID           int64  `json:"id"`
	RunKey       string `json:"run_key"`
	JobID        int64  `json:"job_id"`
	JobKey       string `json:"job_key"`
	Status       string `json:"status"`
	TriggeredBy  string `json:"triggered_by"`
	ParamsJson   string `json:"params_json"`
	QueuedAt     string `json:"queued_at"`
	StartedAt    string `json:"started_at"`
	CompletedAt  string `json:"completed_at"`
	ParentRunID  int64  `json:"parent_run_id"`
	RerunStepKey string `json:"rerun_step_key"`
	ErrorMessage string `json:"error_message"`
	CreatedAt    string `json:"created_at"`
	UpdatedAt    string `json:"updated_at"`
}

func (q *Queries) RunGetManyFilteredJoinedJobsCursorOldest(ctx context.Context, arg RunGetManyFilteredJoinedJobsCursorOldestParams) ([]RunGetManyFilteredJoinedJobsCursorOldestRow, error) {
	rows, err := q.db.QueryContext(ctx, runGetManyFilteredJoinedJobsCursorOldest,
		arg.JobID,
		arg.Status,
		arg.Search,
		arg.QuickFilter,
		arg.WindowHours,
		arg.CursorAt,
		arg.CursorID,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RunGetManyFilteredJoinedJobsCursorOldestRow
	for rows.Next() {
		var i RunGetManyFilteredJoinedJobsCursorOldestRow
		if err := rows.Scan(
			&i.ID,
			&i.RunKey,
			&i.JobID,
			&i.JobKey,
			&i.Status,
			&i.TriggeredBy,
			&i.ParamsJson,
			&i.QueuedAt,
			&i.StartedAt,
			&i.CompletedAt,
			&i.ParentRunID,
			&i.RerunStepKey,
			&i.ErrorMessage,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const runGetManyFilteredJoinedJobsDurationDesc = `-- name: RunGetManyFilteredJoinedJobsDurationDesc :many
SELECT r.id,
       r.run_key,
       r.job_id,
       j.job_key,
       r.status,
       r.triggered_by,
       r.params_json,
       r.queued_at,
       r.started_at,
       r.completed_at,
       r.parent_run_id,
       r.rerun_step_key,
       r.error_message,
       r.created_at,
       r.updated_at
FROM runs r
JOIN jobs j ON j.id = r.job_id
WHERE (?1 = 0 OR r.job_id = ?1)
  AND (?2 = '' OR r.status = ?2)
  AND (
    ?3 = ''
    OR LOWER(r.run_key) LIKE '%' || ?3 || '%'
    OR LOWER(j.job_key) LIKE '%' || ?3 || '%'
    OR LOWER(r.triggered_by) LIKE '%' || ?3 || '%'
  )
  AND (
    ?4 = ''
    OR (
      (?4 = 'backfills' AND LOWER(r.triggered_by) LIKE '%backfill%')
      OR (?4 = 'queued' AND r.status IN ('queued', 'pending'))
      OR (?4 = 'in_progress' AND r.status = 'running')
      OR (?4 = 'failed' AND r.status = 'failed')
      OR (?4 = 'scheduled' AND LOWER(r.triggered_by) LIKE '%schedule%')
    )
  )
  AND (
    ?5 = 0
    OR julianday(r.queued_at) >= julianday('now', '-' || ?5 || ' hours')
  )
ORDER BY
  CASE
    WHEN r.started_at != '' AND r.completed_at != '' THEN CAST((julianday(r.completed_at) - julianday(r.started_at)) * 86400000 AS INTEGER)
    ELSE 0
  END DESC,
  CASE WHEN r.started_at != '' THEN r.started_at ELSE r.queued_at END DESC,
  r.id DESC
LIMIT ?7 OFFSET ?6
`

type RunGetManyFilteredJoinedJobsDurationDescParams struct {
	JobID       interface{} `json:"job_id"`
	Status      interface{} `json:"status"`
	Search      interface{} `json:"search"`
	QuickFilter interface{} `json:"quick_filter"`
	WindowHours interface{} `json:"window_hours"`
	Offset      int64       `json:"offset"`
	Limit       int64       `json:"limit"`
}

type RunGetManyFilteredJoinedJobsDurationDescRow struct {
	ID           int64  `json:"id"`
	RunKey       string `json:"run_key"`
	JobID        int64  `json:"job_id"`
	JobKey       string `json:"job_key"`
	Status       string `json:"status"`
	TriggeredBy  string `json:"triggered_by"`
	ParamsJson   string `json:"params_json"`
	QueuedAt     string `json:"queued_at"`
	StartedAt    string `json:"started_at"`
	CompletedAt  string `json:"completed_at"`
	ParentRunID  int64  `json:"parent_run_id"`
	RerunStepKey string `json:"rerun_step_key"`
	ErrorMessage string `json:"error_message"`
	CreatedAt    string `json:"created_at"`
	UpdatedAt    string `json:"updated_at"`
}

func (q *Queries) RunGetManyFilteredJoinedJobsDurationDesc(ctx context.Context, arg RunGetManyFilteredJoinedJobsDurationDescParams) ([]RunGetManyFilteredJoinedJobsDurationDescRow, error) {
	rows, err := q.db.QueryContext(ctx, runGetManyFilteredJoinedJobsDurationDesc,
		arg.JobID,
		arg.Status,
		arg.Search,
		arg.QuickFilter,
		arg.WindowHours,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RunGetManyFilteredJoinedJobsDurationDescRow
	for rows.Next() {
		var i RunGetManyFilteredJoinedJobsDurationDescRow
		if err := rows.Scan(
			&i.ID,
			&i.RunKey,
			&i.JobID,
			&i.JobKey,
			&i.Status,
			&i.TriggeredBy,
			&i.ParamsJson,
			&i.QueuedAt,
			&i.StartedAt,
			&i.CompletedAt,
			&i.ParentRunID,
			&i.RerunStepKey,
			&i.ErrorMessage,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const runGetManyFilteredJoinedJobsOldest = `-- name: RunGetManyFilteredJoinedJobsOldest :many
SELECT r.id,
       r.run_key,
       r.job_id,
       j.job_key,
       r.status,
       r.triggered_by,
       r.params_json,
       r.queued_at,
       r.started_at,
       r.completed_at,
       r.parent_run_id,
       r.rerun_step_key,
       r.error_message,
       r.created_at,
       r.updated_at
FROM runs r
JOIN jobs j ON j.id = r.job_id
WHERE (?1 = 0 OR r.job_id = ?1)
  AND (?2 = '' OR r.status = ?2)
  AND (
    ?3 = ''
    OR LOWER(r.run_key) LIKE '%' || ?3 || '%'
    OR LOWER(j.job_key) LIKE '%' || ?3 || '%'
    OR LOWER(r.triggered_by) LIKE '%' || ?3 || '%'
  )
  AND (
    ?4 = ''
    OR (
      (?4 = 'backfills' AND LOWER(r.triggered_by) LIKE '%backfill%')
      OR (?4 = 'queued' AND r.status IN ('queued', 'pending'))
      OR (?4 = 'in_progress' AND r.status = 'running')
      OR (?4 = 'failed' AND r.status = 'failed')
      OR (?4 = 'scheduled' AND LOWER(r.triggered_by) LIKE '%schedule%')
    )
  )
  AND (
    ?5 = 0
    OR julianday(r.queued_at) >= julianday('now', '-' || ?5 || ' hours')
  )
ORDER BY CASE WHEN r.started_at != '' THEN r.started_at ELSE r.queued_at END ASC, r.id ASC
LIMIT ?7 OFFSET ?6
`

type RunGetManyFilteredJoinedJobsOldestParams struct {
	JobID       interface{} `json:"job_id"`
	Status      interface{} `json:"status"`
	Search      interface{} `json:"search"`
	QuickFilter interface{} `json:"quick_filter"`
	WindowHours interface{} `json:"window_hours"`
	Offset      int64       `json:"offset"`
	Limit       int64       `json:"limit"`
}

type RunGetManyFilteredJoinedJobsOldestRow struct {
	ID           int64  `json:"id"`
	RunKey       string `json:"run_key"`
	JobID        int64  `json:"job_id"`
	JobKey       string `json:"job_key"`
	Status       string `json:"status"`
	TriggeredBy  string `json:"triggered_by"`
	ParamsJson   string `json:"params_json"`
	QueuedAt     string `json:"queued_at"`
	StartedAt    string `json:"started_at"`
	CompletedAt  string `json:"completed_at"`
	ParentRunID  int64  `json:"parent_run_id"`
	RerunStepKey string `json:"rerun_step_key"`
	ErrorMessage string `json:"error_message"`
	CreatedAt    string `json:"created_at"`
	UpdatedAt    string `json:"updated_at"`
}

func (q *Queries) RunGetManyFilteredJoinedJobsOldest(ctx context.Context, arg RunGetManyFilteredJoinedJobsOldestParams) ([]RunGetManyFilteredJoinedJobsOldestRow, error) {
	rows, err := q.db.QueryContext(ctx, runGetManyFilteredJoinedJobsOldest,
		arg.JobID,
		arg.Status,
		arg.Search,
		arg.QuickFilter,
		arg.WindowHours,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RunGetManyFilteredJoinedJobsOldestRow
	for rows.Next() {
		var i RunGetManyFilteredJoinedJobsOldestRow
		if err := rows.Scan(
			&i.ID,
			&i.RunKey,
			&i.JobID,
			&i.JobKey,
			&i.Status,
			&i.TriggeredBy,
			&i.ParamsJson,
			&i.QueuedAt,
			&i.StartedAt,
			&i.CompletedAt,
			&i.ParentRunID,
			&i.RerunStepKey,
			&i.ErrorMessage,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const runGetManyForRetentionPurge = `-- name: RunGetManyForRetentionPurge :many
SELECT id
FROM runs
WHERE completed_at != ''
  AND completed_at < ?
  AND status IN ('success', 'failed', 'canceled', 'cancelled')
ORDER BY completed_at, id
LIMIT ?
`

type RunGetManyForRetentionPurgeParams struct {
	CompletedAt string `json:"completed_at"`
	Limit       int64  `json:"limit"`
}

func (q *Queries) RunGetManyForRetentionPurge(ctx context.Context, arg RunGetManyForRetentionPurgeParams) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, runGetManyForRetentionPurge, arg.CompletedAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const runGetManyJoinedJobs = `-- name: RunGetManyJoinedJobs :many
SELECT r.id,
       r.run_key,
       r.job_id,
       j.job_key,
       r.status,
       r.triggered_by,
       r.params_json,
       r.queued_at,
       r.started_at,
       r.completed_at,
       r.parent_run_id,
       r.rerun_step_key,
       r.error_message,
       r.created_at,
       r.updated_at
FROM runs r
JOIN jobs j ON j.id = r.job_id
ORDER BY r.id DESC
LIMIT ? OFFSET ?
`

type RunGetManyJoinedJobsParams struct {
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

type RunGetManyJoinedJobsRow struct {
	ID           int64  `json:"id"`
	RunKey       string `json:"run_key"`
	JobID        int64  `json:"job_id"`
	JobKey       string `json:"job_key"`
	Status       string `json:"status"`
	TriggeredBy  string `json:"triggered_by"`
	ParamsJson   string `json:"params_json"`
	QueuedAt     string `json:"queued_at"`
	StartedAt    string `json:"started_at"`
	CompletedAt  string `json:"completed_at"`
	ParentRunID  int64  `json:"parent_run_id"`
	RerunStepKey string `json:"rerun_step_key"`
	ErrorMessage string `json:"error_message"`
	CreatedAt    string `json:"created_at"`
	UpdatedAt    string `json:"updated_at"`
}

func (q *Queries) RunGetManyJoinedJobs(ctx context.Context, arg RunGetManyJoinedJobsParams) ([]RunGetManyJoinedJobsRow, error) {
	rows, err := q.db.QueryContext(ctx, runGetManyJoinedJobs, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RunGetManyJoinedJobsRow
	for rows.Next() {
		var i RunGetManyJoinedJobsRow
		if err := rows.Scan(
			&i.ID,
			&i.RunKey,
			&i.JobID,
			&i.JobKey,
			&i.Status,
			&i.TriggeredBy,
			&i.ParamsJson,
			&i.QueuedAt,
			&i.StartedAt,
			&i.CompletedAt,
			&i.ParentRunID,
			&i.RerunStepKey,
			&i.ErrorMessage,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const runStepCreate = `-- name: RunStepCreate :one
INSERT INTO run_steps (run_id, job_node_id, step_key, status, attempt, started_at, completed_at, duration_ms, output_json, error_message, log_excerpt)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, run_id, job_node_id, step_key, status, attempt, started_at, completed_at, duration_ms, output_json, error_message, log_excerpt, created_at, updated_at
`

type RunStepCreateParams struct {
	RunID        int64  `json:"run_id"`
	JobNodeID    int64  `json:"job_node_id"`
	StepKey      string `json:"step_key"`
	Status       string `json:"status"`
	Attempt      int64  `json:"attempt"`
	StartedAt    string `json:"started_at"`
	CompletedAt  string `json:"completed_at"`
	DurationMs   int64  `json:"duration_ms"`
	OutputJson   string `json:"output_json"`
	ErrorMessage string `json:"error_message"`
	LogExcerpt   string `json:"log_excerpt"`
}

func (q *Queries) RunStepCreate(ctx context.Context, arg RunStepCreateParams) (RunStep, error) {
	row := q.db.QueryRowContext(ctx, runStepCreate,
		arg.RunID,
		arg.JobNodeID,
		arg.StepKey,
		arg.Status,
		arg.Attempt,
		arg.StartedAt,
		arg.CompletedAt,
		arg.DurationMs,
		arg.OutputJson,
		arg.ErrorMessage,
		arg.LogExcerpt,
	)
	var i RunStep
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.JobNodeID,
		&i.StepKey,
		&i.Status,
		&i.Attempt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.DurationMs,
		&i.OutputJson,
		&i.ErrorMessage,
		&i.LogExcerpt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const runStepGetByRunIDAndStepKey = `-- name: RunStepGetByRunIDAndStepKey :one
SELECT id, run_id, job_node_id, step_key, status, attempt, started_at, completed_at, duration_ms, output_json, error_message, log_excerpt, created_at, updated_at
FROM run_steps
WHERE run_id = ? AND step_key = ?
`

type RunStepGetByRunIDAndStepKeyParams struct {
	RunID   int64  `json:"run_id"`
	StepKey string `json:"step_key"`
}

func (q *Queries) RunStepGetByRunIDAndStepKey(ctx context.Context, arg RunStepGetByRunIDAndStepKeyParams) (RunStep, error) {
	row := q.db.QueryRowContext(ctx, runStepGetByRunIDAndStepKey, arg.RunID, arg.StepKey)
	var i RunStep
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.JobNodeID,
		&i.StepKey,
		&i.Status,
		&i.Attempt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.DurationMs,
		&i.OutputJson,
		&i.ErrorMessage,
		&i.LogExcerpt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const runStepGetManyByRunID = `-- name: RunStepGetManyByRunID :many
SELECT id, run_id, job_node_id, step_key, status, attempt, started_at, completed_at, duration_ms, output_json, error_message, log_excerpt, created_at, updated_at
FROM run_steps
WHERE run_id = ?
ORDER BY id
`

func (q *Queries) RunStepGetManyByRunID(ctx context.Context, runID int64) ([]RunStep, error) {
	rows, err := q.db.QueryContext(ctx, runStepGetManyByRunID, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RunStep
	for rows.Next() {
		var i RunStep
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.JobNodeID,
			&i.StepKey,
			&i.Status,
			&i.Attempt,
			&i.StartedAt,
			&i.CompletedAt,
			&i.DurationMs,
			&i.OutputJson,
			&i.ErrorMessage,
			&i.LogExcerpt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const runStepUpdateForComplete = `-- name: RunStepUpdateForComplete :one
UPDATE run_steps
SET status = ?,
    completed_at = ?,
    duration_ms = ?,
    output_json = ?,
    error_message = ?,
    log_excerpt = ?,
    updated_at = CURRENT_TIMESTAMP
WHERE run_id = ? AND step_key = ?
RETURNING id, run_id, job_node_id, step_key, status, attempt, started_at, completed_at, duration_ms, output_json, error_message, log_excerpt, created_at, updated_at
`

type RunStepUpdateForCompleteParams struct {
	Status       string `json:"status"`
	CompletedAt  string `json:"completed_at"`
	DurationMs   int64  `json:"duration_ms"`
	OutputJson   string `json:"output_json"`
	ErrorMessage string `json:"error_message"`
	LogExcerpt   string `json:"log_excerpt"`
	RunID        int64  `json:"run_id"`
	StepKey      string `json:"step_key"`
}

func (q *Queries) RunStepUpdateForComplete(ctx context.Context, arg RunStepUpdateForCompleteParams) (RunStep, error) {
	row := q.db.QueryRowContext(ctx, runStepUpdateForComplete,
		arg.Status,
		arg.CompletedAt,
		arg.DurationMs,
		arg.OutputJson,
		arg.ErrorMessage,
		arg.LogExcerpt,
		arg.RunID,
		arg.StepKey,
	)
	var i RunStep
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.JobNodeID,
		&i.StepKey,
		&i.Status,
		&i.Attempt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.DurationMs,
		&i.OutputJson,
		&i.ErrorMessage,
		&i.LogExcerpt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const runStepUpdateForStart = `-- name: RunStepUpdateForStart :one
UPDATE run_steps
SET status = ?,
    started_at = ?,
    updated_at = CURRENT_TIMESTAMP
WHERE run_id = ? AND step_key = ?
RETURNING id, run_id, job_node_id, step_key, status, attempt, started_at, completed_at, duration_ms, output_json, error_message, log_excerpt, created_at, updated_at
`

type RunStepUpdateForStartParams struct {
	Status    string `json:"status"`
	StartedAt string `json:"started_at"`
	RunID     int64  `json:"run_id"`
	StepKey   string `json:"step_key"`
}

func (q *Queries) RunStepUpdateForStart(ctx context.Context, arg RunStepUpdateForStartParams) (RunStep, error) {
	row := q.db.QueryRowContext(ctx, runStepUpdateForStart,
		arg.Status,
		arg.StartedAt,
		arg.RunID,
		arg.StepKey,
	)
	var i RunStep
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.JobNodeID,
		&i.StepKey,
		&i.Status,
		&i.Attempt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.DurationMs,
		&i.OutputJson,
		&i.ErrorMessage,
		&i.LogExcerpt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const runUpdateForComplete = `-- name: RunUpdateForComplete :one
UPDATE runs
SET status = ?,
    completed_at = ?,
    error_message = ?,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ?
RETURNING id, run_key, job_id, status, triggered_by, params_json, queued_at, started_at, completed_at, parent_run_id, rerun_step_key, error_message, created_at, updated_at
`

type RunUpdateForCompleteParams struct {
	Status       string `json:"status"`
	CompletedAt  string `json:"completed_at"`
	ErrorMessage string `json:"error_message"`
	ID           int64  `json:"id"`
}

func (q *Queries) RunUpdateForComplete(ctx context.Context, arg RunUpdateForCompleteParams) (Run, error) {
	row := q.db.QueryRowContext(ctx, runUpdateForComplete,
		arg.Status,
		arg.CompletedAt,
		arg.ErrorMessage,
		arg.ID,
	)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.RunKey,
		&i.JobID,
		&i.Status,
		&i.TriggeredBy,
		&i.ParamsJson,
		&i.QueuedAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.ParentRunID,
		&i.RerunStepKey,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const runUpdateForStart = `-- name: RunUpdateForStart :one
UPDATE runs
SET status = ?,
    started_at = ?,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ?
RETURNING id, run_key, job_id, status, triggered_by, params_json, queued_at, started_at, completed_at, parent_run_id, rerun_step_key, error_message, created_at, updated_at
`

type RunUpdateForStartParams struct {
	Status    string `json:"status"`
	StartedAt string `json:"started_at"`
	ID        int64  `json:"id"`
}

func (q *Queries) RunUpdateForStart(ctx context.Context, arg RunUpdateForStartParams) (Run, error) {
	row := q.db.QueryRowContext(ctx, runUpdateForStart, arg.Status, arg.StartedAt, arg.ID)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.RunKey,
		&i.JobID,
		&i.Status,
		&i.TriggeredBy,
		&i.ParamsJson,
		&i.QueuedAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.ParentRunID,
		&i.RerunStepKey,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
