// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

type Job struct {
	ID                int64  `json:"id"`
	JobKey            string `json:"job_key"`
	DisplayName       string `json:"display_name"`
	Description       string `json:"description"`
	DefaultParamsJson string `json:"default_params_json"`
	CreatedAt         string `json:"created_at"`
	UpdatedAt         string `json:"updated_at"`
}

type JobEdge struct {
	ID          int64  `json:"id"`
	JobID       int64  `json:"job_id"`
	FromStepKey string `json:"from_step_key"`
	ToStepKey   string `json:"to_step_key"`
	CreatedAt   string `json:"created_at"`
}

type JobNode struct {
	ID           int64  `json:"id"`
	JobID        int64  `json:"job_id"`
	StepKey      string `json:"step_key"`
	DisplayName  string `json:"display_name"`
	Description  string `json:"description"`
	Kind         string `json:"kind"`
	MetadataJson string `json:"metadata_json"`
	SortIndex    int64  `json:"sort_index"`
	CreatedAt    string `json:"created_at"`
}

type JobSchedule struct {
	ID          int64  `json:"id"`
	JobID       int64  `json:"job_id"`
	ScheduleKey string `json:"schedule_key"`
	CronExpr    string `json:"cron_expr"`
	Timezone    string `json:"timezone"`
	IsEnabled   int64  `json:"is_enabled"`
	Description string `json:"description"`
	CreatedAt   string `json:"created_at"`
	UpdatedAt   string `json:"updated_at"`
}

type Run struct {
	ID           int64  `json:"id"`
	RunKey       string `json:"run_key"`
	JobID        int64  `json:"job_id"`
	Status       string `json:"status"`
	TriggeredBy  string `json:"triggered_by"`
	ParamsJson   string `json:"params_json"`
	QueuedAt     string `json:"queued_at"`
	StartedAt    string `json:"started_at"`
	CompletedAt  string `json:"completed_at"`
	ParentRunID  int64  `json:"parent_run_id"`
	RerunStepKey string `json:"rerun_step_key"`
	ErrorMessage string `json:"error_message"`
	CreatedAt    string `json:"created_at"`
	UpdatedAt    string `json:"updated_at"`
}

type RunEvent struct {
	ID            int64  `json:"id"`
	RunID         int64  `json:"run_id"`
	StepKey       string `json:"step_key"`
	EventType     string `json:"event_type"`
	Level         string `json:"level"`
	Message       string `json:"message"`
	EventDataJson string `json:"event_data_json"`
	CreatedAt     string `json:"created_at"`
}

type RunStep struct {
	ID           int64  `json:"id"`
	RunID        int64  `json:"run_id"`
	JobNodeID    int64  `json:"job_node_id"`
	StepKey      string `json:"step_key"`
	Status       string `json:"status"`
	Attempt      int64  `json:"attempt"`
	StartedAt    string `json:"started_at"`
	CompletedAt  string `json:"completed_at"`
	DurationMs   int64  `json:"duration_ms"`
	OutputJson   string `json:"output_json"`
	ErrorMessage string `json:"error_message"`
	LogExcerpt   string `json:"log_excerpt"`
	CreatedAt    string `json:"created_at"`
	UpdatedAt    string `json:"updated_at"`
}

type SchedulerHeartbeat struct {
	SchedulerKey        string `json:"scheduler_key"`
	LastHeartbeatAt     string `json:"last_heartbeat_at"`
	LastTickStartedAt   string `json:"last_tick_started_at"`
	LastTickCompletedAt string `json:"last_tick_completed_at"`
	LastError           string `json:"last_error"`
	UpdatedAt           string `json:"updated_at"`
}

type SchedulerScheduleRun struct {
	ID            int64  `json:"id"`
	JobScheduleID int64  `json:"job_schedule_id"`
	ScheduledFor  string `json:"scheduled_for"`
	RunKey        string `json:"run_key"`
	TriggeredBy   string `json:"triggered_by"`
	CreatedAt     string `json:"created_at"`
	UpdatedAt     string `json:"updated_at"`
}

type SchedulerScheduleState struct {
	JobScheduleID  int64  `json:"job_schedule_id"`
	LastCheckedAt  string `json:"last_checked_at"`
	LastEnqueuedAt string `json:"last_enqueued_at"`
	NextRunAt      string `json:"next_run_at"`
	UpdatedAt      string `json:"updated_at"`
}
