// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

type Job struct {
	ID                int64  `json:"id"`
	JobKey            string `json:"job_key"`
	DisplayName       string `json:"display_name"`
	Description       string `json:"description"`
	DefaultParamsJson string `json:"default_params_json"`
	CreatedAt         string `json:"created_at"`
	UpdatedAt         string `json:"updated_at"`
}

type JobEdge struct {
	ID          int64  `json:"id"`
	JobID       int64  `json:"job_id"`
	FromStepKey string `json:"from_step_key"`
	ToStepKey   string `json:"to_step_key"`
	CreatedAt   string `json:"created_at"`
}

type JobNode struct {
	ID           int64  `json:"id"`
	JobID        int64  `json:"job_id"`
	StepKey      string `json:"step_key"`
	DisplayName  string `json:"display_name"`
	Description  string `json:"description"`
	Kind         string `json:"kind"`
	MetadataJson string `json:"metadata_json"`
	SortIndex    int64  `json:"sort_index"`
	CreatedAt    string `json:"created_at"`
}

type Queue struct {
	ID                   int64  `json:"id"`
	QueueKey             string `json:"queue_key"`
	DisplayName          string `json:"display_name"`
	Description          string `json:"description"`
	RoutePath            string `json:"route_path"`
	LoadMode             string `json:"load_mode"`
	LoadPollEverySeconds int64  `json:"load_poll_every_seconds"`
	CreatedAt            string `json:"created_at"`
	UpdatedAt            string `json:"updated_at"`
}

type QueueItem struct {
	ID           int64  `json:"id"`
	QueueID      int64  `json:"queue_id"`
	QueueItemKey string `json:"queue_item_key"`
	PartitionKey string `json:"partition_key"`
	Status       string `json:"status"`
	ExternalKey  string `json:"external_key"`
	PayloadJson  string `json:"payload_json"`
	ErrorMessage string `json:"error_message"`
	QueuedAt     string `json:"queued_at"`
	StartedAt    string `json:"started_at"`
	CompletedAt  string `json:"completed_at"`
	CreatedAt    string `json:"created_at"`
	UpdatedAt    string `json:"updated_at"`
}

type QueueItemRun struct {
	ID          int64  `json:"id"`
	QueueItemID int64  `json:"queue_item_id"`
	JobID       int64  `json:"job_id"`
	RunID       int64  `json:"run_id"`
	CreatedAt   string `json:"created_at"`
}

type QueueItemStepMetadatum struct {
	ID           int64  `json:"id"`
	QueueItemID  int64  `json:"queue_item_id"`
	JobID        int64  `json:"job_id"`
	RunID        int64  `json:"run_id"`
	StepKey      string `json:"step_key"`
	MetadataJson string `json:"metadata_json"`
	CreatedAt    string `json:"created_at"`
	UpdatedAt    string `json:"updated_at"`
}

type QueueJob struct {
	ID        int64  `json:"id"`
	QueueID   int64  `json:"queue_id"`
	JobID     int64  `json:"job_id"`
	SortIndex int64  `json:"sort_index"`
	CreatedAt string `json:"created_at"`
}

type Run struct {
	ID           int64  `json:"id"`
	RunKey       string `json:"run_key"`
	JobID        int64  `json:"job_id"`
	Status       string `json:"status"`
	TriggeredBy  string `json:"triggered_by"`
	ParamsJson   string `json:"params_json"`
	QueuedAt     string `json:"queued_at"`
	StartedAt    string `json:"started_at"`
	CompletedAt  string `json:"completed_at"`
	ParentRunID  int64  `json:"parent_run_id"`
	RerunStepKey string `json:"rerun_step_key"`
	ErrorMessage string `json:"error_message"`
	CreatedAt    string `json:"created_at"`
	UpdatedAt    string `json:"updated_at"`
}

type RunEvent struct {
	ID            int64  `json:"id"`
	RunID         int64  `json:"run_id"`
	StepKey       string `json:"step_key"`
	EventType     string `json:"event_type"`
	Level         string `json:"level"`
	Message       string `json:"message"`
	EventDataJson string `json:"event_data_json"`
	CreatedAt     string `json:"created_at"`
}

type RunStep struct {
	ID           int64  `json:"id"`
	RunID        int64  `json:"run_id"`
	JobNodeID    int64  `json:"job_node_id"`
	StepKey      string `json:"step_key"`
	Status       string `json:"status"`
	Attempt      int64  `json:"attempt"`
	StartedAt    string `json:"started_at"`
	CompletedAt  string `json:"completed_at"`
	DurationMs   int64  `json:"duration_ms"`
	OutputJson   string `json:"output_json"`
	ErrorMessage string `json:"error_message"`
	LogExcerpt   string `json:"log_excerpt"`
	CreatedAt    string `json:"created_at"`
	UpdatedAt    string `json:"updated_at"`
}

type SchedulerHeartbeat struct {
	SchedulerKey        string `json:"scheduler_key"`
	LastHeartbeatAt     string `json:"last_heartbeat_at"`
	LastTickStartedAt   string `json:"last_tick_started_at"`
	LastTickCompletedAt string `json:"last_tick_completed_at"`
	LastError           string `json:"last_error"`
	UpdatedAt           string `json:"updated_at"`
}

type SchedulerScheduleRun struct {
	ID           int64  `json:"id"`
	JobKey       string `json:"job_key"`
	ScheduleKey  string `json:"schedule_key"`
	ScheduledFor string `json:"scheduled_for"`
	RunKey       string `json:"run_key"`
	TriggeredBy  string `json:"triggered_by"`
	CreatedAt    string `json:"created_at"`
	UpdatedAt    string `json:"updated_at"`
}

type SchedulerScheduleState struct {
	JobKey         string `json:"job_key"`
	ScheduleKey    string `json:"schedule_key"`
	LastCheckedAt  string `json:"last_checked_at"`
	LastEnqueuedAt string `json:"last_enqueued_at"`
	NextRunAt      string `json:"next_run_at"`
	UpdatedAt      string `json:"updated_at"`
}
